import { GalleryHeroAtmosphere } from '../components/GalleryHeroVisuals';
import { useMotionGate } from '../hooks/useMotionGate';
import '../styles/gallery-heroes.css';
import './roadmap-gallery.css';
import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { BracketCanvas } from './BracketCanvas';
import { MatchDetail } from './MatchDetail';
import { Lightbox } from './Lightbox';
import { type Match, type Presentation } from './model.mjs';
import type { Bracket } from './types';
const ROOT = '/polls/abootnothing/brackets';
type Item = Presentation & { id: string };
async function read<T>(path: string): Promise<T> { const r = await fetch(`/api/brackets${path}`, { cache: 'no-store' }); const p = await r.json(); if (!r.ok || !p.ok) throw new Error(p.message || 'This roadmap is unavailable.'); return p; }
export function RoadmapShelf() {
  const [items, setItems] = useState<Item[]>([]);
  useEffect(() => { void read<{ items: Item[] }>('').then(p => setItems(p.items)).catch(() => {}); }, []);
  return <section className="container roadmap-page"><p className="bracket-eyebrow">The season ahead</p><h2>Season Roadmaps</h2><p>Follow the matchups from opening round to the final decision.</p><Link to={ROOT}>Explore Roadmaps &amp; Seasons →</Link>{items.length ? <div className="bracket-library">{items.slice(0,3).map(p => <RoadmapCard key={p.id} item={p} />)}</div> : null}</section>;
}
function RoadmapCard({ item }: { item: Item }) {
  return <Link className="season-card" to={`${ROOT}/${item.slug}`}>
    <div className="season-card__art">{item.feature || item.cover ? <img src={`/api/brackets/media/${item.feature || item.cover}`} alt="" loading="lazy" /> : <div className="season-card__placeholder" aria-hidden="true"><span>THE ROAD TO</span><strong>THE FINAL.</strong><span>ABOOT NOTHING / SEASON ROADMAP</span></div>}<span className="season-card__badge">Season roadmap</span></div>
    <div className="season-card__body"><p className="bracket-eyebrow">{item.season || 'Aboot Nothing'}</p><h2>{item.title}</h2>{item.intro ? <p className="season-card__intro">{item.intro}</p> : <p className="season-card__intro">Explore the contenders, follow each round and see who advances.</p>}<span className="season-card__open">Explore season <span aria-hidden="true">&#8599;</span></span></div>
  </Link>;
}
function SeasonHero() {
  const motion = useMotionGate<HTMLElement>();
  return <header ref={motion.ref} className={`season-hero gallery-hero${motion.active ? ' is-motion-active' : ''}`}>
    <GalleryHeroAtmosphere variant="polls" />
    <div className="container season-hero__grid"><div className="season-hero__copy"><Link className="season-back" to="/polls/abootnothing">&#8592; Aboot Nothing</Link><p className="eyebrow">THE THIRD RAIL / SEASON ROADMAPS</p><h1>Every round.<br /><em>One champion.</em></h1><p className="season-hero__intro">Big rivalries. Tough calls. One place to follow the whole story, from the opening matchups to the final showdown.</p><div className="season-hero__actions"><a className="button button--primary" href="#season-directory">Explore the seasons <span aria-hidden="true">&#8595;</span></a><Link className="season-text-link" to="/polls/abootnothing">Find a matchup &#8599;</Link></div></div>
    <div className="season-path" aria-hidden="true"><div className="season-path__caption"><span>THE ROAD TO THE FINAL</span><span>ABOOT / 01</span></div><svg viewBox="0 0 560 400" fill="none"><defs><linearGradient id="season-gold" x1="0" y1="0" x2="560" y2="400" gradientUnits="userSpaceOnUse"><stop stopColor="#fff1ad"/><stop offset="1" stopColor="#d4a700"/></linearGradient></defs><circle cx="370" cy="210" r="155" stroke="#f3c928" strokeOpacity=".12"/><circle cx="370" cy="210" r="115" stroke="#f3c928" strokeOpacity=".08"/><g className="season-path__traces" stroke="url(#season-gold)" strokeWidth="2"><path d="M120 70H155V130H200M120 190H155V130M120 280H155V330H200M120 380H155V330M290 130H325V225H370M290 330H325V225"/></g>{[45,165,255,355].map((y,i)=><g key={y}><rect x="12" y={y} width="108" height="48" rx="8" fill="#17160e" stroke="#796824"/><text x="30" y={y+30} fill="#d0c9ac" fontSize="9" fontFamily="monospace">{['THE RIVAL','THE FAVORITE','THE WILDCARD','THE UNDERDOG'][i]}</text></g>)}{[105,305].map(y=><g key={y}><rect x="200" y={y} width="90" height="50" rx="8" fill="#282310" stroke="#d2b03a"/><path d={`M225 ${y+26}l8 8 17-19`} stroke="#f3c928" strokeWidth="3"/></g>)}<g className="season-path__trophy"><rect x="370" y="151" width="152" height="152" rx="18" fill="#24200e" stroke="url(#season-gold)" strokeWidth="2"/><path d="M427 186h38v25c0 25-38 25-38 0v-25Zm0 5h-12v14c0 11 9 16 16 16m34-30h12v14c0 11-9 16-16 16m-15 9v21m-17 0h34" stroke="url(#season-gold)" strokeWidth="3" strokeLinecap="round"/><text x="446" y="280" textAnchor="middle" fill="#fff1ad" fontSize="13" letterSpacing="2" fontFamily="monospace">CHAMPION</text></g></svg><div className="season-path__footer"><span>EVERY CONTENDER COUNTS.</span><b>ONLY ONE TAKES IT.</b></div></div></div>
    <div className="season-hero__rail"><span><b>01</b> MEET THE CONTENDERS</span><span><b>02</b> FOLLOW THE ROUNDS</span><span><b>03</b> WITNESS THE WINNER</span></div>
  </header>;
}
export function Roadmaps() {
  const [loading, setLoading] = useState(true), [search, setSearch] = useState('');
  const { slug } = useParams(), [items, setItems] = useState<Item[]>([]), [bracket, setBracket] = useState<Bracket | null>(null), [selected, setSelected] = useState<Match | null>(null), [error, setError] = useState('');
  const load = useCallback(async () => { try { if (slug) { const p = await read<{ bracket: Bracket }>(`/${encodeURIComponent(slug)}`); setBracket(p.bracket); } else setItems((await read<{ items: Item[] }>('')).items); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Roadmap unavailable.'); setBracket(null); setItems([]); } finally { setLoading(false); } }, [slug]);
  useEffect(() => { void load(); const tick = setInterval(() => { if (!document.hidden) void load(); }, 15000); const visible = () => { if (!document.hidden) void load(); }; document.addEventListener('visibilitychange', visible); return () => { clearInterval(tick); document.removeEventListener('visibilitychange', visible); }; }, [load]);
  const graph = bracket?.graph, final = graph?.matches.find(m => m.round === Math.log2(graph.size) - 1), winner = bracket?.finalized ? bracket.decisions.find(d => d.matchId === final?.id)?.winnerId : null, champion = graph?.contenders.find(c => c.id === winner);
  const match = graph?.matches.find(m => m.id === selected?.id);
  if (!slug) {
    const filtered = items.filter(item => `${item.title} ${item.season}`.toLowerCase().includes(search.toLowerCase()));
    return <main className="season-landing"><SeasonHero /><section className="container season-directory" id="season-directory"><header className="season-directory__heading"><div><p className="eyebrow">THE MATCHUP COLLECTION</p><h2>Pick your season.</h2><p>Every rivalry has a beginning. Follow it all the way.</p></div>{items.length ? <label className="season-search">Find a season<input type="search" placeholder="Search seasons..." value={search} onChange={e => setSearch(e.target.value)} /></label> : null}</header>
      {error ? <div className="season-empty" role="status"><span className="season-empty__mark" aria-hidden="true">!</span><div><p className="eyebrow">WE COULDN'T LOAD THE SEASONS</p><h3>Let's try that again.</h3><p>{error}</p><button className="button button--primary" onClick={() => void load()}>Retry</button></div></div> : loading ? <div className="season-empty" role="status"><p>Loading the season collection...</p></div> : items.length ? <><p className="season-count">{filtered.length} {filtered.length === 1 ? 'season' : 'seasons'} to explore</p><div className="season-grid">{filtered.map(item => <RoadmapCard key={item.id} item={item} />)}</div>{!filtered.length ? <div className="season-empty"><div><h3>No matching seasons.</h3><p>Try another title or explore the full collection.</p><button className="button" onClick={() => setSearch('')}>Clear search</button></div></div> : null}</> : <div className="season-empty"><span className="season-empty__mark" aria-hidden="true">VS</span><div><p className="eyebrow">THE NEXT CHAPTER IS ON ITS WAY</p><h3>The rivalries start here.</h3><p>No seasons have been published yet. In the meantime, head into Aboot Nothing and find your next matchup.</p><Link className="button button--primary" to="/polls/abootnothing">Explore Aboot Nothing <span aria-hidden="true">&#8599;</span></Link></div></div>}
      <aside className="season-bottom"><div><p className="eyebrow">GOT A SIDE? MAKE IT COUNT.</p><h2>The bracket tells the story.<br />The audience has its say.</h2></div><Link className="button" to="/polls">Explore all Polls &#8599;</Link></aside>
    </section></main>;
  }
  return <main className="roadmap-page"><Link to={slug ? ROOT : '/polls/abootnothing'}>← {slug ? 'All Season Roadmaps' : 'Aboot Nothing'}</Link>{error ? <section className="bracket-panel" role="status"><h1>Roadmap unavailable</h1><p>{error}</p><p>Only intentionally published seasons can be viewed here.</p></section> : graph && bracket ? <><header className="roadmap-hero">{graph.presentation.cover ? <img src={`/api/brackets/media/${graph.presentation.cover}`} alt="" /> : null}<span className="bracket-eyebrow">{graph.presentation.season || 'Aboot Nothing · Season Roadmap'}</span><h1>{graph.presentation.title}</h1><p>{graph.presentation.intro}</p></header>{graph.presentation.description ? <p>{graph.presentation.description}</p> : null}{bracket.needsReview.length ? <div className="bracket-alert">A result is under review. Later-round participants have been preserved pending an explicit correction.</div> : null}{champion ? <section className="roadmap-champion"><span className="bracket-eyebrow">Confirmed season champion</span><h2>{champion.name}</h2><p>The required rounds are complete.</p></section> : null}<BracketCanvas bracket={bracket} selected={selected?.id} onSelect={setSelected} /><p>Scores marked manual or historical are separately recorded bracket results. Voting takes place in the linked Poll.</p></> : <p role="status">Loading Season Roadmap…</p>}
    {match && graph && bracket && selected ? <Lightbox title={`Round ${match.round + 1} · Match ${match.position + 1}`} onClose={() => setSelected(null)}><MatchDetail bracket={bracket} match={match} onClose={() => setSelected(null)} /></Lightbox> : null}
  </main>;
}
