import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { BracketCanvas } from './BracketCanvas';
import { statusLabel } from './status';
import { Lightbox } from './Lightbox';
import { opponents, type Match, type Presentation } from './model.mjs';
import type { Bracket } from './types';
const ROOT = '/polls/abootnothing/brackets';
type Item = Presentation & { id: string };
async function read<T>(path: string): Promise<T> { const r = await fetch(`/api/brackets${path}`, { cache: 'no-store' }); const p = await r.json(); if (!r.ok || !p.ok) throw new Error(p.message || 'This roadmap is unavailable.'); return p; }
export function RoadmapShelf() {
  const [items, setItems] = useState<Item[]>([]);
  useEffect(() => { void read<{ items: Item[] }>('').then(p => setItems(p.items)).catch(() => {}); }, []);
  return <section className="container roadmap-page"><p className="bracket-eyebrow">The season ahead</p><h2>Season Roadmaps</h2><p>Follow the matchups from opening round to the final decision.</p><Link to={ROOT}>Explore Roadmaps &amp; Seasons →</Link>{items.length ? <div className="bracket-library">{items.slice(0,3).map(p => <RoadmapCard key={p.id} item={p} />)}</div> : null}</section>;
}
function RoadmapCard({ item }: { item: Item }) { return <article className="bracket-library-card">{item.feature ? <img className="bracket-upload-preview" src={`/api/brackets/media/${item.feature}`} alt="" /> : null}<p className="bracket-eyebrow">{item.season || 'Season Roadmap'}</p><h2><Link to={`${ROOT}/${item.slug}`}>{item.title}</Link></h2><p>{item.intro}</p></article>; }
export function Roadmaps() {
  const { slug } = useParams(), [items, setItems] = useState<Item[]>([]), [bracket, setBracket] = useState<Bracket | null>(null), [selected, setSelected] = useState<Match | null>(null), [error, setError] = useState('');
  const load = useCallback(async () => { try { if (slug) { const p = await read<{ bracket: Bracket }>(`/${encodeURIComponent(slug)}`); setBracket(p.bracket); } else setItems((await read<{ items: Item[] }>('')).items); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Roadmap unavailable.'); setBracket(null); setItems([]); } }, [slug]);
  useEffect(() => { void load(); const tick = setInterval(() => { if (!document.hidden) void load(); }, 15000); const visible = () => { if (!document.hidden) void load(); }; document.addEventListener('visibilitychange', visible); return () => { clearInterval(tick); document.removeEventListener('visibilitychange', visible); }; }, [load]);
  const graph = bracket?.graph, final = graph?.matches.find(m => m.round === Math.log2(graph.size) - 1), winner = bracket?.finalized ? bracket.decisions.find(d => d.matchId === final?.id)?.winnerId : null, champion = graph?.contenders.find(c => c.id === winner);
  const match = graph?.matches.find(m => m.id === selected?.id), pair = graph && match ? opponents(graph, match, bracket?.decisions) : [], result = bracket?.decisions.find(d => d.matchId === match?.id), source = bracket?.sources[match?.id || ''];
  return <main className="roadmap-page"><Link to={slug ? ROOT : '/polls/abootnothing'}>← {slug ? 'All Season Roadmaps' : 'Aboot Nothing'}</Link>{error ? <section className="bracket-panel" role="status"><h1>Roadmap unavailable</h1><p>{error}</p><p>Only intentionally published seasons can be viewed here.</p></section> : !slug ? <><header className="roadmap-hero"><span className="bracket-eyebrow">Aboot Nothing</span><h1>Every matchup.<br />The whole season.</h1><p>Season Roadmaps trace each contender’s journey. Explore the upcoming rounds and follow confirmed results.</p></header><div className="bracket-library">{items.map(item => <RoadmapCard key={item.id} item={item} />)}</div>{!items.length ? <p>No Season Roadmaps are published yet. New matchups are still available in <Link to="/polls/abootnothing">Aboot Nothing</Link>.</p> : null}</> : graph && bracket ? <><header className="roadmap-hero">{graph.presentation.cover ? <img src={`/api/brackets/media/${graph.presentation.cover}`} alt="" /> : null}<span className="bracket-eyebrow">{graph.presentation.season || 'Aboot Nothing · Season Roadmap'}</span><h1>{graph.presentation.title}</h1><p>{graph.presentation.intro}</p></header>{graph.presentation.description ? <p>{graph.presentation.description}</p> : null}{bracket.needsReview.length ? <div className="bracket-alert">A result is under review. Later-round participants have been preserved pending an explicit correction.</div> : null}{champion ? <section className="roadmap-champion"><span className="bracket-eyebrow">Confirmed season champion</span><h2>{champion.name}</h2><p>The required rounds are complete.</p></section> : null}<BracketCanvas bracket={bracket} selected={selected?.id} onSelect={setSelected} /><p>Scores marked manual or historical are separately recorded bracket results. Voting takes place in the linked Poll.</p></> : <p role="status">Loading Season Roadmap…</p>}
    {match && graph && bracket && selected ? <Lightbox title={`Round ${match.round + 1} · Match ${match.position + 1}`} onClose={() => setSelected(null)}><div className="bracket-public-detail"><h2>{pair.map(c => c?.name || 'Awaiting opponent').join(' vs ')}</h2><p>{match.description}</p><div className="pair">{pair.map((c,i) => <section key={i}>{c?.image ? <img src={`/api/brackets/media/${c.image}`} alt={`${c.name} artwork`} /> : null}<h3>{c?.name || 'Unresolved upstream winner'}</h3><p>{c?.description}</p><p>Score: {source?.scores && c ? source.scores[c.id] ?? 'Unknown' : result?.scores[i] ?? 'Unknown'}</p>{result?.winnerId === c?.id && !bracket.needsReview.includes(match.id) ? <strong>WINNER · {result?.source === 'poll' ? 'Confirmed Poll result' : result?.source === 'bye' ? 'Explicit bye' : 'Manual bracket result'}</strong> : null}</section>)}</div><p>{source ? statusLabel(source.state) : result ? `${result.source} result` : 'Upcoming matchup'}</p>{source?.slug ? <Link to={`/polls/${source.slug}`}>Open Poll →</Link> : null}</div></Lightbox> : null}
  </main>;
}
