import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4186";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const ARTIFACTS = fileURLToPath(new URL("../.artifacts/polls-v11/", import.meta.url));
const PNG = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");

test("Public Poll gallery, modal, detail, vote, editor, popout, and responsive states", async (t) => {
  await mkdir(ARTIFACTS, { recursive: true });
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4186"], { stdio: "ignore" });
  t.after(() => server.kill()); await wait();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  for (const viewport of [{ width: 1920, height: 1080 }, { width: 1440, height: 900 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) {
    const context = await browser.newContext({ viewport }); await consent(context); const page = await context.newPage(); const errors = [];
    page.on("console", (entry) => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("pageerror", (error) => errors.push(error.message)); await page.route("**/api/**", respond);
    await page.goto(`${ORIGIN}/polls`, { waitUntil: "networkidle" }); await page.getByRole("heading", { level: 1, name: /READ THE/ }).waitFor(); await page.getByText("Open audience choice").waitFor();
    await page.screenshot({ path: `${ARTIFACTS}/gallery-${viewport.width}.png`, fullPage: true }); assert.equal(await fits(page), true);
    if (viewport.width === 1440) { await page.getByRole("button", { name: "Quick view", exact: true }).first().click(); await page.getByRole("dialog").waitFor(); assert.equal(await page.evaluate(() => document.activeElement?.getAttribute("aria-label")), "Close Poll quick view"); await page.screenshot({ path: `${ARTIFACTS}/quick-view-modal.png` }); await page.getByRole("button", { name: "Close Poll quick view" }).click(); }
    await page.goto(`${ORIGIN}/polls/open-audience-choice`, { waitUntil: "networkidle" }); await page.getByRole("heading", { level: 1, name: "Open audience choice" }).waitFor(); await page.screenshot({ path: `${ARTIFACTS}/detail-before-${viewport.width}.png`, fullPage: true });
    if (viewport.width === 1440) { await page.getByRole("button", { name: "Vote", exact: true }).first().click(); await page.getByText("Vote recorded.").waitFor(); await page.screenshot({ path: `${ARTIFACTS}/detail-after-vote.png`, fullPage: true }); }
    if (viewport.width === 1920) { const close = page.getByRole("button", { name: "Close Poll", exact: true }); assert.equal(await close.count(), 1); await page.screenshot({ path: `${ARTIFACTS}/detail-owner-close-enabled.png`, fullPage: true }); let confirmationMessage = ""; page.once("dialog", async (dialog) => { confirmationMessage = dialog.message(); await dialog.accept(); }); await close.click(); assert.match(confirmationMessage, /settle its final results.*New votes will be rejected/i); await page.getByText("Poll closed. Final results are now settled.").waitFor(); await page.screenshot({ path: `${ARTIFACTS}/detail-owner-closed.png`, fullPage: true }); }
    if (viewport.width === 390) { await page.goto(`${ORIGIN}/polls/new`, { waitUntil: "networkidle" }); await page.getByRole("heading", { level: 1, name: "Build a live Poll" }).waitFor(); await page.getByRole("textbox", { name: "Chat trigger" }).nth(1).fill("CARROT"); await page.getByPlaceholder("Type the complete message").fill("  carrot  "); await page.getByText("Matches Option two").waitFor(); await page.screenshot({ path: `${ARTIFACTS}/editor-mobile-custom-trigger.png`, fullPage: true }); assert.equal(await fits(page), true); }
    assert.deepEqual(errors, []); await context.close();
  }
  const context = await browser.newContext({ viewport: { width: 1920, height: 1080 } }); await consent(context); const page = await context.newPage(); await page.route("**/api/**", respond);
  await page.goto(`${ORIGIN}/polls/new`, { waitUntil: "networkidle" }); await page.getByRole("heading", { name: "Build a live Poll" }).waitFor(); await page.getByRole("checkbox", { name: /Enable exact-chat voting/ }).check(); await page.getByLabel("Rumble source").waitFor(); assert.equal(await page.getByLabel("Rumble source").inputValue(), "user:1sl8zm"); assert.equal(await page.getByRole("button", { name: /Move Option two up/ }).isEnabled(), true); assert.equal(await page.getByRole("button", { name: /Move Option one up/ }).isDisabled(), true); await page.screenshot({ path: `${ARTIFACTS}/editor-auto-source-one-live-1920.png`, fullPage: true }); await page.getByRole("button", { name: "Advanced / Custom source" }).click(); await page.screenshot({ path: `${ARTIFACTS}/editor-advanced-source.png`, fullPage: true }); await page.getByRole("button", { name: "Use detected source" }).click(); await page.getByLabel("Poll cover").setInputFiles({ name: "cover.png", mimeType: "image/png", buffer: PNG }); await page.getByLabel("1:1 image").first().setInputFiles({ name: "option.png", mimeType: "image/png", buffer: PNG }); await page.getByRole("button", { name: "Violet" }).click(); await page.screenshot({ path: `${ARTIFACTS}/editor-banner-tint-option-image.png`, fullPage: true }); await page.getByRole("textbox", { name: "Chat trigger" }).nth(1).fill("CARROT"); await page.getByPlaceholder("Type the complete message").fill("carrot!"); await page.getByText("No match").waitFor();
  createFailure = true; await page.getByRole("textbox", { name: "Title", exact: true }).fill("Overlay acceptance"); await page.getByRole("button", { name: "Save draft" }).click(); const alert = page.locator(".ephemeral-notice--error"); await alert.waitFor(); assert.equal(await alert.getByText("Poll could not be updated").count(), 1); const overlay = await page.evaluate(() => { const region = document.querySelector(".ephemeral-notice-region"); const card = document.querySelector(".ephemeral-notice--error"); const header = document.querySelector(".site-header")?.getBoundingClientRect(); const box = card?.getBoundingClientRect(); return region && card && box ? { portalled: region.parentElement === document.body, position: getComputedStyle(region).position, zIndex: Number(getComputedStyle(region).zIndex), backgroundColor: getComputedStyle(card).backgroundColor, headerBottom: header?.bottom || 0, top: box.top, right: box.right, width: box.width } : null; }); assert.ok(overlay && overlay.portalled && overlay.position === "fixed", JSON.stringify(overlay)); assert.equal(overlay.backgroundColor, "rgb(18, 11, 12)", JSON.stringify(overlay)); assert.ok(overlay.zIndex > 90 && overlay.top >= overlay.headerBottom && overlay.right <= 1920 && overlay.width <= 430, JSON.stringify(overlay)); await page.screenshot({ path: `${ARTIFACTS}/editor-error-overlay-1920.png`, fullPage: false }); await alert.getByRole("button", { name: "Dismiss notification" }).click(); await alert.waitFor({ state: "detached" }); createFailure = false;
  discoveryMode = "multiple"; await page.reload({ waitUntil: "networkidle" }); await page.getByRole("checkbox", { name: /Enable exact-chat voting/ }).check(); await page.getByText("Multiple live streams detected — choose one below.").waitFor(); await page.getByText("Choose a detected stream").click(); await page.screenshot({ path: `${ARTIFACTS}/editor-multiple-streams.png`, fullPage: true });
  discoveryMode = "offline"; await page.reload({ waitUntil: "networkidle" }); await page.getByRole("checkbox", { name: /Enable exact-chat voting/ }).check(); await page.getByText("Rumble source discovery temporarily unavailable.").waitFor(); await page.screenshot({ path: `${ARTIFACTS}/editor-discovery-offline.png`, fullPage: true }); discoveryMode = "one";
  await page.goto(`${ORIGIN}/polls/signed-in-only`, { waitUntil: "networkidle" }); assert.equal(await page.getByRole("button", { name: "Close Poll", exact: true }).count(), 0); await page.screenshot({ path: `${ARTIFACTS}/signed-in-only-state.png`, fullPage: true });
  await page.goto(`${ORIGIN}/polls/open-audience-choice/popout`, { waitUntil: "networkidle" }); await page.getByRole("heading", { name: "Open audience choice" }).waitFor(); await page.screenshot({ path: `${ARTIFACTS}/popout.png`, fullPage: true }); assert.equal(await page.locator(".site-header").count(), 0); await context.close();
});

let voted = false; let discoveryMode = "one"; let createFailure = false;
async function respond(route) { const url = new URL(route.request().url()); const method = route.request().method();
  if (url.pathname === "/api/auth/config") return json(route, { configured: true, emailSignupConfigured: false, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: ORIGIN, adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" });
  if (url.pathname === "/api/auth/session") return json(route, session());
  if (url.pathname === "/api/polls/access") return json(route, { ok: true, authenticated: true, canCreate: true, canManageAll: false });
  if (url.pathname === "/api/polls/discovery") return json(route, discovery());
  if (url.pathname === "/api/polls" && method === "POST" && createFailure) return json(route, { ok: false, error: "service_schema_mismatch", message: "The service database schema is not compatible with this deployment." }, 503);
  if (url.pathname === "/api/polls" && method === "GET") return json(route, { ok: true, items: [poll("open"), signedPoll(), poll("closed")], count: 3, refreshedAt: new Date().toISOString() });
  if (url.pathname.endsWith("/vote")) { voted = true; return json(route, { ok: true, poll: poll("open"), vote: { optionId: "opt_carrot", repeated: false, changed: false }, refreshedAt: new Date().toISOString() }); }
  if (url.pathname.endsWith("/lifecycle")) return json(route, { ok: true, poll: poll("closed"), access: { canManage: true, canManageAll: false, isOwner: true } });
  if (url.pathname === "/api/polls/open-audience-choice") return json(route, { ok: true, poll: poll("open"), access: { canManage: true, canManageAll: false, isOwner: true }, refreshedAt: new Date().toISOString() });
  if (url.pathname === "/api/polls/closed-audience-result") return json(route, { ok: true, poll: poll("closed"), access: { canManage: false, canManageAll: false, isOwner: false }, refreshedAt: new Date().toISOString() });
  if (url.pathname === "/api/polls/signed-in-only") return json(route, { ok: true, poll: signedPoll(), access: { canManage: false, canManageAll: false, isOwner: false }, refreshedAt: new Date().toISOString() });
  return json(route, { ok: true }); }
function poll(state) { const open = state === "open"; const banner = `data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 500"><rect width="1200" height="500" fill="#16130a"/><path d="M680 0 420 310h190l-70 190 330-360H670z" fill="#f3c928" opacity=".7"/></svg>')}`; const image = `data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><rect width="200" height="200" fill="#8f6cff"/><circle cx="100" cy="100" r="58" fill="#fff" opacity=".7"/></svg>')}`; return { id: `pol_${state}1234`, slug: open ? "open-audience-choice" : "closed-audience-result", title: open ? "Open audience choice" : "Closed audience result", description: "Choose the complete signal that should lead the next segment.", state, public: true, webVotingMode: "anyone", rumbleEnabled: true, rumbleSourceScope: "user:1sl8zm", livestreamMode: "automatic", livestreamId: null, revision: 3, totalVotes: voted ? 14 : 13, currentVoteOptionId: voted ? "opt_carrot" : null, options: [{ id: "opt_one1234", position: 0, label: "Option one", description: "First response", trigger: "1", normalizedTrigger: "1", votes: 5, image: { id: "asset-one", purpose: "option", optionId: "opt_one1234", url: image, contentType: "image/svg+xml", byteSize: 1, width: 200, height: 200, createdAt: new Date().toISOString() } }, { id: "opt_carrot", position: 1, label: "Option two", description: "Custom response", trigger: "CARROT", normalizedTrigger: "carrot", votes: voted ? 9 : 8, image: null }], owner: { id: "creator", displayName: "Approved Creator", avatarUrl: null }, theme: { accent: open ? "#f3c928" : "#8f6cff", layout: "bars" }, media: { banner: open ? { id: "asset-banner", purpose: "banner", url: banner, contentType: "image/svg+xml", byteSize: 1, width: 1200, height: 500, createdAt: new Date().toISOString() } : null }, updatedAt: new Date().toISOString(), openedAt: "2026-08-31T00:00:00Z", closedAt: open ? null : "2026-08-31T01:00:00Z" }; }
function discovery() { const base = { ok: true, provider: "rumble", freshness: { heartbeatAt: new Date().toISOString(), ageSeconds: 4, providerResponseAt: "2026-08-31T21:48:24Z", observedAt: new Date().toISOString() }, source: { scope: "user:1sl8zm", type: "user", id: "1sl8zm", displayName: "ThirdRailify" }, message: null }; if (discoveryMode === "offline") return { ...base, botState: "offline", source: null, livestreams: [], message: "Rumble source discovery temporarily unavailable." }; const streams = [{ id: "7cpera", title: "Third Railify Live Show", isLive: true, createdOn: new Date(Date.now() - 12 * 60_000).toISOString(), scheduledOn: null, visibility: "public", watchingNow: 42 }]; if (discoveryMode === "multiple") streams.push({ ...streams[0], id: "7cperb", title: "Third Railify Backstage" }); return { ...base, botState: "healthy", livestreams: streams }; }
function signedPoll() { return { ...poll("open"), id: "pol_signed123", slug: "signed-in-only", title: "Signed-in only", webVotingMode: "signed_in", totalVotes: 0, currentVoteOptionId: null }; }
function session() { return { ok: true, authenticated: true, csrfToken: "poll-browser-csrf", access: { isAdmin: false, isMasterAdmin: false }, account: { id: "creator", email: "creator@example.test", displayName: "Approved Creator", avatarUrl: null, providers: ["email"], role: "user", adminLevel: "none", status: "active", emailVerified: true, createdAt: "2026-08-31T00:00:00Z", source: "test" } }; }
async function consent(context) { const now = Date.now(); await context.addCookies([{ name: "thirdrailify_consent", value: encodeURIComponent(JSON.stringify({ version: 1, timestamp: new Date(now).toISOString(), expiry: new Date(now + 86400000).toISOString(), categories: { preferences: false, externalMedia: false } })), domain: "127.0.0.1", path: "/", expires: Math.floor((now + 86400000) / 1000), httpOnly: false, secure: false, sameSite: "Lax" }]); }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function fits(page) { return page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth); }
async function wait() { for (let index = 0; index < 80; index += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Public preview did not start"); }
