import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { chromium } from "playwright-core";
import { WHEEL_GEOMETRY } from "../src/wheels/wheelRenderPlan.mjs";

const ORIGIN = process.env.WHEELS_DEPLOY_ORIGIN || "http://127.0.0.1:4197";
const LOCAL = !process.env.WHEELS_DEPLOY_ORIGIN;
const FIXTURE = LOCAL || process.env.WHEELS_V19_FIXTURE === "1";
const SLUG = process.env.WHEELS_V19_SLUG || "v19-render-stability";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const ARTIFACTS = process.env.WHEELS_V19_ARTIFACTS || join(tmpdir(), "thirdrailify-wheels-v19-browser");
const GIF = twoFrameGif();
const GIF_ID = "11111111-1111-4111-8111-111111111111";
const STATIC_ID = "22222222-2222-4222-8222-222222222222";
const WHEEL_FACE_TO_OUTER_RATIO = WHEEL_GEOMETRY.faceToOuterRatio;

test("Wheels V1.9 keeps its local face rigid through GIF-backed spins, repeats, hit testing, and responsive surfaces", async (t) => {
  await mkdir(ARTIFACTS, { recursive: true });
  let server; if (LOCAL) { server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4197"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForPreview(); }
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1, reducedMotion: "no-preference" }); await consent(context); const page = await context.newPage(); const evidence = monitor(page); if (FIXTURE) await routes(page);
  await page.goto(`${ORIGIN}/wheels/${SLUG}`, { waitUntil: "networkidle" }); const canvas = page.locator(".wheel-stage canvas").first(); await canvas.waitFor({ timeout: 10_000 }).catch(async () => { throw new Error(`wheel fixture did not render: ${JSON.stringify({ body: await page.locator("body").innerText(), errors: evidence.errors })}`); }); await ready(canvas);
  const idle = await sample(canvas, "idle"); const frames = [idle]; await page.locator(".wheel-stage").first().screenshot({ path: join(ARTIFACTS, "local-fixed-idle.png") });
  const baselineStatic = staticCounts(idle.metrics); const frameA = await fingerprint(canvas);
  await page.getByRole("button", { name: "Start demo spin" }).click();
  let elapsed = 0; for (const [name, at] of [["early", 350], ["quarter", 900], ["mid", 1750], ["late", 2750], ["near-settle", 3250]]) { await page.waitForTimeout(at - elapsed); elapsed = at; const next = await sample(canvas, name); frames.push(next); await page.locator(".wheel-stage").first().screenshot({ path: join(ARTIFACTS, `local-fixed-${name}.png`) }); }
  let frameB = frameA; for (let attempt = 0; attempt < 14 && frameB === frameA; attempt += 1) { await page.waitForTimeout(90); frameB = await fingerprint(canvas); } assert.notEqual(frameA, frameB, "GIF content changes while the rigid face spins");
  const result = page.getByRole("dialog"); await result.waitFor({ timeout: 10_000 }).catch(async () => { throw new Error(`spin did not settle: ${JSON.stringify({ body: await page.locator("body").innerText(), stage: await page.locator(".wheel-stage").first().evaluate((node) => ({ className: node.className, rotorStyle: node.querySelector(".wheel-stage__rotor").getAttribute("style"), rotorTransform: getComputedStyle(node.querySelector(".wheel-stage__rotor")).transform, debug: node.querySelector("canvas").__wheelRendererV19 })) })}`); }); const winner = (await result.getByRole("heading", { level: 2 }).innerText()).trim(); const hudWinner = (await page.locator(".pointer-target-hud strong").innerText()).trim(); assert.match(winner, new RegExp(escapeRegExp(hudWinner), "i")); await page.screenshot({ path: join(ARTIFACTS, "local-fixed-settled.png") });
  const settled = await sample(canvas, "settled"); frames.push(settled); for (const frame of frames) { assert.equal(frame.canvas.width, idle.canvas.width, `${frame.name} backing width`); assert.equal(frame.canvas.height, idle.canvas.height, `${frame.name} backing height`); assert.ok(Math.abs(frame.frame.width - frame.frame.height) <= .02, JSON.stringify(frame.frame)); assert.ok(Math.abs(frame.rotor.width - frame.rotor.height) <= .02, JSON.stringify(frame.rotor)); assert.ok(Math.abs(frame.canvas.cssWidth - frame.canvas.cssHeight) <= .02, JSON.stringify(frame.canvas)); assert.ok(Math.abs(frame.geometry.faceToOuterRatio - idle.geometry.faceToOuterRatio) <= .0001, JSON.stringify(frame.geometry)); assert.equal(frame.metrics.size, idle.metrics.size); assert.equal(frame.metrics.dpr, idle.metrics.dpr); assert.equal(frame.metrics.pixels, idle.metrics.pixels); assert.deepEqual(localMetrics(frame.metrics.plan), localMetrics(idle.metrics.plan)); assert.ok(Math.abs(frame.transformScale.x - 1) < .00001 && Math.abs(frame.transformScale.y - 1) < .00001, JSON.stringify(frame.transformScale)); }
  assert.deepEqual(staticCounts(settled.metrics), baselineStatic, "spin and GIF ticks perform no static face work"); assert.ok(settled.metrics.gifFramesDecoded > idle.metrics.gifFramesDecoded); assert.ok(settled.metrics.gifFramesDecoded - idle.metrics.gifFramesDecoded <= 55, JSON.stringify({ idle: idle.metrics.gifFramesDecoded, settled: settled.metrics.gifFramesDecoded }));
  await result.getByRole("button", { name: "Close result" }).click(); const stageBox = await page.locator(".wheel-stage").first().boundingBox(); assert.ok(stageBox); await page.mouse.click(stageBox.x + stageBox.width / 2, stageBox.y + stageBox.height * .14); const details = page.getByRole("dialog"); await details.waitFor(); assert.match(await details.innerText(), new RegExp(escapeRegExp(hudWinner), "i")); await page.getByRole("button", { name: "Close participant details" }).click();
  for (let repeat = 1; repeat <= 2; repeat += 1) { await page.getByRole("button", { name: "Start demo spin" }).click(); const dialog = page.getByRole("dialog"); await dialog.waitFor({ timeout: 5_000 }); await dialog.getByRole("button", { name: "Close result" }).click(); const repeated = await sample(canvas, `repeat-${repeat}`); assert.deepEqual(staticCounts(repeated.metrics), baselineStatic); assert.equal(repeated.canvas.width, idle.canvas.width); }
  assert.deepEqual(evidence.writes, []); assert.deepEqual(evidence.errors, []);

  const matrix = [];
  for (const surface of [
    ...[{ width: 1920, height: 1080 }, { width: 1440, height: 900 }, { width: 1365, height: 768 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 473, height: 1024 }, { width: 430, height: 932 }, { width: 412, height: 915 }, { width: 390, height: 844 }, { width: 844, height: 390 }].map((viewport) => ({ route: "detail", viewport })),
    ...[{ width: 1920, height: 1080 }, { width: 2048, height: 1152 }, { width: 2560, height: 1080 }, { width: 3440, height: 1440 }, { width: 1280, height: 720 }, { width: 473, height: 1024 }, { width: 430, height: 932 }, { width: 390, height: 844 }, { width: 844, height: 390 }].map((viewport) => ({ route: "present", viewport })),
  ]) {
    const candidateContext = await browser.newContext({ viewport: surface.viewport, deviceScaleFactor: surface.viewport.width === 1280 ? 2 : 1, reducedMotion: "no-preference" }); await consent(candidateContext); const candidate = await candidateContext.newPage(); const candidateEvidence = monitor(candidate); if (FIXTURE) await routes(candidate); await candidate.goto(`${ORIGIN}/wheels/${SLUG}${surface.route === "present" ? "/present" : ""}`, { waitUntil: "networkidle" }); const candidateCanvas = candidate.locator(".wheel-stage canvas").first(); await candidateCanvas.waitFor(); await ready(candidateCanvas); const before = await sample(candidateCanvas, "before"); await candidate.screenshot({ path: join(ARTIFACTS, `${surface.route}-${surface.viewport.width}x${surface.viewport.height}-idle.png`) }); await candidate.getByRole("button", { name: "Start demo spin" }).click(); await candidate.waitForTimeout(850); const during = await sample(candidateCanvas, "during"); const fit = await candidate.evaluate(() => { const stage = document.querySelector(".wheel-stage").getBoundingClientRect(); const pointer = document.querySelector(".wheel-stage__pointer").getBoundingClientRect(); return { overflow: document.documentElement.scrollWidth - document.documentElement.clientWidth, circular: Math.abs(stage.width - stage.height), pointerAligned: Math.abs(pointer.left + pointer.width / 2 - (stage.left + stage.width / 2)) }; }); assert.ok(fit.overflow <= 1 && fit.circular <= 1 && fit.pointerAligned <= 1, JSON.stringify({ surface, fit })); assert.deepEqual(staticCounts(during.metrics), staticCounts(before.metrics)); assert.deepEqual(localMetrics(during.metrics.plan), localMetrics(before.metrics.plan)); assert.equal(during.canvas.width, before.canvas.width); assert.equal(before.canvas.width, before.canvas.height); assert.equal(during.canvas.width, during.canvas.height); assert.ok(Math.abs(before.frame.width - before.frame.height) <= .02 && Math.abs(during.frame.width - during.frame.height) <= .02, JSON.stringify({ surface, before: before.frame, during: during.frame })); assert.ok(Math.abs(before.rotor.width - before.rotor.height) <= .02 && Math.abs(during.rotor.width - during.rotor.height) <= .02, JSON.stringify({ surface, before: before.rotor, during: during.rotor })); assert.ok(Math.abs(before.geometry.faceToOuterRatio - WHEEL_FACE_TO_OUTER_RATIO) <= .005 && Math.abs(during.geometry.faceToOuterRatio - WHEEL_FACE_TO_OUTER_RATIO) <= .005, JSON.stringify({ surface, before: before.geometry, during: during.geometry })); assert.deepEqual(candidateEvidence.writes, []); assert.deepEqual(candidateEvidence.errors, []); matrix.push({ ...surface, fit, before: compact(before), during: compact(during) }); await candidate.screenshot({ path: join(ARTIFACTS, `${surface.route}-${surface.viewport.width}x${surface.viewport.height}-mid-spin.png`) }); await candidateContext.close();
  }

  const v113 = { zoom: [], dpr: [], repeatedResize: [], fullscreen: [] };
  const zoomContext = await browser.newContext({ viewport: { width: 2048, height: 1152 }, deviceScaleFactor: 1, reducedMotion: "no-preference" }); await consent(zoomContext); const zoomPage = await zoomContext.newPage(); const zoomEvidence = monitor(zoomPage); if (FIXTURE) await routes(zoomPage); await zoomPage.goto(`${ORIGIN}/wheels/${SLUG}/present`, { waitUntil: "networkidle" }); const zoomCanvas = zoomPage.locator(".wheel-stage canvas").first(); await zoomCanvas.waitFor(); await ready(zoomCanvas);
  for (const zoom of [.67, .8, .9, 1, 1.1, 1.25, 1.5, 1.75, 2]) { const viewport = { width: Math.round(2048 / zoom), height: Math.round(1152 / zoom) }; await zoomPage.setViewportSize(viewport); await zoomPage.waitForTimeout(200); const measured = await sample(zoomCanvas, `zoom-${zoom}`); assertCanonicalFrame(measured, `zoom ${zoom}`); v113.zoom.push({ mode: "equivalent-layout-viewport", value: zoom, viewport, sample: compact(measured) }); if (zoom === .67 || zoom === 2) await zoomPage.screenshot({ path: join(ARTIFACTS, `presentation-zoom-${Math.round(zoom * 100)}.png`) }); }
  assert.deepEqual(zoomEvidence.writes, []); assert.deepEqual(zoomEvidence.errors, []); await zoomContext.close();
  for (const dpr of [1, 1.25, 1.5, 2, 3]) {
    const dprContext = await browser.newContext({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: dpr, reducedMotion: "no-preference" }); await consent(dprContext); const dprPage = await dprContext.newPage(); const dprEvidence = monitor(dprPage); if (FIXTURE) await routes(dprPage); await dprPage.goto(`${ORIGIN}/wheels/${SLUG}/present`, { waitUntil: "networkidle" }); const dprCanvas = dprPage.locator(".wheel-stage canvas").first(); await dprCanvas.waitFor(); await ready(dprCanvas); const measured = await sample(dprCanvas, `dpr-${dpr}`); assertCanonicalFrame(measured, `DPR ${dpr}`); assert.equal(measured.metrics.dpr, Math.min(dpr, WHEEL_GEOMETRY.dprCap)); assert.equal(measured.canvas.width, measured.canvas.height); assert.deepEqual(dprEvidence.writes, []); assert.deepEqual(dprEvidence.errors, []); v113.dpr.push({ viewport: { width: 1280, height: 720 }, value: dpr, sample: compact(measured) }); await dprContext.close();
  }
  const resizeContext = await browser.newContext({ viewport: { width: 1920, height: 1080 }, reducedMotion: "no-preference" }); await consent(resizeContext); const resizePage = await resizeContext.newPage(); const resizeEvidence = monitor(resizePage); if (FIXTURE) await routes(resizePage); await resizePage.goto(`${ORIGIN}/wheels/${SLUG}/present`, { waitUntil: "networkidle" }); const resizeCanvas = resizePage.locator(".wheel-stage canvas").first(); await resizeCanvas.waitFor(); await ready(resizeCanvas);
  for (const viewport of [{ width: 1920, height: 1080 }, { width: 768, height: 1024 }, { width: 473, height: 1024 }, { width: 844, height: 390 }, { width: 473, height: 1024 }, { width: 1920, height: 1080 }]) { await resizePage.setViewportSize(viewport); await resizePage.waitForTimeout(250); const measured = await sample(resizeCanvas, `resize-${viewport.width}x${viewport.height}`); assertCanonicalFrame(measured, `resize ${viewport.width}x${viewport.height}`); v113.repeatedResize.push({ viewport, sample: compact(measured) }); if (viewport.width === 844) await resizePage.screenshot({ path: join(ARTIFACTS, "mobile-landscape-844x390.png") }); }
  const fullscreenButton = resizePage.getByRole("button", { name: "Fullscreen" }).first(); await fullscreenButton.click(); await resizePage.waitForFunction(() => Boolean(document.fullscreenElement)); await resizePage.waitForTimeout(250); const fullscreen = await sample(resizeCanvas, "fullscreen"); assertCanonicalFrame(fullscreen, "fullscreen"); v113.fullscreen.push({ state: "entered", sample: compact(fullscreen) }); await resizePage.screenshot({ path: join(ARTIFACTS, "presentation-fullscreen.png") }); await resizePage.evaluate(() => document.exitFullscreen()); await resizePage.waitForFunction(() => !document.fullscreenElement); await resizePage.waitForTimeout(250); const exited = await sample(resizeCanvas, "fullscreen-exited"); assertCanonicalFrame(exited, "fullscreen exited"); v113.fullscreen.push({ state: "exited", sample: compact(exited) }); assert.deepEqual(resizeEvidence.writes, []); assert.deepEqual(resizeEvidence.errors, []); await resizeContext.close();

  for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) { const previewContext = await browser.newContext({ viewport, reducedMotion: "no-preference" }); await consent(previewContext); const preview = await previewContext.newPage(); const previewEvidence = monitor(preview); if (FIXTURE) await routes(preview); await preview.goto(`${ORIGIN}/wheels/${SLUG}/edit`); const editor = preview.getByRole("dialog", { name: /Edit V1.9 Stability Fixture/i }); await editor.waitFor(); await editor.getByRole("tab", { name: "appearance" }).click(); await editor.getByRole("button", { name: "Customize appearance" }).click(); const appearance = preview.getByRole("dialog", { name: /Tune the broadcast stage/i }); await appearance.waitFor(); const previewCanvas = appearance.locator(".wheel-stage canvas"); await ready(previewCanvas); const previewSample = await sample(previewCanvas, "appearance"); assert.ok(previewSample.metrics.plan.segments.some((segment) => segment.pattern)); assert.ok(previewSample.metrics.plan.segments.some((segment) => segment.image)); const fit = await appearance.evaluate((node) => ({ overflow: node.scrollWidth - node.clientWidth, documentOverflow: document.documentElement.scrollWidth - document.documentElement.clientWidth })); assert.ok(fit.overflow <= 1 && fit.documentOverflow <= 1, JSON.stringify({ viewport, fit })); await preview.screenshot({ path: join(ARTIFACTS, `appearance-${viewport.width}x${viewport.height}.png`) }); assert.deepEqual(previewEvidence.writes, []); assert.deepEqual(previewEvidence.errors, []); await previewContext.close(); }
  const reducedContext = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: "reduce" }); await consent(reducedContext); const reducedPage = await reducedContext.newPage(); const reducedEvidence = monitor(reducedPage); if (FIXTURE) await routes(reducedPage); await reducedPage.goto(`${ORIGIN}/wheels/${SLUG}`); const reducedCanvas = reducedPage.locator(".wheel-stage canvas").first(); await reducedCanvas.waitFor(); await ready(reducedCanvas); const reducedBefore = await sample(reducedCanvas, "reduced-before"); await reducedPage.getByRole("button", { name: "Start demo spin" }).click(); await reducedPage.getByRole("dialog").waitFor({ timeout: 2_500 }); const reducedAfter = await sample(reducedCanvas, "reduced-after"); assert.deepEqual(staticCounts(reducedAfter.metrics), staticCounts(reducedBefore.metrics)); assert.deepEqual(localMetrics(reducedAfter.metrics.plan), localMetrics(reducedBefore.metrics.plan)); assert.deepEqual(reducedEvidence.writes, []); assert.deepEqual(reducedEvidence.errors, []); await reducedContext.close();
  await writeFile(join(ARTIFACTS, "v19-render-stability-metrics.json"), JSON.stringify({ origin: ORIGIN, frames: frames.map(compact), baselineStatic, settledStatic: staticCounts(settled.metrics), matrix, writes: evidence.writes, errors: evidence.errors }, null, 2));
  await writeFile(join(ARTIFACTS, "v113-geometry-evidence.json"), JSON.stringify({ origin: ORIGIN, canonical: WHEEL_GEOMETRY, matrix, ...v113 }, null, 2));
});

async function ready(canvas) { await canvas.evaluate((node) => new Promise((resolve, reject) => { const started = performance.now(); const check = () => { const debug = node.__wheelRendererV19; if (debug?.plan && debug.plan.segments.filter((segment) => segment.style.mode === "image").every((segment) => segment.image) && debug.gifFramesDecoded >= 1) resolve(); else if (performance.now() - started > 5000) reject(new Error(`renderer not ready: ${JSON.stringify(debug)}`)); else setTimeout(check, 50); }; check(); })); await new Promise((resolve) => setTimeout(resolve, 180)); }
async function sample(canvas, name) { return canvas.evaluate((node, sampleName) => { const rotor = node.parentElement; const frame = node.closest(".wheel-stage"); const hub = frame.querySelector(".wheel-stage__hub"); const matrix = new DOMMatrixReadOnly(getComputedStyle(rotor).transform); const frameRect = frame.getBoundingClientRect(); const canvasStyle = getComputedStyle(node); const scale = frameRect.width / frame.clientWidth; const metrics = structuredClone(node.__wheelRendererV19); return { name: sampleName, canvas: { width: node.width, height: node.height, cssWidth: Number.parseFloat(canvasStyle.width) * scale, cssHeight: Number.parseFloat(canvasStyle.height) * scale }, frame: { width: frameRect.width, height: frameRect.height }, rotor: { width: rotor.clientWidth * scale, height: rotor.clientHeight * scale }, rect: node.getBoundingClientRect().toJSON(), transform: getComputedStyle(rotor).transform, rotation: Math.atan2(matrix.b, matrix.a) * 180 / Math.PI, transformScale: { x: Math.hypot(matrix.a, matrix.b), y: Math.hypot(matrix.c, matrix.d) }, geometry: { outerDiameter: frameRect.width, faceDiameter: metrics.faceDiameter * scale, faceToOuterRatio: metrics.faceDiameter * scale / frameRect.width, hubDiameter: hub.getBoundingClientRect().width, hubToOuterRatio: hub.getBoundingClientRect().width / frameRect.width }, metrics }; }, name); }
function staticCounts(metrics) { return { planBuilds: metrics.planBuilds, staticFaceRebuilds: metrics.staticFaceRebuilds, measureTextCalls: metrics.measureTextCalls, patternConstructions: metrics.patternConstructions, imageCoverCalculations: metrics.imageCoverCalculations, size: metrics.size, dpr: metrics.dpr, pixels: metrics.pixels }; }
function assertCanonicalFrame(frame, label) { assert.ok(Math.abs(frame.frame.width / frame.frame.height - 1) <= .002, `${label} frame ${JSON.stringify(frame.frame)}`); assert.ok(Math.abs(frame.rotor.width / frame.rotor.height - 1) <= .002, `${label} rotor ${JSON.stringify(frame.rotor)}`); assert.ok(Math.abs(frame.canvas.cssWidth / frame.canvas.cssHeight - 1) <= .002, `${label} Canvas CSS ${JSON.stringify(frame.canvas)}`); assert.equal(frame.canvas.width, frame.canvas.height, `${label} Canvas backing`); assert.ok(Math.abs(frame.geometry.faceToOuterRatio - WHEEL_FACE_TO_OUTER_RATIO) <= .005, `${label} face ratio ${JSON.stringify(frame.geometry)}`); assert.ok(Math.abs(frame.geometry.hubToOuterRatio - WHEEL_GEOMETRY.hubToOuterRatio) <= .005, `${label} hub ratio ${JSON.stringify(frame.geometry)}`); assert.ok(Math.abs(frame.transformScale.x - frame.transformScale.y) <= .00001, `${label} transform ${JSON.stringify(frame.transformScale)}`); }
function localMetrics(plan) { return plan.segments.map((segment) => ({ id: segment.entry.id, fontSize: segment.label.fontSize, measuredWidth: segment.label.measuredWidth, maxWidth: segment.label.maxWidth, tangentSpan: segment.tangentSpan, pattern: segment.pattern && { tileWidth: segment.pattern.tileWidth, tileHeight: segment.pattern.tileHeight, lineWidth: segment.pattern.lineWidth, dotRadius: segment.pattern.dotRadius, originX: segment.pattern.originX, originY: segment.pattern.originY, scale: segment.pattern.scale }, image: segment.image && { scale: segment.image.scale, cropWidth: segment.image.cropWidth, cropHeight: segment.image.cropHeight, localOrientation: segment.image.localOrientation } })); }
function compact(frame) { return { name: frame.name, frame: frame.frame, rotor: frame.rotor, canvas: frame.canvas, geometry: frame.geometry, rotation: frame.rotation, transform: frame.transform, transformScale: frame.transformScale, static: staticCounts(frame.metrics), gifFramesDecoded: frame.metrics.gifFramesDecoded, faceComposites: frame.metrics.faceComposites }; }
async function fingerprint(canvas) { return canvas.evaluate((node) => { const context = node.getContext("2d"); const image = context.getImageData(Math.floor(node.width * .05), Math.floor(node.height * .05), Math.floor(node.width * .9), Math.floor(node.height * .9)).data; let hash = 2166136261; for (let index = 0; index < image.length; index += 17) { hash ^= image[index]; hash = Math.imul(hash, 16777619); } return String(hash >>> 0); }); }
function monitor(page) { const writes = []; const errors = []; page.on("request", (request) => { const url = new URL(request.url()); if (url.pathname.startsWith("/api/wheels") && !["GET", "HEAD"].includes(request.method())) writes.push(`${request.method()} ${url.pathname}`); }); page.on("console", (entry) => { if (entry.type() === "error") { const location = entry.location().url; errors.push(`${entry.text()}${location ? ` @ ${location}` : ""}`); } }); page.on("pageerror", (error) => errors.push(error.message)); return { writes, errors }; }
async function routes(page) { if (!LOCAL) await page.route(new RegExp(`/wheels/${escapeRegExp(SLUG)}(?:/[^?#]*)?(?:[?#].*)?$`), async (route) => { if (route.request().resourceType() !== "document") return route.continue(); const response = await fetch(`${ORIGIN}/index.html`); return route.fulfill({ status: response.status, contentType: "text/html; charset=utf-8", body: await response.text() }); }); await page.route("**/api/**", respond); await page.route("**/api/wheels/media/static-v19", (route) => route.fulfill({ status: 200, contentType: "image/svg+xml", body: orientationSvg() })); await page.route("**/api/wheels/media/gif-v19", (route) => route.fulfill({ status: 200, contentType: "image/gif", body: GIF })); }
async function respond(route) { const url = new URL(route.request().url()); if (url.pathname === "/api/auth/config") return json(route, { configured: true, emailSignupConfigured: false, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: ORIGIN, adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" }); if (url.pathname === "/api/auth/session") return json(route, { ok: true, authenticated: true, csrfToken: "v19-fixture", access: { isAdmin: false, isMasterAdmin: false }, account: { id: "creator", email: "creator@example.test", displayName: "Creator", avatarUrl: null, providers: ["email"], role: "user", adminLevel: "none", status: "active", emailVerified: true, createdAt: "2026-08-30T00:00:00Z", source: "test" } }); if (url.pathname === "/api/wheels/mechanics") return json(route, { ok: true, revision: 12, mechanics: { mechanicsVersion: 1, curveProfile: "broadcast-smooth", customCurve: { holdEnd: .04, tailStart: .66, tailVelocity: .12 }, launchRpsMin: 2.8, launchRpsMax: 4.5, minimumFullTurns: 2, maximumFullTurns: 120, defaultSpinDurationMs: 6500, minimumSpinDurationMs: 2000, maximumSpinDurationMs: 60000 } }); if (url.pathname === "/api/wheels") return json(route, { ok: true, items: [{ slug: SLUG, title: "V1.9 Stability Fixture", description: "Synthetic local renderer fixture", participantCount: 8, weighted: true, themePreset: "custom", palette: ["#11110E"], demoEnabled: true, officialEnabled: false, latestOfficialAt: null }], count: 1 }); if (url.pathname === "/api/wheels/access") return json(route, { ok: true, authenticated: true, canCreate: true, isMasterAdmin: false, maximumOwnedWheels: 20 }); if (url.pathname === `/api/wheels/${SLUG}`) return json(route, payload()); return json(route, { ok: true }); }
function payload() { const labels = ["A", "Daniel", "Demo GOAT 01", "THIS IS A MUCH LONGER PARTICIPANT NAME", "Dots", "Triangles", "Third Rail Bolts", "Static Image"]; const styles = [{ mode: "pattern", color: "#11110E", pattern: "zigzag", patternColor: "#F3C928" }, { mode: "solid", color: "#B8182F" }, { mode: "pattern", color: "#0D6F73", pattern: "dots", patternColor: "#FFFFFF" }, { mode: "pattern", color: "#6D3A93", pattern: "checkers", patternColor: "#FFFFFF" }, { mode: "pattern", color: "#B8182F", pattern: "triangles", patternColor: "#F3C928" }, { mode: "image", color: "#181818", imageAssetId: GIF_ID }, { mode: "pattern", color: "#11110E", pattern: "third-rail-bolts", patternColor: "#F3C928" }, { mode: "image", color: "#181818", imageAssetId: STATIC_ID }]; const entries = labels.map((label, order) => ({ id: `00000000-0000-4000-8000-00000000000${order + 1}`, label, order, weight: [8, 5, 3, 1, 2, 2, 2, 2][order], colour: null, style: styles[order], state: "active" })); return { ok: true, wheel: { slug: SLUG, title: "V1.9 Stability Fixture", description: "Synthetic local renderer fixture", lifecycle: "active", visibility: "public", participantCount: 8, weighted: true, entries, config: { themePreset: "custom", palette: ["#11110E"], paletteStyles: [{ mode: "solid", color: "#11110E" }], pointerAccent: "#F3C928", centreTreatment: "bolt", backgroundIntensity: "medium", labelContrast: "light", spinDurationMs: 3600, tickingSoundEnabled: false, spinSoundPreset: "silent", winnerSoundEnabled: false, winnerSoundPreset: "silent", celebrationEnabled: false, confettiEnabled: false, fireworksEnabled: false, winnerLightingEnabled: false, celebrationIntensity: "normal", backgroundEnabled: false, backgroundFocalX: 50, backgroundFocalY: 50, backgroundImageOpacity: 70, backgroundOverlayIntensity: 60, winnerMessageTemplate: "Signal locked: {winner}", publicHistoryVisible: true }, media: { background: null, centre: null, segmentFills: [{ id: GIF_ID, purpose: "segment_fill", url: `${ORIGIN}/api/wheels/media/gif-v19`, contentType: "image/gif", byteSize: GIF.length, width: 1, height: 1, sha256: "fixture", fileName: "two-frame.gif", animationCapable: true, createdAt: "2026-08-30T00:00:00Z" }, { id: STATIC_ID, purpose: "segment_fill", url: `${ORIGIN}/api/wheels/media/static-v19`, contentType: "image/svg+xml", byteSize: orientationSvg().length, width: 80, height: 120, sha256: "fixture-static", fileName: "orientation.svg", animationCapable: false, createdAt: "2026-08-30T00:00:00Z" }] }, demoEnabled: true, officialEnabled: false, latestOfficialResult: null, recentOfficialResults: [], revision: 19 }, access: { role: "editor", isMasterAdmin: false, canEdit: true, canSpinOfficially: false, editingLocked: false, officialSpinLocked: false, revision: 19 } }; }
function orientationSvg() { return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 120"><rect width="80" height="120" fill="#0D6F73"/><path d="M40 4 72 54H52v62H28V54H8Z" fill="#F3C928"/></svg>'; }
function twoFrameGif() { return Buffer.from([0x47,0x49,0x46,0x38,0x39,0x61,1,0,1,0,0x80,0,0,0x18,0x18,0x18,0xff,0x35,0x55,0x21,0xff,0x0b,...Buffer.from("NETSCAPE2.0"),3,1,0,0,0,0x21,0xf9,4,0,10,0,0,0,0x2c,0,0,0,0,1,0,1,0,0,2,2,0x44,1,0,0x21,0xf9,4,0,10,0,0,0,0x2c,0,0,0,0,1,0,1,0,0,2,2,0x4c,1,0,0x3b]); }
async function consent(context) { const now = Date.now(); await context.addCookies([{ name: "thirdrailify_consent", value: encodeURIComponent(JSON.stringify({ version: 1, timestamp: new Date(now).toISOString(), expiry: new Date(now + 2592000000).toISOString(), categories: { preferences: false, externalMedia: false } })), url: ORIGIN }]); }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
function escapeRegExp(value) { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
async function waitForPreview() { for (let attempt = 0; attempt < 80; attempt += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Vite preview did not start."); }
