import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4185"; const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";

test("Wheels V1.1 celebration, appearance, Community navigation, and VIP surfaces have real responsive browser evidence", async (t) => {
  const artifacts = fileURLToPath(new URL("../.artifacts/wheels-v11/", import.meta.url)); await mkdir(artifacts, { recursive: true }); const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4185"], { stdio: "ignore" }); t.after(() => server.kill()); await wait();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close()); const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "no-preference" }); const now = Date.now(); await context.addCookies([{ name: "thirdrailify_consent", value: encodeURIComponent(JSON.stringify({ version: 1, timestamp: new Date(now).toISOString(), expiry: new Date(now + 1000 * 60 * 60 * 24 * 30).toISOString(), categories: { preferences: false, externalMedia: false } })), domain: "127.0.0.1", path: "/" }]); await fakeAudio(context); const page = await context.newPage(); const errors = []; page.on("console", (entry) => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("pageerror", (error) => errors.push(error.message)); await page.route("**/api/**", respond);
  await page.goto(`${ORIGIN}/wheels/third-railify-demo-draw`); await dismissPrivacy(page); await page.getByRole("heading", { level: 1, name: "Third Railify Demo Draw" }).waitFor(); assert.equal(await page.getByRole("button", { name: "Start demo spin" }).textContent().then((value) => value.includes("SPIN WHEEL")), true); assert.equal(await page.getByText("SPIN THE RAIL", { exact: true }).count(), 0); await page.screenshot({ path: `${artifacts}/wheel-idle-1440.png`, fullPage: true });
  await page.getByRole("button", { name: "Start demo spin" }).click(); await page.waitForTimeout(350); assert.equal(await page.locator(".wheel-stage.is-spinning").count(), 1); await page.screenshot({ path: `${artifacts}/wheel-spinning-1440.png`, fullPage: false }); await page.getByRole("dialog").waitFor(); assert.equal(await page.locator(".winner-confetti i").count(), 58); assert.equal(await page.locator(".winner-lightshow").count(), 1); assert.equal(await page.evaluate(() => window.__audio.starts), 4); await page.screenshot({ path: `${artifacts}/winner-confetti-lighting-1440.png`, fullPage: false });
  await page.getByRole("button", { name: "Close result" }).click(); await page.getByRole("button", { name: "Turn wheel sound off" }).click(); await page.getByRole("button", { name: "Start demo spin" }).click(); await page.getByRole("dialog").waitFor(); assert.equal(await page.evaluate(() => window.__audio.starts), 4, "muted winner creates no second stinger"); await page.getByRole("button", { name: "Close result" }).click();
  await page.getByRole("button", { name: "Appearance" }).click(); await page.getByRole("dialog", { name: /Tune the broadcast stage/i }).waitFor(); for (const tab of ["theme", "background", "centre", "celebration"]) assert.equal(await page.getByRole("tab", { name: tab }).count(), 1); await page.getByRole("tab", { name: "background" }).click(); await page.getByLabel("Background image").setInputFiles({ name: "synthetic-wheel-stage.svg", mimeType: "image/svg+xml", buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 900"><rect width="1600" height="900" fill="#4b121b"/><path stroke="#f3c928" stroke-width="18" d="M0 700L1600 160"/></svg>') }); await page.screenshot({ path: `${artifacts}/appearance-background-preview-1440.png`, fullPage: false }); await page.getByRole("tab", { name: "centre" }).click(); await page.getByLabel("Centre image").setInputFiles({ name: "synthetic-centre.svg", mimeType: "image/svg+xml", buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><circle cx="400" cy="400" r="360" fill="#171810"/><path fill="#f3c928" d="M430 50L180 450h180l-40 300 300-430H430z"/></svg>') }); assert.equal(await page.locator(".appearance-preview .wheel-stage__hub.is-custom img").count(), 1); await page.screenshot({ path: `${artifacts}/appearance-centre-preview-1440.png`, fullPage: false }); await page.getByRole("button", { name: "Discard" }).click();
  await page.getByRole("link", { name: "Home", exact: true }).click(); await page.getByText("Follow the rail.").waitFor(); const placement = await page.evaluate(() => { const community = document.querySelector(".community-section"); const vip = document.querySelector(".home-vip-section"); const follow = document.querySelector(".follow-section"); return Boolean(community && vip && follow && (community.compareDocumentPosition(vip) & Node.DOCUMENT_POSITION_FOLLOWING) && (vip.compareDocumentPosition(follow) & Node.DOCUMENT_POSITION_FOLLOWING)); }); assert.equal(placement, true); assert.equal(await page.getByRole("button", { name: "Toggle Community links" }).count(), 0, "Community header label has no arrow/chevron control"); await page.getByRole("link", { name: "Community", exact: true }).hover(); await page.getByRole("link", { name: "GOATS in the Wild", exact: true }).waitFor(); assert.equal(await page.getByRole("link", { name: "Wheels", exact: true }).count() >= 1, true); await page.screenshot({ path: `${artifacts}/community-dropdown-1440.png`, fullPage: false });
  await page.goto(`${ORIGIN}/community`); assert.equal(await page.locator(".community-paths").getByText("VIP", { exact: true }).count(), 0); assert.equal(await page.locator(".community-vip-feature .vip-feature-card").count(), 1); await page.screenshot({ path: `${artifacts}/community-vip-1440.png`, fullPage: true });
  await page.goto(`${ORIGIN}/vip`); await page.getByRole("heading", { level: 1, name: /THE INNER RAIL IS BEING BUILT/i }).waitFor(); assert.equal(await page.getByRole("button", { name: /buy|purchase|subscribe/i }).count(), 0); assert.equal(await page.locator("h1").count(), 1); await page.screenshot({ path: `${artifacts}/vip-1440.png`, fullPage: true }); await page.setViewportSize({ width: 390, height: 844 }); await page.reload(); await page.getByRole("heading", { level: 1 }).waitFor(); await assertFits(page); await page.getByRole("button", { name: "Open navigation" }).click(); assert.equal(await page.getByRole("link", { name: "VIP", exact: true }).count() >= 1, true); assert.equal(await page.locator(".mobile-nav__community").getByRole("link", { name: "Wheels" }).count(), 1); await page.screenshot({ path: `${artifacts}/vip-mobile-390.png`, fullPage: true });
  for (const viewport of [{ width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) { await page.setViewportSize(viewport); await page.goto(`${ORIGIN}/`); await page.locator("main h1").waitFor(); await assertFits(page); }
  for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) { await page.setViewportSize(viewport); for (const route of ["/", "/community"]) { await page.goto(`${ORIGIN}${route}`); await page.locator("main h1").waitFor(); await assertFits(page); } }
  for (const viewport of [{ width: 1920, height: 1080 }, { width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) { await page.setViewportSize(viewport); await page.goto(`${ORIGIN}/vip`); await page.locator("main h1").waitFor(); await assertFits(page); }
  for (const viewport of [{ width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) { await page.setViewportSize(viewport); await page.goto(`${ORIGIN}/wheels/third-railify-demo-draw`); await page.getByRole("button", { name: "Appearance" }).click(); await page.getByRole("dialog", { name: /Tune the broadcast stage/i }).waitFor(); await assertFits(page); const dialog = await page.locator(".appearance-dialog").boundingBox(); assert.ok(dialog && dialog.width <= viewport.width && dialog.height <= viewport.height); await page.getByRole("button", { name: "Discard" }).click(); }
  assert.equal(await page.evaluate(() => window.__audio.closes >= 1), true, "audio context closes after leaving the wheel route"); assert.deepEqual(errors, []); await context.close();
});

async function respond(route) { const url = new URL(route.request().url()); const method = route.request().method(); if (url.pathname === "/api/auth/config") return json(route, { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: ORIGIN, adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" }); if (url.pathname === "/api/auth/session") return json(route, session()); if (url.pathname === "/api/watch") return json(route, { available: false, liveNow: [], primary: null, latest: null, upcoming: null }); if (url.pathname === "/api/currency-rates") return json(route, { ok: true, base: "CAD", date: "2026-08-29", rates: { CAD: 1 } }); if (url.pathname === "/api/commerce/catalogue") return json(route, { ok: true, source: "commerce-d1", currency: "CAD", checkoutEnabled: false, products: [], collections: [], updatedAt: null }); if (url.pathname === "/api/catalogue/banner") return json(route, { ok: true, normal: { enabled: false, messages: [] }, live: { enabled: false }, homeRail: { enabled: false, items: [] } }); if (url.pathname === "/api/community/discord") return json(route, { available: true, schema: "thirdrailify-discord-community-v1", freshness: "fresh", generatedAt: "2026-08-29T00:00:00.000Z", ageSeconds: 0, guild: { id: "fixture", name: "Third Railify", inviteUrl: "https://discord.com/invite/Bd8hU5aFxA" }, counts: { onlineMembers: 0 }, channels: [], voiceSpaces: [], members: [] }); if (url.pathname === "/api/wheels/third-railify-demo-draw") return json(route, wheel()); if (url.pathname.endsWith("/spins") && method === "POST") return json(route, { ok: true, spin: { id: "spin", winningEntryId: "entry-2", winningLabel: "Demo GOAT 02", createdAt: new Date().toISOString() }, idempotent: false }); return json(route, { ok: true }); }
function wheel() { const entries = Array.from({ length: 8 }, (_, index) => ({ id: `entry-${index + 1}`, label: `Demo GOAT 0${index + 1}`, order: index, weight: 1, colour: null, state: "active" })); return { ok: true, wheel: { slug: "third-railify-demo-draw", title: "Third Railify Demo Draw", description: "Synthetic V1.1 browser fixture", lifecycle: "active", visibility: "public", participantCount: 8, weighted: false, entries, config: { themePreset: "third-rail-gold", palette: ["#F3C928", "#B8182F", "#F3F0E5", "#5B2C83"], pointerAccent: "#F3C928", centreTreatment: "bolt", backgroundIntensity: "high", labelContrast: "light", spinDurationMs: 2000, tickingSoundEnabled: false, winnerSoundEnabled: true, celebrationEnabled: true, confettiEnabled: true, winnerLightingEnabled: true, celebrationIntensity: "normal", backgroundEnabled: true, backgroundFocalX: 50, backgroundFocalY: 50, backgroundImageOpacity: 72, backgroundOverlayIntensity: 58, winnerMessageTemplate: "Signal locked: {winner}", publicHistoryVisible: true }, media: { background: null, centre: null }, demoEnabled: true, officialEnabled: true, latestOfficialResult: null, recentOfficialResults: [], revision: 7 }, access: { role: "editor", isMasterAdmin: false, canEdit: true, canSpinOfficially: true, editingLocked: false, officialSpinLocked: false, revision: 7 } }; }
function session() { return { ok: true, authenticated: true, csrfToken: "fixture-csrf", access: { isAdmin: false, isMasterAdmin: false }, account: { id: "creator", email: "creator@example.test", displayName: "Approved Creator", avatarUrl: null, providers: ["email"], role: "user", adminLevel: "none", status: "active", emailVerified: true, createdAt: new Date().toISOString(), source: "test" } }; }
async function fakeAudio(context) { await context.addInitScript(() => { const priorCloses = Number(sessionStorage.getItem("wheel-audio-closes") || 0); window.__audio = { contexts: 0, starts: 0, stops: 0, closes: priorCloses, resumes: 0 }; class FakeNode { connect(node) { return node; } } class FakeOscillator extends FakeNode { constructor() { super(); this.frequency = { value: 0 }; this.type = "sine"; } start() { window.__audio.starts += 1; } stop() { window.__audio.stops += 1; } } class FakeGain extends FakeNode { constructor() { super(); this.gain = { setValueAtTime() {}, exponentialRampToValueAtTime() {} }; } } window.AudioContext = class { constructor() { window.__audio.contexts += 1; this.state = "running"; this.currentTime = 0; this.destination = new FakeNode(); } createOscillator() { return new FakeOscillator(); } createGain() { return new FakeGain(); } resume() { window.__audio.resumes += 1; this.state = "running"; return Promise.resolve(); } close() { window.__audio.closes += 1; sessionStorage.setItem("wheel-audio-closes", String(window.__audio.closes)); this.state = "closed"; return Promise.resolve(); } }; }); }
async function dismissPrivacy(page) { const button = page.getByRole("button", { name: /Reject non-essential/i }); if (await button.count()) await button.click(); }
async function assertFits(page) { const value = await page.evaluate(() => ({ fits: document.documentElement.scrollWidth <= document.documentElement.clientWidth, width: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth })); assert.equal(value.fits, true, JSON.stringify(value)); }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function wait() { for (let index = 0; index < 60; index += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* start */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Preview did not start."); }
