import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4186";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const ORDER = ["alpha-wheel", "beta-wheel", "gamma-wheel", "delta-wheel"];
const TITLES = { "alpha-wheel": "Alpha Signal", "beta-wheel": "Beta Draw", "gamma-wheel": "Gamma Night", "delta-wheel": "Delta Finale" };
const ACCENTS = { "alpha-wheel": "#F3C928", "beta-wheel": "#F05A47", "gamma-wheel": "#5FE5D5", "delta-wheel": "#C98BE5" };

test("Wheels V1.6 navigates adjacent public scenes without remounting the shell", async (t) => {
  const artifacts = fileURLToPath(new URL("../.artifacts/wheels-v16/", import.meta.url)); await mkdir(artifacts, { recursive: true });
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4186"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForPreview();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "no-preference" }); await addConsent(context); await context.addInitScript(() => { Object.defineProperty(navigator, "share", { configurable: true, value: async (data) => { globalThis.__wheelSharePayload = data; } }); }); const page = await context.newPage();
  const details = []; const media = []; const documents = []; const errors = []; const writes = [];
  page.on("request", (request) => { const url = new URL(request.url()); if (request.resourceType() === "document") documents.push(url.pathname); if (/^\/api\/wheels\/[^/]+$/.test(url.pathname)) details.push(url.pathname); if (url.pathname.startsWith("/wheel-media/")) media.push(url.pathname); if (url.pathname.startsWith("/api/") && !["GET", "HEAD"].includes(request.method())) writes.push(`${request.method()} ${url.pathname}`); });
  page.on("console", (entry) => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("pageerror", (error) => errors.push(error.message));
  await page.route("**/api/**", respond); await page.route("**/wheel-media/**", (route) => route.fulfill({ status: 200, contentType: "image/svg+xml", body: mediaSvg(new URL(route.request().url()).pathname) }));

  await page.goto(`${ORIGIN}/wheels/beta-wheel`); await page.getByRole("heading", { level: 1, name: TITLES["beta-wheel"] }).waitFor();
  await page.getByRole("button", { name: `Previous wheel: ${TITLES["alpha-wheel"]}` }).waitFor(); await page.getByRole("button", { name: `Next wheel: ${TITLES["gamma-wheel"]}` }).waitFor();
  await waitFor(() => details.includes("/api/wheels/alpha-wheel") && details.includes("/api/wheels/gamma-wheel"));
  assert.equal(details.includes("/api/wheels/delta-wheel"), false, "initial detail prefetch is limited to immediate neighbours");
  await waitFor(() => media.includes("/wheel-media/alpha-wheel.svg") && media.includes("/wheel-media/gamma-wheel.svg"));
  await page.locator("[data-site-shell]").evaluate((node) => { node.setAttribute("data-v16-instance", "retained"); window.addEventListener("beforeunload", () => { document.documentElement.dataset.beforeUnload = "true"; }); });
  const initialDocuments = documents.length; const stageTop = await page.locator(".wheel-visual-wrap").evaluate((node) => node.getBoundingClientRect().top + window.scrollY); await page.evaluate((top) => window.scrollTo(0, top), stageTop); const stageScroll = await page.evaluate(() => window.scrollY);

  await page.getByRole("button", { name: `Next wheel: ${TITLES["gamma-wheel"]}` }).evaluate((button) => button.click());
  await page.locator('[data-wheel-scene="outgoing"]').waitFor(); assert.equal(new URL(page.url()).pathname, "/wheels/gamma-wheel", "URL updates through React Router at navigation start");
  assert.equal(await page.locator('[data-wheel-scene="incoming"] [aria-label^="Next wheel:"]').isDisabled(), true, "rapid navigation is locked during the bounded transition");
  await page.waitForTimeout(150); const nextFrame = await transitionFrame(page); assert.ok(nextFrame.outgoingX < -1, JSON.stringify(nextFrame)); assert.ok(nextFrame.incomingX > 1, JSON.stringify(nextFrame)); assert.ok(nextFrame.outgoingOpacity < 1 && nextFrame.incomingOpacity > 0, JSON.stringify(nextFrame)); assert.equal(nextFrame.fits, true); assert.equal(nextFrame.backgrounds, 2); assert.ok(Math.abs(nextFrame.scrollY - stageScroll) < 4, `mid-transition scroll preserved: ${stageScroll} -> ${JSON.stringify(nextFrame)}`); await page.screenshot({ path: `${artifacts}/next-midpoint-1440.png`, fullPage: false });
  await settle(page, "gamma-wheel"); assert.equal(await page.locator("canvas").count(), 1); assert.equal(documents.length, initialDocuments); assert.equal(await page.locator('[data-site-shell][data-v16-instance="retained"]').count(), 1); assert.notEqual(await page.evaluate(() => document.documentElement.dataset.beforeUnload || ""), "true"); const settledScroll = await page.evaluate(() => window.scrollY); assert.ok(Math.abs(settledScroll - stageScroll) < 4, `wheel-to-wheel navigation preserves the stage scroll position: ${stageScroll} -> ${settledScroll}`);

  await page.goBack(); await page.locator('[data-wheel-scene="outgoing"]').waitFor(); await page.waitForTimeout(150); const previousFrame = await transitionFrame(page); assert.ok(previousFrame.outgoingX > 1, JSON.stringify(previousFrame)); assert.ok(previousFrame.incomingX < -1, JSON.stringify(previousFrame)); assert.equal(previousFrame.fits, true); await page.screenshot({ path: `${artifacts}/previous-midpoint-1440.png`, fullPage: false }); await settle(page, "beta-wheel");
  await page.goForward(); await settle(page, "gamma-wheel"); assert.equal(documents.length, initialDocuments, "Back and Forward remain SPA history transitions"); assert.equal(await page.locator('[data-site-shell][data-v16-instance="retained"]').count(), 1);

  await page.getByRole("button", { name: `Previous wheel: ${TITLES["beta-wheel"]}` }).click(); await settle(page, "beta-wheel"); await page.getByRole("button", { name: `Previous wheel: ${TITLES["alpha-wheel"]}` }).click(); await settle(page, "alpha-wheel");
  assert.equal(await page.getByRole("button", { name: /Previous wheel unavailable; start of gallery/ }).isDisabled(), true); assert.equal(await page.getByRole("button", { name: `Next wheel: ${TITLES["beta-wheel"]}` }).isEnabled(), true); assert.match(await page.locator(".wheel-navigator").innerText(), /01 \/ 04/); await page.screenshot({ path: `${artifacts}/first-boundary-1440.png`, fullPage: false });

  const alphaParticipant = `${TITLES["alpha-wheel"]} entrant 1`; await page.locator(".participant-list").getByRole("button", { name: new RegExp(alphaParticipant) }).click(); await page.getByRole("dialog", { name: alphaParticipant }).waitFor(); await page.getByRole("button", { name: `Next wheel: ${TITLES["beta-wheel"]}` }).evaluate((button) => button.click()); await page.getByRole("dialog", { name: alphaParticipant }).waitFor({ state: "detached" }); await settle(page, "beta-wheel"); await page.getByRole("button", { name: `Previous wheel: ${TITLES["alpha-wheel"]}` }).click(); await settle(page, "alpha-wheel");
  await page.getByRole("button", { name: "Spin wheel from centre" }).click(); assert.equal(await page.getByRole("button", { name: `Next wheel: ${TITLES["beta-wheel"]}` }).isDisabled(), true, "a centre-triggered spin locks gallery navigation"); assert.equal(await page.getByRole("button", { name: "Spin wheel from centre" }).isDisabled(), true, "the centre spin control shares the active-spin lock"); await page.getByRole("dialog").waitFor({ timeout: 5000 }); assert.equal(await page.getByRole("button", { name: `Next wheel: ${TITLES["beta-wheel"]}` }).isDisabled(), true, "open winner result keeps gallery navigation locked"); await page.getByRole("button", { name: "Close result" }).click(); assert.equal(await page.getByRole("button", { name: `Next wheel: ${TITLES["beta-wheel"]}` }).isEnabled(), true);
  await page.getByRole("button", { name: "Manage participants" }).click(); const manager = page.getByRole("dialog", { name: "Manage participants" }); await manager.waitFor(); await manager.locator(".participant-row input").first().fill(`${alphaParticipant} revised`); assert.equal(await page.locator('[data-wheel-scene="active"] .wheel-navigator__direction--next').isDisabled(), true, "dirty participant manager makes the underlying navigator inert"); await manager.getByRole("button", { name: "Close participant manager" }).click(); await manager.getByText("Discard unsaved participant changes?").waitFor(); await manager.getByRole("button", { name: "Discard and close" }).click();
  await page.getByRole("link", { name: "Edit" }).click(); const editor = page.getByRole("dialog", { name: /Edit Alpha Signal/ }); await editor.waitFor(); await editor.getByLabel("Wheel title").fill("Unsaved Alpha Signal"); assert.equal(await page.locator('[data-wheel-scene="active"] .wheel-navigator__direction--next').isDisabled(), true, "dirty editor makes the underlying navigator inert"); await page.getByRole("button", { name: "Close wheel editor" }).click(); await page.getByText("Discard unsaved wheel changes?").waitFor(); await page.getByRole("button", { name: "Discard and close" }).click(); assert.equal(new URL(page.url()).pathname, "/wheels/alpha-wheel");

  await page.getByRole("button", { name: "Appearance" }).click(); const appearance = page.getByRole("dialog", { name: /Tune the broadcast stage/i }); await appearance.waitFor(); assert.equal(await appearance.locator(".palette-grid button").count(), 26); await appearance.getByRole("button", { name: /Electric Blue \/ White/ }).click(); assert.equal(await appearance.getByLabel("Wheel accent hex colour").inputValue(), "#79AFFF"); await appearance.getByLabel(`${alphaParticipant} hex colour`).fill("#FF00AA"); await appearance.getByRole("button", { name: "Reset to default" }).click(); assert.equal(await appearance.getByLabel("Wheel accent hex colour").inputValue(), "#F3C928"); assert.equal(await appearance.getByRole("button", { name: /Third Rail Gold/ }).getAttribute("aria-pressed"), "true"); assert.equal(await appearance.getByLabel(`${alphaParticipant} hex colour`).inputValue(), "#F3C928"); assert.equal(await appearance.locator(".appearance-preview").evaluate((node) => node.style.backgroundImage.includes("url(")), false, "default reset previews the default background treatment"); await page.screenshot({ path: `${artifacts}/appearance-reset-1440.png`, fullPage: false }); await appearance.getByLabel("Wheel accent hex colour").fill("#FF00AA"); assert.equal(await appearance.locator(".appearance-preview").evaluate((node) => getComputedStyle(node).getPropertyValue("--wheel-accent").trim()), "#FF00AA"); assert.equal(await appearance.locator(".wheel-stage").evaluate((node) => getComputedStyle(node).getPropertyValue("--pointer").trim()), "#FF00AA"); await appearance.getByRole("button", { name: "Discard" }).click(); assert.deepEqual(writes, [], "transition and appearance preview acceptance performs no remote mutation");

  await page.getByRole("button", { name: "Share wheel link" }).click(); await page.getByRole("alert").filter({ hasText: "Share options opened for this wheel." }).waitFor(); const shared = await page.evaluate(() => globalThis.__wheelSharePayload); assert.equal(shared.url, `${ORIGIN}/wheels/alpha-wheel`); assert.equal(shared.title, TITLES["alpha-wheel"]); await page.evaluate(() => { Object.defineProperty(navigator, "share", { configurable: true, value: async () => { throw new Error("fixture share sheet unavailable"); } }); }); await page.getByRole("button", { name: "Share wheel link" }).click(); await page.getByRole("alert").filter({ hasText: "Share options were unavailable, so the wheel link was copied instead." }).waitFor();

  assert.deepEqual(errors, []); await context.close();

  const presentation = await browser.newContext({ viewport: { width: 1920, height: 1080 }, reducedMotion: "no-preference" }); await addConsent(presentation); const presentationPage = await presentation.newPage(); await presentationPage.route("**/api/**", respond); await presentationPage.route("**/wheel-media/**", (route) => route.fulfill({ status: 200, contentType: "image/svg+xml", body: mediaSvg("presentation") })); await presentationPage.goto(`${ORIGIN}/wheels/beta-wheel/present`); await presentationPage.getByRole("button", { name: `Next wheel: ${TITLES["gamma-wheel"]}` }).waitFor(); assert.match(await presentationPage.locator(".wheel-navigator").innerText(), /02 \/ 04/); const presentationFit = await presentationPage.evaluate(() => { const tools = [...document.querySelectorAll(".wheel-spin-console__tools .sound-toggle")].map((node) => { const rect = node.getBoundingClientRect(); return { text: node.textContent?.trim(), clientWidth: node.clientWidth, scrollWidth: node.scrollWidth, left: rect.left, right: rect.right }; }); const nav = document.querySelector(".wheel-navigator")?.getBoundingClientRect(); return { fits: document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1, navHeight: nav?.height || 0, tools }; }); assert.equal(presentationFit.fits, true, JSON.stringify(presentationFit)); assert.ok(presentationFit.navHeight <= 58, JSON.stringify(presentationFit)); assert.equal(presentationFit.tools.length, 3); for (const tool of presentationFit.tools) { assert.ok(tool.scrollWidth <= tool.clientWidth + 1, `presentation control is not clipped: ${JSON.stringify(tool)}`); assert.ok(tool.left >= 0 && tool.right <= 1920, `presentation control stays on screen: ${JSON.stringify(tool)}`); } await presentationPage.screenshot({ path: `${artifacts}/presentation-navigation-controls-1920.png`, fullPage: false }); await presentationPage.getByRole("button", { name: `Next wheel: ${TITLES["gamma-wheel"]}` }).click(); await presentationPage.locator('[data-wheel-scene="outgoing"]').waitFor(); await settle(presentationPage, "gamma-wheel", true); await presentation.close();

  const reduced = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: "reduce" }); await addConsent(reduced); const reducedPage = await reduced.newPage(); await reducedPage.route("**/api/**", respond); await reducedPage.route("**/wheel-media/**", (route) => route.fulfill({ status: 200, contentType: "image/svg+xml", body: mediaSvg("reduced") })); await reducedPage.goto(`${ORIGIN}/wheels/beta-wheel`); await reducedPage.getByRole("button", { name: `Next wheel: ${TITLES["gamma-wheel"]}` }).waitFor(); await reducedPage.getByRole("button", { name: `Next wheel: ${TITLES["gamma-wheel"]}` }).click(); await reducedPage.locator('[data-wheel-scene="outgoing"]').waitFor(); const reducedFrame = await transitionFrame(reducedPage); assert.ok(Math.abs(reducedFrame.outgoingX) < 1 && Math.abs(reducedFrame.incomingX) < 1, JSON.stringify(reducedFrame)); assert.equal(reducedFrame.fits, true); await reducedPage.screenshot({ path: `${artifacts}/mobile-reduced-transition-390.png`, fullPage: false }); await settle(reducedPage, "gamma-wheel"); await reduced.close();

  for (const viewport of [{ width: 1920, height: 1080 }, { width: 1365, height: 768 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) {
    const responsive = await browser.newContext({ viewport, reducedMotion: "reduce" }); await addConsent(responsive); const responsivePage = await responsive.newPage(); await responsivePage.route("**/api/**", respond); await responsivePage.route("**/wheel-media/**", (route) => route.fulfill({ status: 200, contentType: "image/svg+xml", body: mediaSvg("responsive") })); await responsivePage.goto(`${ORIGIN}/wheels/beta-wheel`); await responsivePage.locator(".wheel-navigator").waitFor(); const fit = await responsivePage.evaluate(() => ({ fits: document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1, nav: document.querySelector(".wheel-navigator")?.getBoundingClientRect().toJSON(), titleSize: Number.parseFloat(getComputedStyle(document.querySelector(".wheel-control-heading h1")).fontSize) })); assert.equal(fit.fits, true, `${viewport.width}px has no horizontal overflow: ${JSON.stringify(fit)}`); assert.ok(fit.nav && fit.nav.left >= -1 && fit.nav.right <= viewport.width + 1, `${viewport.width}px navigator fits: ${JSON.stringify(fit)}`); assert.ok(fit.nav.height <= 58, `${viewport.width}px navigator is slimline: ${JSON.stringify(fit)}`); assert.ok(fit.titleSize <= 69.5, `${viewport.width}px title remains compact: ${JSON.stringify(fit)}`); if (viewport.width === 390) { await responsivePage.screenshot({ path: `${artifacts}/mobile-navigator-390.png`, fullPage: false }); await responsivePage.goto(`${ORIGIN}/wheels/beta-wheel/present`); await responsivePage.locator(".wheel-navigator").waitFor(); const mobilePresentation = await responsivePage.evaluate(() => ({ fits: document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1, tools: [...document.querySelectorAll(".wheel-spin-console__tools .sound-toggle")].map((node) => ({ clientWidth: node.clientWidth, scrollWidth: node.scrollWidth })) })); assert.equal(mobilePresentation.fits, true, JSON.stringify(mobilePresentation)); assert.equal(mobilePresentation.tools.length, 3); for (const tool of mobilePresentation.tools) assert.ok(tool.scrollWidth <= tool.clientWidth + 1, JSON.stringify(mobilePresentation)); await responsivePage.screenshot({ path: `${artifacts}/mobile-presentation-390.png`, fullPage: false }); } await responsive.close();
  }
});

async function transitionFrame(page) { return page.evaluate(() => { const outgoing = document.querySelector('[data-wheel-scene="outgoing"]'); const incoming = document.querySelector('[data-wheel-scene="incoming"]'); const matrix = (node) => { const value = getComputedStyle(node).transform; return value === "none" ? 0 : new DOMMatrixReadOnly(value).m41; }; return { outgoingX: matrix(outgoing), incomingX: matrix(incoming), outgoingOpacity: Number(getComputedStyle(outgoing).opacity), incomingOpacity: Number(getComputedStyle(incoming).opacity), backgrounds: document.querySelectorAll(".wheel-scene-backgrounds .wheel-control-page__background").length, fits: document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1, scrollY: window.scrollY, scrollHeight: document.documentElement.scrollHeight, clientHeight: document.documentElement.clientHeight, incomingHeight: incoming.getBoundingClientRect().height }; }); }
async function settle(page, slug, presentation = false) { await page.locator('[data-wheel-scene="outgoing"]').waitFor({ state: "detached", timeout: 2500 }); await page.locator(`[data-wheel-scene="active"][data-wheel-slug="${slug}"]`).waitFor(); assert.equal(new URL(page.url()).pathname, `/wheels/${slug}${presentation ? "/present" : ""}`); assert.equal(await page.locator("canvas").count(), 1); }
async function respond(route) { const url = new URL(route.request().url()); const path = url.pathname; if (path === "/api/auth/config") return json(route, { configured: true, emailSignupConfigured: false, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: ORIGIN, adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" }); if (path === "/api/auth/session") return json(route, session()); if (path === "/api/catalogue/banner") return json(route, { ok: true, normal: { enabled: false, messages: [] }, live: { enabled: false } }); if (path === "/api/watch") return json(route, { available: false, liveNow: [], primary: null, latest: null, upcoming: null }); if (path === "/api/currency-rates") return json(route, { ok: true, base: "CAD", date: "2026-08-29", rates: { CAD: 1 } }); if (path === "/api/commerce/catalogue") return json(route, { ok: true, source: "commerce-d1", currency: "CAD", checkoutEnabled: false, updatedAt: null, collections: [], products: [] }); if (path === "/api/wheels") return json(route, { ok: true, items: ORDER.map(summary), count: ORDER.length }); const match = path.match(/^\/api\/wheels\/([^/]+)$/); if (match && ORDER.includes(match[1])) return json(route, payload(match[1])); return json(route, { ok: true }); }
function summary(slug) { return { slug, title: TITLES[slug], description: `${TITLES[slug]} fixture`, participantCount: 4, weighted: false, themePreset: "third-rail-gold", palette: [ACCENTS[slug], "#20201A"], demoEnabled: true, officialEnabled: false, latestOfficialAt: null }; }
function payload(slug) { const entries = Array.from({ length: 4 }, (_, index) => ({ id: `${slug}-${index}`, label: `${TITLES[slug]} entrant ${index + 1}`, order: index, weight: 1, colour: null, state: "active" })); return { ok: true, wheel: { ...summary(slug), lifecycle: "active", visibility: "public", entries, config: { themePreset: "third-rail-gold", palette: [ACCENTS[slug], "#20201A"], pointerAccent: ACCENTS[slug], centreTreatment: "bolt", backgroundIntensity: "high", labelContrast: "light", spinDurationMs: 2000, tickingSoundEnabled: false, winnerSoundEnabled: false, celebrationEnabled: true, confettiEnabled: true, winnerLightingEnabled: true, celebrationIntensity: "normal", backgroundEnabled: true, backgroundFocalX: 50, backgroundFocalY: 50, backgroundImageOpacity: 72, backgroundOverlayIntensity: 58, winnerMessageTemplate: "Signal locked: {winner}", publicHistoryVisible: true }, media: { background: { id: `${slug}-background`, purpose: "background", url: `${ORIGIN}/wheel-media/${slug}.svg`, contentType: "image/svg+xml", byteSize: 100, width: 1440, height: 900, sha256: "fixture", createdAt: "2026-08-29T00:00:00.000Z" }, centre: null }, latestOfficialResult: null, recentOfficialResults: [], revision: 1 }, access: { role: "editor", isMasterAdmin: false, canEdit: true, canSpinOfficially: false, editingLocked: false, officialSpinLocked: false, revision: 1 } }; }
function session() { return { ok: true, authenticated: true, csrfToken: "v16-fixture", access: { isAdmin: false, isMasterAdmin: false }, account: { id: "creator", email: "creator@example.test", displayName: "Creator", username: null, avatarUrl: null, providers: ["email"], role: "user", adminLevel: "none", status: "active", emailVerified: true, createdAt: "2026-08-29T00:00:00.000Z", lastLoginAt: null, source: "test" } }; }
function mediaSvg(name) { return `<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="900"><rect width="1440" height="900" fill="#080906"/><circle cx="350" cy="420" r="280" fill="${name.includes("gamma") ? "#0D6F73" : "#4D0913"}"/></svg>`; }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function addConsent(context) { const now = Date.now(); await context.addCookies([{ name: "thirdrailify_consent", value: encodeURIComponent(JSON.stringify({ version: 1, timestamp: new Date(now).toISOString(), expiry: new Date(now + 2_592_000_000).toISOString(), categories: { preferences: false, externalMedia: false } })), domain: "127.0.0.1", path: "/" }]); }
async function waitForPreview() { for (let attempt = 0; attempt < 80; attempt += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Public preview did not start."); }
async function waitFor(predicate) { for (let attempt = 0; attempt < 80; attempt += 1) { if (predicate()) return; await new Promise((resolve) => setTimeout(resolve, 50)); } throw new Error("Timed out waiting for fixture activity."); }
