import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4178";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";

test("Wheels directory, demo result, editor, and presentation are responsive and truthful", async (t) => {
  const artifacts = fileURLToPath(new URL("../.artifacts/wheels-v1/", import.meta.url)); await mkdir(artifacts, { recursive: true });
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4178"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForPreview();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close()); let writes = 0;
  const directoryMatrix = [{ width: 1920, height: 1080 }, { width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }];
  const wheelMatrix = [{ width: 1920, height: 1080 }, { width: 1440, height: 900 }, { width: 1365, height: 768 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }];
  const editorMatrix = [{ width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }];
  const presentationMatrix = [{ width: 1920, height: 1080 }, { width: 1280, height: 720 }, { width: 390, height: 844 }];
  for (const viewport of directoryMatrix) await withPage(browser, viewport, async (page) => { await page.goto(`${ORIGIN}/wheels`); await page.getByRole("heading", { level: 1, name: /SPIN THE/i }).waitFor(); await page.getByRole("link", { name: /Third Railify Demo Draw/i }).waitFor(); await assertPage(page, viewport.width); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/public-directory-desktop.png`, fullPage: true }); }, () => { writes += 1; });
  for (const viewport of wheelMatrix) await withPage(browser, viewport, async (page) => {
    await page.goto(`${ORIGIN}/wheels/third-railify-demo-draw`); await page.getByRole("heading", { level: 1, name: "Third Railify Demo Draw" }).waitFor(); assert.equal(await page.locator("canvas").count(), 1); const box = await page.locator(".wheel-stage").boundingBox(); assert.ok(box && Math.abs(box.width - box.height) < 1); await assertPage(page, viewport.width); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/public-wheel-before-spin-desktop.png`, fullPage: true }); if (viewport.width === 390) await page.screenshot({ path: `${artifacts}/public-wheel-before-spin-mobile.png`, fullPage: true });
    if (viewport.width === 1440 || viewport.width === 390) { const writesBeforeDemo = writes; await page.getByRole("button", { name: "Start demo spin" }).click(); await page.getByRole("dialog").waitFor(); await page.getByText("Demo result — not recorded as an official draw").waitFor(); assert.equal(await page.locator(".winner-confetti i").count(), 36); assert.equal(writes, writesBeforeDemo, "a demo spin performs no API write"); await assertPage(page, viewport.width); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/public-demo-winner-desktop.png`, fullPage: true }); await page.getByRole("button", { name: "Close result" }).click(); }
    if (viewport.width === 1440) { const writesBeforeOfficial = writes; await page.getByRole("button", { name: "Official draw" }).click(); await page.getByRole("button", { name: "Start recorded official draw" }).click(); await page.getByRole("dialog").waitFor(); await page.getByText(/selected and persisted by the Third Railify authority/i).waitFor(); assert.equal(writes, writesBeforeOfficial + 1, "an official draw performs exactly one authenticated write"); await page.getByRole("button", { name: "Close result" }).click(); }
  }, () => { writes += 1; });
  for (const viewport of editorMatrix) await withPage(browser, viewport, async (page) => { await page.goto(`${ORIGIN}/wheels/third-railify-demo-draw/edit`); await page.getByRole("heading", { level: 1, name: /Edit Third Railify Demo Draw/i }).waitFor(); await page.getByLabel("Wheel title").waitFor(); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/public-approved-editor-desktop.png`, fullPage: true }); if (viewport.width === 390) { const writesBeforeSave = writes; await page.getByLabel("Wheel title").fill("Third Railify Demo Draw Revised"); await page.getByRole("button", { name: "Save changes" }).click(); await page.getByText("Authoritative wheel revision saved.").waitFor(); assert.equal(writes, writesBeforeSave + 1); } await assertPage(page, viewport.width); }, () => { writes += 1; });
  for (const viewport of presentationMatrix) await withPage(browser, viewport, async (page) => { await page.goto(`${ORIGIN}/wheels/third-railify-demo-draw/present`); await page.getByRole("heading", { level: 1, name: /presentation/i }).waitFor(); await page.getByRole("link", { name: "Exit presentation mode" }).waitFor(); await assertPage(page, viewport.width); if (viewport.width === 1920) await page.screenshot({ path: `${artifacts}/public-presentation-desktop.png`, fullPage: true }); }, () => { writes += 1; });
});

async function withPage(browser, viewport, action, onWrite) { const context = await browser.newContext({ viewport, reducedMotion: "reduce" }); const page = await context.newPage(); const errors = []; page.on("console", (entry) => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("pageerror", (error) => errors.push(error.message)); await page.route("**/api/**", async (route) => respond(route, onWrite)); try { await action(page); assert.deepEqual(errors, []); } finally { await context.close(); } }

async function respond(route, onWrite) { const url = new URL(route.request().url()); const method = route.request().method(); if (method !== "GET") onWrite(); if (url.pathname === "/api/auth/config") return json(route, authConfig()); if (url.pathname === "/api/auth/session") return json(route, session()); if (url.pathname === "/api/wheels/access") return json(route, { ok: true, authenticated: true, canCreate: true, isMasterAdmin: false, maximumOwnedWheels: 20 }); if (url.pathname === "/api/wheels") { if (method === "POST") return json(route, wheelPayload()); return json(route, { ok: true, items: [summary()], count: 1 }); } if (url.pathname === "/api/wheels/third-railify-demo-draw/spins" && method === "POST") return json(route, { ok: true, spin: { id: "spin-fixture", winningEntryId: "10000000-0000-4000-8000-000000000003", winningLabel: "Demo GOAT 03", createdAt: "2026-08-29T00:00:00.000Z" }, idempotent: false }); if (url.pathname === "/api/wheels/third-railify-demo-draw") { if (method === "PUT") { const body = JSON.parse(route.request().postData() || "{}"); return json(route, wheelPayload({ title: body.title, revision: 8 })); } return json(route, wheelPayload()); } return json(route, { ok: true }); }
function summary() { return { slug: "third-railify-demo-draw", title: "Third Railify Demo Draw", description: "Synthetic browser fixture", participantCount: 8, weighted: true, themePreset: "third-rail-gold", palette: ["#F3C928", "#B8182F", "#F3F0E5", "#5B2C83"], demoEnabled: true, officialEnabled: true, latestOfficialAt: null }; }
function wheelPayload(overrides = {}) { const entries = Array.from({ length: 8 }, (_, index) => ({ id: `10000000-0000-4000-8000-00000000000${index + 1}`, label: `Demo GOAT 0${index + 1}`, order: index, weight: index === 2 ? 2 : 1, colour: ["#F3C928", "#B8182F", "#F3F0E5", "#5B2C83"][index % 4], state: "active" })); return { ok: true, wheel: { slug: "third-railify-demo-draw", title: "Third Railify Demo Draw", description: "Synthetic browser fixture", lifecycle: "active", visibility: "public", participantCount: 8, weighted: true, entries, config: { themePreset: "third-rail-gold", palette: ["#F3C928", "#B8182F", "#F3F0E5", "#5B2C83"], pointerAccent: "#F3C928", centreTreatment: "bolt", backgroundIntensity: "high", labelContrast: "light", spinDurationMs: 2000, tickingSoundEnabled: false, winnerSoundEnabled: false, celebrationIntensity: "full", winnerMessageTemplate: "Signal locked: {winner}", publicHistoryVisible: true }, demoEnabled: true, officialEnabled: true, latestOfficialResult: null, recentOfficialResults: [], revision: overrides.revision || 7, ...overrides }, access: { role: "editor", isMasterAdmin: false, canEdit: true, canSpinOfficially: true, editingLocked: false, officialSpinLocked: false, revision: overrides.revision || 7 } }; }
function authConfig() { return { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: ORIGIN, adminOrigin: "https://thirdrailify-admin.pages.dev", environment: "test", cookieMode: "host-only" }; }
function session() { return { ok: true, authenticated: true, csrfToken: "wheel-browser-csrf", access: { isAdmin: false, isMasterAdmin: false }, account: { id: "creator", email: "creator@example.test", displayName: "Approved Creator", username: null, avatarUrl: null, providers: ["email"], role: "user", adminLevel: "none", status: "active", emailVerified: true, createdAt: "2026-08-29T00:00:00.000Z", lastLoginAt: null, source: "test" } }; }
async function assertPage(page, width) { assert.equal(await page.locator("h1").count(), 1, `${width}px has one H1`); const layout = await page.evaluate(() => ({ fits: document.documentElement.scrollWidth <= document.documentElement.clientWidth, scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth, offenders: [...document.querySelectorAll("*")].filter((element) => { const box = element.getBoundingClientRect(); return box.right > document.documentElement.clientWidth + 1 || box.left < -1; }).slice(0, 8).map((element) => ({ tag: element.tagName, className: element.className, box: element.getBoundingClientRect().toJSON() })) })); assert.equal(layout.fits, true, `${width}px has no horizontal overflow: ${JSON.stringify(layout)}`); }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function waitForPreview() { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Public preview did not start."); }
