import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4198"; const SLUG = "v18-render-fixture"; const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const GIF = twoFrameGif();

test("Wheels V1.8 patterns, radial media, animated GIF, tonal pointer, sounds, and responsive controls", async (t) => {
  const artifacts = fileURLToPath(new URL("../.artifacts/wheels-v18/", import.meta.url)); await mkdir(artifacts, { recursive: true });
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4198"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForPreview();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } }); await consent(context); const page = await context.newPage(); const errors = monitor(page); await instrumentAudio(page); await routes(page);
  await page.goto(`${ORIGIN}/wheels/${SLUG}`); await page.locator(".wheel-stage canvas").waitFor();
  const wheelCanvas = page.locator(".wheel-stage canvas").first(); const frameA = await canvasFingerprint(page); const redA = await canvasRedScore(page); await wheelCanvas.screenshot({ path: `${artifacts}/gif-frame-a-wheel.png` }); let frameB = frameA; let redB = redA; for (let attempt = 0; attempt < 24 && Math.abs(redB-redA) < 1000; attempt += 1) { await page.waitForTimeout(90); frameB = await canvasFingerprint(page); redB = await canvasRedScore(page); } assert.notEqual(frameA, frameB, "animated GIF changes actual Canvas pixels while idle"); assert.ok(Math.abs(redB-redA) >= 1000, JSON.stringify({ redA, redB })); await wheelCanvas.screenshot({ path: `${artifacts}/gif-frame-b-wheel.png` });
  await page.getByRole("button", { name: "Start demo spin" }).click(); await page.waitForTimeout(180); const spinA = await canvasFingerprint(page); await page.waitForTimeout(115); const spinB = await canvasFingerprint(page); assert.notEqual(spinA, spinB, "GIF sampling remains active while rotor spins");
  const timersBeforeExit = await page.evaluate(() => window.__v18IntervalState?.active || 0); await page.getByRole("link", { name: /Back to wheels/i }).click(); await page.waitForURL(`${ORIGIN}/wheels`); await page.waitForTimeout(120); const timersAfterExit = await page.evaluate(() => window.__v18IntervalState?.active || 0); assert.ok(timersBeforeExit >= 1); assert.equal(timersAfterExit, 0, "GIF ticker stops on route exit"); assert.ok(await page.evaluate(() => window.__v18AudioState.closed >= 1), "route exit closes wheel audio");

  await page.goto(`${ORIGIN}/wheels/${SLUG}`); await page.getByRole("button", { name: "Turn wheel sound off" }).click(); const mutedAudio = await page.evaluate(() => window.__v18Audio.length); await page.getByRole("button", { name: "Start demo spin" }).click(); await page.waitForTimeout(180); assert.equal(await page.evaluate(() => window.__v18Audio.length), mutedAudio, "global Sound off suppresses the selected spin preset"); await page.goto(`${ORIGIN}/wheels`);

  await openAppearance(page); const dialog = page.getByRole("dialog", { name: /Tune the broadcast stage/i }); await dialog.getByRole("button", { name: /High Voltage Hazard/i }).click(); await page.screenshot({ path: `${artifacts}/patterned-preset.png` });
  const patterned = await dialog.locator(".appearance-preview canvas").evaluate((canvas) => { const ctx = canvas.getContext("2d"); const data = ctx.getImageData(0,0,canvas.width,canvas.height).data; return new Set(Array.from({ length: Math.floor(data.length / 64) }, (_, index) => `${data[index*64]},${data[index*64+1]},${data[index*64+2]}`)).size; }); assert.ok(patterned > 20);

  const customPatterns = [
    { base: "#B8182F", pattern: "zigzag", alternate: "#FF8EA0" },
    { base: "#FFFFFF", pattern: "dots", alternate: "#808080" },
    { base: "#16845A", pattern: "triangles", alternate: "#6B4423" },
    { base: "#184D9A", pattern: "third-rail-bolts", alternate: "#FFFFFF" },
  ];
  for (const [index, style] of customPatterns.entries()) await editPattern(dialog, page, index, style);
  await page.screenshot({ path: `${artifacts}/four-custom-vector-patterns.png` });
  assert.ok(await dialog.locator(".custom-palette-card .segment-style-preview.is-pattern").count() >= 4);
  await dialog.locator(".entrant-colours article .segment-style-action").first().click(); let entrantStyle = page.getByRole("dialog", { name: "Segment style" }); await page.screenshot({ path: `${artifacts}/participant-style-editor.png` }); await entrantStyle.getByRole("radio", { name: "pattern", exact: true }).check(); await entrantStyle.getByLabel(/Pattern for Entrant 1/i).selectOption("waves"); await entrantStyle.getByRole("button", { name: "Apply style" }).click(); await page.screenshot({ path: `${artifacts}/participant-pattern-override.png` });

  const fixtureFiles = await imageFixtures(page);
  for (let index = 0; index < 4; index += 1) { await dialog.locator(".custom-palette-card .segment-style-action").nth(index).click(); const style = page.getByRole("dialog", { name: "Segment style" }); await style.getByLabel(new RegExp(`Upload segment image for Custom palette style ${index + 1}`)).setInputFiles(fixtureFiles[index]); await style.getByRole("button", { name: "Apply style" }).click(); }
  await page.screenshot({ path: `${artifacts}/four-format-radial-image-fills.png` }); const imageSlots = await dialog.locator(".custom-palette-card .segment-style-preview.is-image").count(); assert.ok(imageSlots >= 4);
  await dialog.locator(".entrant-colours article .segment-style-action").first().click(); entrantStyle = page.getByRole("dialog", { name: "Segment style" }); await entrantStyle.getByLabel(/Upload segment image for Entrant 1/i).setInputFiles({ name: "animated-two-frame.gif", mimeType: "image/gif", buffer: GIF }); await entrantStyle.getByRole("button", { name: "Apply style" }).click(); await page.screenshot({ path: `${artifacts}/participant-gif-override.png` });

  for (const [name, colour] of [["gold","#F3C928"],["crimson","#B8182F"],["green","#16845A"],["violet","#6D3A93"]]) { await dialog.getByLabel("Wheel accent hex colour").fill(colour); const computed = await dialog.locator(".wheel-stage").evaluate((node) => ({ base: getComputedStyle(node).getPropertyValue("--pointer").trim(), light: getComputedStyle(node).getPropertyValue("--pointer-light").trim(), pointer: getComputedStyle(node.querySelector(".wheel-stage__pointer-blade")).backgroundImage })); assert.equal(computed.base, colour); assert.ok(!computed.pointer.includes("rgb(255, 255, 255)"), computed.pointer); await page.screenshot({ path: `${artifacts}/pointer-${name}.png` }); }

  await dialog.getByLabel("Generated wheel ticks").uncheck(); assert.equal(await dialog.getByRole("button", { name: "Preview sound" }).first().isDisabled(), true); await dialog.getByLabel("Generated wheel ticks").check(); const spinProfiles = []; for (const id of ["classic-tick","relay-click","arc-pulse","mechanical-ratchet"]) { await dialog.getByLabel("Spin sound preset").selectOption(id); await dialog.getByRole("button", { name: "Preview sound" }).first().click(); await page.waitForTimeout(30); spinProfiles.push(await page.evaluate(() => window.__v18Audio.at(-1))); } assert.equal(new Set(spinProfiles.map(JSON.stringify)).size, 4);
  await dialog.getByRole("tab", { name: "celebration" }).click(); const winnerProfiles = []; for (const id of ["gold-rise","broadcast-hit","voltage-chime","crimson-impact"]) { await dialog.getByLabel("Winner sound preset").selectOption(id); await dialog.getByRole("button", { name: "Preview sound" }).first().click(); await page.waitForTimeout(30); winnerProfiles.push(await page.evaluate(() => window.__v18Audio.at(-1))); } assert.equal(new Set(winnerProfiles.map(JSON.stringify)).size, 4); await dialog.getByLabel("Winner music stinger").uncheck(); assert.equal(await dialog.getByRole("button", { name: "Preview sound" }).first().isDisabled(), true); await dialog.getByLabel("Winner music stinger").check(); await dialog.getByLabel("Winner sound preset").selectOption("silent"); assert.equal(await dialog.getByRole("button", { name: "Preview sound" }).first().isDisabled(), true); await page.waitForTimeout(1750); assert.equal(await page.evaluate(() => window.__v18AudioState.closed), await page.evaluate(() => window.__v18AudioState.contexts), "preview audio contexts close without accumulating"); await page.screenshot({ path: `${artifacts}/sound-presets.png` });
  await page.screenshot({ path: `${artifacts}/sound-controls-and-image-preview.png` });
  await page.getByRole("button", { name: "Close appearance without saving" }).click(); await page.goto(`${ORIGIN}/wheels/${SLUG}/present`); await page.locator(".wheel-presentation-layout canvas").waitFor(); await page.screenshot({ path: `${artifacts}/presentation-pattern-and-image-wheel.png` });
  assert.deepEqual(errors, []); await context.close();

  for (const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:768,height:1024},{width:390,height:844}]) { const responsive = await browser.newContext({ viewport }); await consent(responsive); const candidate = await responsive.newPage(); await routes(candidate); await openAppearance(candidate); const geometry = await candidate.evaluate(() => ({ doc: document.documentElement.scrollWidth-document.documentElement.clientWidth, dialog: document.querySelector(".appearance-dialog").scrollWidth-document.querySelector(".appearance-dialog").clientWidth, circular: Math.abs(document.querySelector(".appearance-preview canvas").getBoundingClientRect().width-document.querySelector(".appearance-preview canvas").getBoundingClientRect().height), pointer: document.querySelector(".wheel-stage__pointer").getBoundingClientRect().top >= 0 })); assert.ok(geometry.doc <= 1 && geometry.dialog <= 1 && geometry.circular <= 1 && geometry.pointer, JSON.stringify({ viewport, geometry })); await candidate.screenshot({ path: `${artifacts}/appearance-${viewport.width}x${viewport.height}.png` }); if (viewport.width === 768 || viewport.width === 390) { await candidate.locator(".custom-palette-card .segment-style-action").first().click(); const segmentDialog = candidate.getByRole("dialog", { name: "Segment style" }); const styleGeometry = await segmentDialog.evaluate((node) => ({ horizontal: node.scrollWidth-node.clientWidth, bounds: node.getBoundingClientRect().toJSON() })); assert.ok(styleGeometry.horizontal <= 1 && styleGeometry.bounds.left >= 0 && styleGeometry.bounds.right <= viewport.width + 1, JSON.stringify({ viewport, styleGeometry })); assert.equal(await segmentDialog.locator(".segment-style-preview img").evaluate((image) => image.complete && image.naturalWidth > 0), true, "the projected GIF thumbnail decodes"); await candidate.screenshot({ path: `${artifacts}/segment-style-${viewport.width}x${viewport.height}.png` }); } await responsive.close(); }
});

async function openAppearance(page) { await page.goto(`${ORIGIN}/wheels/${SLUG}/edit`); const editor = page.getByRole("dialog", { name: /Edit V1.8 Render Fixture/i }); await editor.waitFor(); await editor.getByRole("tab", { name: "appearance" }).click(); await editor.getByRole("button", { name: "Customize appearance" }).click(); await page.getByRole("dialog", { name: /Tune the broadcast stage/i }).waitFor(); }
async function editPattern(dialog, page, index, value) { await dialog.locator(".custom-palette-card .segment-style-action").nth(index).click(); const style = page.getByRole("dialog", { name: "Segment style" }); await style.getByRole("radio", { name: "pattern", exact: true }).check(); await style.getByLabel(`Base colour hex for Custom palette style ${index + 1}`).fill(value.base); await style.getByLabel(`Pattern for Custom palette style ${index + 1}`).selectOption(value.pattern); await style.getByLabel(`Pattern colour hex for Custom palette style ${index + 1}`).fill(value.alternate); await style.getByRole("button", { name: "Apply style" }).click(); }
async function canvasFingerprint(page) { return page.locator(".wheel-stage canvas").first().evaluate((canvas) => { const context=canvas.getContext("2d");const image=context.getImageData(Math.floor(canvas.width*.52),Math.floor(canvas.height*.1),Math.floor(canvas.width*.38),Math.floor(canvas.height*.4));const data=image.data;let hash=2166136261;for(let index=0;index<data.length;index+=13){hash^=data[index];hash=Math.imul(hash,16777619);}return String(hash>>>0); }); }
async function canvasRedScore(page) { return page.locator(".wheel-stage canvas").first().evaluate((canvas) => { const context=canvas.getContext("2d");const image=context.getImageData(Math.floor(canvas.width*.52),Math.floor(canvas.height*.1),Math.floor(canvas.width*.38),Math.floor(canvas.height*.4)).data;let score=0;for(let index=0;index<image.length;index+=4)if(image[index]>90&&image[index]>image[index+1]*1.3&&image[index]>image[index+2]*1.15)score+=1;return score; }); }
async function imageFixtures(page) { const encoded = await page.evaluate(() => { const canvas=document.createElement("canvas"); canvas.width=80;canvas.height=120;const ctx=canvas.getContext("2d");ctx.fillStyle="#B8182F";ctx.fillRect(0,0,80,120);ctx.fillStyle="#F3C928";ctx.beginPath();ctx.moveTo(40,5);ctx.lineTo(72,54);ctx.lineTo(52,54);ctx.lineTo(52,112);ctx.lineTo(28,112);ctx.lineTo(28,54);ctx.lineTo(8,54);ctx.closePath();ctx.fill();return { jpg:canvas.toDataURL("image/jpeg",.9), webp:canvas.toDataURL("image/webp",.9) }; }); const decode=(url)=>Buffer.from(url.split(",")[1],"base64"); const svg=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 120"><rect width="80" height="120" fill="#0D6F73"/><path d="M40 4 72 54H52v62H28V54H8Z" fill="#F3F0E5"/></svg>'); return [{name:"orientation.jpg",mimeType:"image/jpeg",buffer:decode(encoded.jpg)},{name:"orientation.svg",mimeType:"image/svg+xml",buffer:svg},{name:"orientation.bmp",mimeType:"image/bmp",buffer:bmp(80,120)},{name:"orientation.webp",mimeType:"image/webp",buffer:decode(encoded.webp)}]; }
function bmp(width,height){const row=Math.ceil(width*3/4)*4;const bytes=Buffer.alloc(54+row*height);bytes.write("BM");bytes.writeUInt32LE(bytes.length,2);bytes.writeUInt32LE(54,10);bytes.writeUInt32LE(40,14);bytes.writeInt32LE(width,18);bytes.writeInt32LE(height,22);bytes.writeUInt16LE(1,26);bytes.writeUInt16LE(24,28);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const p=54+y*row+x*3;const arrow=x>width*.35&&x<width*.65||y>height*.42&&Math.abs(x-width/2)<(height-y)*.32;bytes[p]=arrow?40:47;bytes[p+1]=arrow?201:24;bytes[p+2]=arrow?243:184;}return bytes;}
function twoFrameGif(){return Buffer.from([0x47,0x49,0x46,0x38,0x39,0x61,1,0,1,0,0x80,0,0,0x18,0x18,0x18,0xff,0x35,0x55,0x21,0xff,0x0b,...Buffer.from("NETSCAPE2.0"),3,1,0,0,0,0x21,0xf9,4,0,100,0,0,0,0x2c,0,0,0,0,1,0,1,0,0,2,2,0x44,1,0,0x21,0xf9,4,0,100,0,0,0,0x2c,0,0,0,0,1,0,1,0,0,2,2,0x4c,1,0,0x3b]);}
async function instrumentAudio(page){await page.addInitScript(()=>{window.__v18Audio=[];window.__v18AudioState={contexts:0,closed:0};const Native=window.AudioContext||window.webkitAudioContext;if(Native){window.AudioContext=class extends Native{constructor(...args){super(...args);this.__items=[];window.__v18AudioState.contexts+=1;}createOscillator(){const node=super.createOscillator();const start=node.start.bind(node);node.start=(...args)=>{this.__items.push({type:node.type,frequency:Math.round(node.frequency.value),detune:Math.round(node.detune.value)});window.__v18Audio.push([...this.__items]);return start(...args);};return node;}close(){window.__v18AudioState.closed+=1;return super.close();}};}const nativeSet=window.setInterval.bind(window),nativeClear=window.clearInterval.bind(window);const ids=new Set();window.__v18IntervalState={active:0};window.setInterval=(fn,ms,...args)=>{const id=nativeSet(fn,ms,...args);ids.add(id);window.__v18IntervalState.active=ids.size;return id;};window.clearInterval=(id)=>{ids.delete(id);window.__v18IntervalState.active=ids.size;return nativeClear(id);};});}
async function routes(page){await page.route("**/api/**",respond);await page.route("**/api/wheels/media/**",route=>route.fulfill({status:200,contentType:"image/gif",body:GIF}));}
async function respond(route){const url=new URL(route.request().url());if(url.pathname==="/api/auth/config")return json(route,{configured:true,emailSignupConfigured:false,turnstileSiteKey:null,oauthProviders:[],oauthProviderStates:[],publicOrigin:ORIGIN,adminOrigin:ORIGIN,environment:"test",cookieMode:"host-only"});if(url.pathname==="/api/auth/session")return json(route,{ok:true,authenticated:true,csrfToken:"v18-fixture",access:{isAdmin:false,isMasterAdmin:false},account:{id:"creator",email:"creator@example.test",displayName:"Creator",avatarUrl:null,providers:["email"],role:"user",adminLevel:"none",status:"active",emailVerified:true,createdAt:"2026-08-30T00:00:00Z",source:"test"}});if(url.pathname==="/api/wheels")return json(route,{ok:true,items:[],count:0});if(url.pathname==="/api/wheels/access")return json(route,{ok:true,authenticated:true,canCreate:true,isMasterAdmin:false,maximumOwnedWheels:20});if(url.pathname===`/api/wheels/${SLUG}`)return json(route,payload());return json(route,{ok:true});}
function payload(){const entries=["Entrant 1","Entrant 2","Entrant 3","Entrant 4"].map((label,order)=>({id:`00000000-0000-4000-8000-00000000000${order+1}`,label,order,weight:1,colour:null,style:null,state:"active"}));return{ok:true,wheel:{slug:SLUG,title:"V1.8 Render Fixture",description:"Synthetic local visual acceptance",lifecycle:"active",visibility:"public",participantCount:4,weighted:false,entries,config:{themePreset:"custom",palette:["#181818","#B8182F","#0D6F73","#6D3A93"],paletteStyles:[{mode:"image",color:"#181818",imageAssetId:"11111111-1111-4111-8111-111111111111"},{mode:"pattern",color:"#B8182F",pattern:"zigzag",patternColor:"#FF8EA0"},{mode:"pattern",color:"#0D6F73",pattern:"triangles",patternColor:"#F3C928"},{mode:"pattern",color:"#6D3A93",pattern:"third-rail-bolts",patternColor:"#FFFFFF"}],pointerAccent:"#F3C928",centreTreatment:"bolt",backgroundIntensity:"high",labelContrast:"light",spinDurationMs:2000,tickingSoundEnabled:true,spinSoundPreset:"classic-tick",winnerSoundEnabled:true,winnerSoundPreset:"gold-rise",celebrationEnabled:true,confettiEnabled:true,fireworksEnabled:true,winnerLightingEnabled:true,celebrationIntensity:"normal",backgroundEnabled:true,backgroundFocalX:50,backgroundFocalY:50,backgroundImageOpacity:72,backgroundOverlayIntensity:58,winnerMessageTemplate:"Signal locked: {winner}",publicHistoryVisible:true},media:{background:null,centre:null,segmentFills:[{id:"11111111-1111-4111-8111-111111111111",purpose:"segment_fill",url:`${ORIGIN}/api/wheels/media/11111111-1111-4111-8111-111111111111`,contentType:"image/gif",byteSize:GIF.length,width:1,height:1,sha256:"fixture",fileName:"two-frame.gif",animationCapable:true,createdAt:"2026-08-30T00:00:00Z"}]},demoEnabled:true,officialEnabled:false,latestOfficialResult:null,recentOfficialResults:[],revision:18},access:{role:"editor",isMasterAdmin:false,canEdit:true,canSpinOfficially:false,editingLocked:false,officialSpinLocked:false,revision:18}};}
async function consent(context){const now=Date.now();await context.addCookies([{name:"thirdrailify_consent",value:encodeURIComponent(JSON.stringify({version:1,timestamp:new Date(now).toISOString(),expiry:new Date(now+2592000000).toISOString(),categories:{preferences:false,externalMedia:false}})),domain:"127.0.0.1",path:"/"}]);}
function monitor(page){const errors=[];page.on("console",entry=>{if(entry.type()==="error")errors.push(entry.text());});page.on("pageerror",error=>errors.push(error.message));return errors;}
function json(route,body,status=200){return route.fulfill({status,contentType:"application/json",body:JSON.stringify(body)});}
async function waitForPreview(){for(let attempt=0;attempt<80;attempt++){try{if((await fetch(ORIGIN)).ok)return;}catch{/* preview is still starting */}await new Promise(resolve=>setTimeout(resolve,100));}throw new Error("Public preview did not start.");}
