import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4193";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const SLUG = "third-railify-demo-draw";

test("Wheels V1.3 import/export is local, conversion-explicit, responsive, and permission-contained", async (t) => {
  const artifacts = fileURLToPath(new URL("../.artifacts/wheels-v13/", import.meta.url)); await mkdir(artifacts, { recursive: true });
  const sample = await readFile(new URL("./fixtures/wheel-of-names-sample.wheel", import.meta.url));
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4193"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForPreview();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "reduce", acceptDownloads: true }); await addConsent(context); const page = await context.newPage(); const errors = []; const writes = [];
  page.on("console", (entry) => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("pageerror", (error) => errors.push(error.message)); page.on("request", (request) => { const url = new URL(request.url()); if (url.pathname.startsWith("/api/wheels") && !new Set(["GET", "HEAD"]).has(request.method())) writes.push(`${request.method()} ${url.pathname}`); }); await page.route("**/api/**", respond);

  await page.goto(`${ORIGIN}/wheels/${SLUG}/edit`); await page.getByRole("dialog", { name: /Edit Third Railify Demo Draw/ }).waitFor(); await page.getByRole("button", { name: "Import / Export" }).click(); const transfer = page.getByRole("dialog", { name: "Import / Export" }); await transfer.waitFor(); await assertFits(page); const suspendedEditor = page.locator(".wheel-editor-backdrop"); assert.equal(await suspendedEditor.count(), 1, "editor DOM remains mounted while its focus trap is suspended"); assert.equal(await suspendedEditor.getAttribute("aria-hidden"), "true"); assert.equal(await suspendedEditor.isVisible(), false, "suspended editor is not visually stacked beneath import"); await page.screenshot({ path: `${artifacts}/desktop-import-export-dialog.png`, fullPage: false });

  await transfer.getByRole("tab", { name: "Export" }).click(); await transfer.getByText(".twl format v2").waitFor(); await transfer.getByRole("button", { name: "Download .twl" }).waitFor(); await transfer.getByRole("button", { name: "Download JSON" }).waitFor(); await transfer.getByRole("button", { name: "Copy JSON" }).waitFor(); await transfer.getByText("Include custom background, centre, and referenced segment images").waitFor(); await page.screenshot({ path: `${artifacts}/twl-export-panel.png`, fullPage: false });
  const downloadEvent = page.waitForEvent("download"); await transfer.getByRole("button", { name: "Download .twl" }).click(); const download = await downloadEvent; assert.equal(download.suggestedFilename(), "Third-Railify-Demo-Draw.twl");

  await transfer.getByRole("tab", { name: "Import" }).click(); await transfer.getByLabel("Choose file").setInputFiles({ name: "misleading.json", mimeType: "application/json", buffer: sample }); await transfer.getByRole("heading", { name: "Wheel of Names" }).waitFor(); assert.match(await transfer.textContent(), /Participants\s*8/); assert.match(await transfer.textContent(), /WARNING/); assert.match(await transfer.textContent(), /drawShadow/); assert.match(await transfer.textContent(), /entry IDs are not trusted/i); await transfer.locator(".wheel-import-preview").scrollIntoViewIfNeeded(); await page.screenshot({ path: `${artifacts}/wheel-of-names-preview.png`, fullPage: false }); await transfer.locator(".wheel-conversion-report .is-warning").first().scrollIntoViewIfNeeded(); await page.screenshot({ path: `${artifacts}/conversion-warning-report.png`, fullPage: false });
  assert.deepEqual(writes, [], "preview and export perform no mutation request"); await transfer.getByRole("button", { name: "Review replacement" }).click(); const confirmation = transfer.locator(".wheel-replace-confirm"); await confirmation.getByText("Nothing is persisted until you press the editor’s existing Save action.").waitFor(); await confirmation.scrollIntoViewIfNeeded(); await page.screenshot({ path: `${artifacts}/replacement-confirmation.png`, fullPage: false }); await confirmation.getByRole("button", { name: "Load import into editor" }).click();
  const editor = page.getByRole("dialog", { name: /Edit WHEELOFNAMES/ }); await editor.waitFor(); assert.equal(await editor.getByLabel("Wheel title").inputValue(), "WHEELOFNAMES"); await editor.getByText("Unsaved changes").waitFor(); assert.deepEqual(writes, [], "loading into editor remains local"); await page.screenshot({ path: `${artifacts}/imported-dirty-editor.png`, fullPage: false });

  await page.goto(`${ORIGIN}/wheels/new`); await page.getByRole("heading", { level: 1, name: "Build a competition wheel" }).waitFor(); await page.getByRole("button", { name: "Import wheel" }).click(); const newTransfer = page.getByRole("dialog", { name: "Import / Export" }); await newTransfer.getByLabel("Choose file").setInputFiles({ name: "WHEELOFNAMES.wheel", mimeType: "application/json", buffer: sample }); await newTransfer.getByRole("heading", { name: "Wheel of Names" }).waitFor(); await newTransfer.getByRole("button", { name: "Use as new wheel" }).click(); assert.equal(await page.getByLabel("Wheel title").inputValue(), "WHEELOFNAMES"); await page.getByText("Unsaved changes", { exact: true }).waitFor(); assert.deepEqual(writes, [], "new-wheel import creates nothing before Create wheel"); await page.screenshot({ path: `${artifacts}/new-wheel-imported-dirty.png`, fullPage: true });

  await page.setViewportSize({ width: 390, height: 844 }); await page.goto(`${ORIGIN}/wheels/${SLUG}/edit`); await page.getByRole("dialog", { name: /Edit Third Railify Demo Draw/ }).waitFor(); await page.getByRole("button", { name: "Import / Export" }).click(); const mobile = page.getByRole("dialog", { name: "Import / Export" }); await mobile.getByLabel("Choose file").setInputFiles({ name: "WHEELOFNAMES.wheel", mimeType: "application/json", buffer: sample }); await mobile.getByRole("heading", { name: "Wheel of Names" }).waitFor(); await assertFits(page); const bounds = await mobile.boundingBox(); assert.ok(bounds && bounds.width <= 390 && bounds.height <= 844); await page.screenshot({ path: `${artifacts}/mobile-import-dialog.png`, fullPage: false });

  const spinnerContext = await browser.newContext({ viewport: { width: 1024, height: 768 }, reducedMotion: "reduce" }); await addConsent(spinnerContext); const spinnerPage = await spinnerContext.newPage(); await spinnerPage.route("**/api/**", async (route) => { const url = new URL(route.request().url()); if (url.pathname === `/api/wheels/${SLUG}`) { const payload = wheel(); payload.access = { role: "spinner", isMasterAdmin: false, canEdit: false, canSpinOfficially: true, editingLocked: false, officialSpinLocked: false, revision: 7 }; return json(route, payload); } return respond(route); }); await spinnerPage.goto(`${ORIGIN}/wheels/${SLUG}`); await spinnerPage.getByRole("heading", { level: 1, name: "Third Railify Demo Draw" }).waitFor(); assert.equal(await spinnerPage.getByRole("link", { name: "Edit" }).count(), 0); assert.equal(await spinnerPage.getByRole("button", { name: "Import / Export" }).count(), 0); await spinnerPage.goto(`${ORIGIN}/wheels/${SLUG}/edit`); await spinnerPage.getByRole("dialog", { name: "Editor access required" }).waitFor(); assert.equal(await spinnerPage.getByRole("button", { name: "Import / Export" }).count(), 0); await spinnerContext.close();

  assert.deepEqual(writes, [], "the complete acceptance flow made no mutation request"); assert.deepEqual(errors, []);
});

async function respond(route) { const url = new URL(route.request().url()); const method = route.request().method(); if (url.pathname === "/api/auth/config") return json(route, { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: ORIGIN, adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" }); if (url.pathname === "/api/auth/session") return json(route, session()); if (url.pathname === "/api/wheels/access") return json(route, { ok: true, authenticated: true, canCreate: true, isMasterAdmin: false, maximumOwnedWheels: 20 }); if (url.pathname === `/api/wheels/${SLUG}` && method === "GET") return json(route, wheel()); if (url.pathname === "/api/wheels" && method === "GET") return json(route, { ok: true, items: [], count: 0 }); return json(route, { ok: true }); }
function wheel() { const entries = Array.from({ length: 8 }, (_, index) => ({ id: `10000000-0000-4000-8000-00000000000${index + 1}`, label: `Demo GOAT 0${index + 1}`, order: index, weight: 1, colour: ["#F3C928", "#B8182F", "#F3F0E5", "#20201A"][index % 4], state: "active" })); return { ok: true, wheel: { slug: SLUG, title: "Third Railify Demo Draw", description: "Synthetic V1.3 browser fixture", lifecycle: "active", visibility: "public", participantCount: 8, weighted: false, entries, config: { themePreset: "third-rail-gold", palette: ["#F3C928", "#B8182F", "#F3F0E5", "#20201A"], pointerAccent: "#F3C928", centreTreatment: "bolt", backgroundIntensity: "high", labelContrast: "light", spinDurationMs: 6500, tickingSoundEnabled: true, winnerSoundEnabled: true, celebrationEnabled: true, confettiEnabled: true, winnerLightingEnabled: true, celebrationIntensity: "normal", backgroundEnabled: true, backgroundFocalX: 50, backgroundFocalY: 50, backgroundImageOpacity: 72, backgroundOverlayIntensity: 58, winnerMessageTemplate: "Signal locked: {winner}", publicHistoryVisible: true }, media: { background: null, centre: null }, demoEnabled: true, officialEnabled: true, latestOfficialResult: null, recentOfficialResults: [], revision: 7 }, access: { role: "editor", isMasterAdmin: false, canEdit: true, canSpinOfficially: true, editingLocked: false, officialSpinLocked: false, revision: 7 } }; }
function session() { return { ok: true, authenticated: true, csrfToken: "fixture-csrf", access: { isAdmin: false, isMasterAdmin: false }, account: { id: "creator", email: "creator@example.test", displayName: "Approved Creator", avatarUrl: null, providers: ["email"], role: "user", adminLevel: "none", status: "active", emailVerified: true, createdAt: "2026-08-29T00:00:00.000Z", source: "test" } }; }
async function addConsent(context) { const now = Date.now(); await context.addCookies([{ name: "thirdrailify_consent", value: encodeURIComponent(JSON.stringify({ version: 1, timestamp: new Date(now).toISOString(), expiry: new Date(now + 2_592_000_000).toISOString(), categories: { preferences: false, externalMedia: false } })), domain: "127.0.0.1", path: "/" }]); }
async function assertFits(page) { const value = await page.evaluate(() => ({ fits: document.documentElement.scrollWidth <= document.documentElement.clientWidth, scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth })); assert.equal(value.fits, true, JSON.stringify(value)); }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function waitForPreview() { for (let attempt = 0; attempt < 80; attempt += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Public preview did not start."); }
