import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import { ArrowIcon, BagIcon } from "../components/Icons";
import { CurrencyDisclaimer, CurrencySelect, ProductPrice } from "../components/CurrencyPrice";
import { ProductCard } from "../components/ProductCard";
import { catalogueProvider, categorySlug } from "../lib/catalogueProvider";
import { useCart } from "../store/cart";
import type { CatalogueProduct } from "../types/catalogue";

export function ProductDetailPage() {
  const { slug = "" } = useParams(); const location = useLocation(); const cart = useCart();
  const [product, setProduct] = useState<CatalogueProduct | null>(null); const [products, setProducts] = useState<CatalogueProduct[]>([]);
  const [variantId, setVariantId] = useState(""); const [quantity, setQuantity] = useState(1); const [imageFailed, setImageFailed] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); Promise.all([catalogueProvider.loadProduct(slug, controller.signal), catalogueProvider.load(controller.signal)]).then(([next, snapshot]) => { setProduct(next); setProducts(snapshot.products); setVariantId(next.variants?.find((variant) => variant.availability === "active")?.id || next.variants?.[0]?.id || ""); }).catch((reason: unknown) => { if (reason instanceof DOMException && reason.name === "AbortError") return; setError(reason instanceof Error && reason.message === "product_not_found" ? "not_found" : "unavailable"); }).finally(() => setLoading(false)); return () => controller.abort(); }, [slug]);
  useEffect(() => { setImageFailed(false); setQuantity(1); window.scrollTo({ top: 0, behavior: "auto" }); }, [slug]);
  const variant = product?.variants?.find((entry) => entry.id === variantId) || null;
  const related = useMemo(() => product ? [...products].filter((entry) => entry.id !== product.id).sort((left, right) => { const leftShared = left.categories.some((entry) => product.categories.includes(entry)) ? 1 : 0; const rightShared = right.categories.some((entry) => product.categories.includes(entry)) ? 1 : 0; return rightShared - leftShared || Number(Boolean(right.featured)) - Number(Boolean(left.featured)) || left.slug.localeCompare(right.slug); }).slice(0, 3) : [], [product, products]);
  if (loading) return <section className="route-hero route-hero--center"><div className="container"><p className="eyebrow">Commerce catalogue</p><h1>Loading product…</h1></div></section>;
  if (!product || error) return <section className="route-hero route-hero--center"><div className="container"><p className="eyebrow">{error === "not_found" ? "Product unavailable" : "Shop unavailable"}</p><h1>{error === "not_found" ? "This product is not in the public catalogue." : "The shop catalogue could not be loaded."}</h1><p>Nothing has been substituted from the legacy store snapshot.</p><div className="button-row"><Link className="button button--primary" to={`/shop${location.search}${location.hash}`}>Back to the shop</Link><button className="button button--secondary" type="button" onClick={() => window.location.reload()}>Retry</button></div></div></section>;
  const selectedPrice = variant ? variant.unitAmount / 100 : product.price; const selectedPriceLabel = variant ? formatCad(variant.unitAmount) : product.formattedPrice;
  return <>
    <section className="product-detail product-detail--commerce"><div className="container product-detail__crumbs"><Link to={`/shop${location.search}`}>Shop</Link><span>/</span>{product.categories[0] ? <><Link to={`/products/${categorySlug(product.categories[0])}${location.search}`}>{product.categories[0]}</Link><span>/</span></> : null}<strong>{product.name}</strong></div>
      <div className="container product-detail__grid"><div className="product-media"><div className="product-media__stage">{!imageFailed && product.image ? <img src={product.image} alt={product.name} width="900" height="1125" onError={() => setImageFailed(true)} /> : <span className="product-image-fallback" role="img" aria-label={`${product.name} image unavailable`}>TR</span>}<span className="product-media__marker">Replacement store preview</span></div></div>
        <div className="product-detail__copy"><p className="eyebrow">{product.categories.join(" · ") || "Third Railify merchandise"}</p><h1>{product.name}</h1><ProductPrice price={selectedPrice} formattedPrice={selectedPriceLabel} prominent /><CurrencySelect /><CurrencyDisclaimer />
          {product.description ? <p className="product-detail__description">{product.description}</p> : <p className="product-detail__truth">Permanent product details are being prepared for cutover.</p>}
          {product.variants?.length ? <div className="commerce-variant-selector"><label htmlFor="product-variant">Choose variant</label><select id="product-variant" value={variantId} onChange={(event) => setVariantId(event.target.value)}>{product.variants.map((entry) => <option key={entry.id} value={entry.id} disabled={entry.availability !== "active"}>{entry.label} — {formatCad(entry.unitAmount)}{entry.availability !== "active" ? " — unavailable" : ""}</option>)}</select></div> : <p className="product-detail__truth">No public variant is currently available.</p>}
          <div className="commerce-quantity"><label htmlFor="product-quantity">Quantity</label><input id="product-quantity" type="number" min={1} max={product.maxQuantity || 20} value={quantity} onChange={(event) => setQuantity(Math.min(product.maxQuantity || 20, Math.max(1, Number(event.target.value) || 1)))} /></div>
          <div className="product-detail__actions"><button className="button button--primary" type="button" disabled={!variant || variant.availability !== "active"} onClick={() => variant && cart.add(product, variant, quantity)}><BagIcon /> Add selected variant</button><Link className="button button--secondary" to="/shop">Continue shopping <ArrowIcon /></Link></div>
          <details className="product-disclosure"><summary>Checkout status</summary><p>The cart stores local product and variant identities only. Prices are displayed from Commerce D1 and will be revalidated server-side. Checkout is coming online during the store migration.</p></details>
          <aside className="product-goats-cta" aria-labelledby="product-goats-title"><div>{!imageFailed && product.image ? <img src={product.image} alt="" width="92" height="92" /> : <span aria-hidden="true">GOAT</span>}</div><p><small>GOATS in the Wild</small><strong id="product-goats-title">Already own this product?</strong><span>Show us your GOATED drip and join the approved community showcase.</span></p><Link className="text-link" to={`/goats/submit?product=${encodeURIComponent(product.id)}`}>Submit your photos <ArrowIcon /></Link></aside>
        </div></div>
    </section>
    {related.length ? <section className="section related-products" aria-labelledby="related-products-title"><div className="container catalogue-heading"><div><p className="eyebrow">Same signal, different artifact</p><h2 id="related-products-title">Related products.</h2></div><Link className="text-link" to={`/shop${location.search}`}>Browse the complete store <ArrowIcon /></Link></div><div className="container product-grid product-grid--related">{related.map((entry, index) => <ProductCard key={entry.id} product={entry} index={index} />)}</div></section> : null}
  </>;
}

function formatCad(unitAmount: number) { return new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" }).format(unitAmount / 100); }
