import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowIcon, BagIcon, SearchIcon } from "../components/Icons";
import { ProductCard } from "../components/ProductCard";
import { ProductPrice } from "../components/CurrencyPrice";
import { SignalField } from "../components/SignalField";
import { catalogueProvider, categorySlug } from "../lib/catalogueProvider";
import { useCart } from "../store/cart";
import type { CatalogueProduct, CatalogueSnapshot } from "../types/catalogue";

type SortMode = "featured" | "price-asc" | "price-desc" | "name";

export function ShopPage() {
  const { category = "all-products" } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [searchParams, setSearchParams] = useSearchParams(); const cart = useCart();
  const galleryHeading = useRef<HTMLHeadingElement>(null); const [snapshot, setSnapshot] = useState<CatalogueSnapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const query = searchParams.get("q") || ""; const rawSort = searchParams.get("sort"); const sort: SortMode = rawSort === "price-asc" || rawSort === "price-desc" || rawSort === "name" ? rawSort : "featured";
  const load = useCallback(() => { const controller = new AbortController(); setLoading(true); setError(""); catalogueProvider.load(controller.signal).then(setSnapshot).catch((reason: unknown) => { if (reason instanceof DOMException && reason.name === "AbortError") return; setError("The commerce catalogue could not be loaded."); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  useEffect(load, [load]);
  const activeCategory = category === "all" ? "all-products" : categorySlug(category);
  const allProducts = useMemo(() => snapshot?.products ?? [], [snapshot]);
  const collections = useMemo(() => snapshot?.collections ?? [], [snapshot]);
  const catalogueCollections = useMemo(() => [{ title: "All Products", slug: "all-products" }, ...collections], [collections]);
  const products = useMemo(() => { const needle = query.trim().toLowerCase(); const next = allProducts.filter((product) => { const slugs = product.collectionSlugs || product.categories.map(categorySlug); const matchesCategory = activeCategory === "all-products" || slugs.includes(activeCategory); return matchesCategory && (!needle || `${product.name} ${product.categories.join(" ")} ${product.optionTypes.join(" ")}`.toLowerCase().includes(needle)); }); if (sort === "featured") next.sort(featuredCompare); if (sort === "price-asc") next.sort((a, b) => a.price - b.price || a.slug.localeCompare(b.slug)); if (sort === "price-desc") next.sort((a, b) => b.price - a.price || a.slug.localeCompare(b.slug)); if (sort === "name") next.sort((a, b) => a.name.localeCompare(b.name)); return next; }, [activeCategory, allProducts, query, sort]);
  const updateQuery = (key: string, value: string) => { const next = new URLSearchParams(searchParams); if (value) next.set(key, value); else next.delete(key); setSearchParams(next, { replace: true }); };
  const chooseCategory = (slug: string) => { navigate({ pathname: slug === "all-products" ? "/shop" : `/products/${slug}`, search: location.search, hash: location.hash }); window.requestAnimationFrame(() => { galleryHeading.current?.focus({ preventScroll: true }); document.getElementById("catalogue")?.scrollIntoView({ behavior: "smooth", block: "start" }); }); };
  const clearFilters = () => { setSearchParams(new URLSearchParams()); navigate({ pathname: "/shop", search: "", hash: location.hash }); };
  const filtersActive = activeCategory !== "all-products" || Boolean(query) || sort !== "featured";
  return <><FeaturedHero products={allProducts} cartCount={cart.count} openCart={cart.open} />
    <section className="collection-section collection-discovery" aria-labelledby="collections-title"><div className="container split-heading split-heading--compact"><div><p className="eyebrow">Find your line</p><h2 id="collections-title">Shop by collection.</h2></div><p>Explore collections managed by the authoritative commerce catalogue.</p></div><div className="container collection-grid">{collections.map((collection, index) => { const categoryProducts = allProducts.filter((product) => (product.collectionSlugs || product.categories.map(categorySlug)).includes(collection.slug)); return <button className="collection-card" key={collection.slug} type="button" onClick={() => chooseCategory(collection.slug)}><span className="collection-card__index">{String(index + 1).padStart(2, "0")}</span><span className="collection-card__images" aria-hidden="true">{categoryProducts.slice(0, 2).map((product) => product.image ? <img key={product.id} src={product.image} alt="" /> : null)}</span><span className="collection-card__copy"><strong>{collection.title}</strong>{collection.description ? <span>{collection.description}</span> : null}<small>{collection.productCount} {collection.productCount === 1 ? "product" : "products"}</small></span><ArrowIcon /></button>; })}</div></section>
    <section id="catalogue" className="section section--panel catalogue-section"><div className="container catalogue-heading"><div><p className="eyebrow">Commerce D1 catalogue</p><h2 ref={galleryHeading} tabIndex={-1}>The complete replacement drop.</h2></div><div><p>Browse real products and variants. All gallery prices use the authoritative CAD catalogue value.</p></div></div>
      <div className="shop-utility-wrap"><div className="container shop-toolbar shop-toolbar--commerce"><label className="search-field"><SearchIcon /><span className="sr-only">Search products</span><input value={query} onChange={(event) => updateQuery("q", event.target.value)} placeholder="Search products and collections…" /></label><label className="sort-field"><span>Sort</span><select value={sort} onChange={(event) => updateQuery("sort", event.target.value)}><option value="featured">Featured order</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="name">Name</option></select></label><div className="result-count" aria-live="polite"><strong>{loading ? "—" : products.length}</strong><span>results</span></div></div><div className="container filter-bar" aria-label="Catalogue filters">{catalogueCollections.map((collection) => <button key={collection.slug} className={collection.slug === activeCategory ? "is-active" : ""} type="button" onClick={() => chooseCategory(collection.slug)} aria-pressed={collection.slug === activeCategory}>{collection.title}</button>)}{filtersActive ? <button className="filter-clear" type="button" onClick={clearFilters}>Clear filters</button> : null}</div></div>
      <div className="container">{loading ? <LoadingGrid /> : null}{error ? <ErrorState message={error} retry={load} /> : null}{!loading && !error && products.length ? <div className="product-grid product-grid--store">{products.map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div> : null}{!loading && !error && !products.length ? <div className="empty-state empty-state--catalogue"><SearchIcon /><p className="eyebrow">No matches</p><h3>No products are on this section of rail.</h3><p>Try another category or clear the current search and sort controls.</p><button className="button button--secondary" type="button" onClick={clearFilters}>Clear filters</button></div> : null}</div>
    </section></>;
}

function FeaturedHero({ products, cartCount, openCart }: { products: CatalogueProduct[]; cartCount: number; openCart: () => void }) {
  const displayable = useMemo(() => products.filter((product) => product.image && Number.isFinite(product.price) && product.price >= 0), [products]);
  const featured = useMemo(() => { const explicit = displayable.filter((product) => product.featured).sort(featuredCompare); return explicit.length ? explicit : [...displayable].sort((a, b) => a.slug.localeCompare(b.slug)); }, [displayable]);
  const [activeIndex, setActiveIndex] = useState(0); const activeIndexRef = useRef(0); const [previousIndex, setPreviousIndex] = useState<number | null>(null); const transitionTimer = useRef<number | null>(null); const [paused, setPaused] = useState(false); const [engaged, setEngaged] = useState(false); const [reducedMotion, setReducedMotion] = useState(false);
  useEffect(() => { const media = window.matchMedia("(prefers-reduced-motion: reduce)"); const sync = () => setReducedMotion(media.matches); sync(); media.addEventListener("change", sync); return () => media.removeEventListener("change", sync); }, []);
  const showIndex = useCallback((requested: number) => { if (!featured.length) return; const next = (requested + featured.length) % featured.length; const current = activeIndexRef.current; if (next === current) return; if (transitionTimer.current !== null) window.clearTimeout(transitionTimer.current); if (!reducedMotion) { setPreviousIndex(current); transitionTimer.current = window.setTimeout(() => { setPreviousIndex(null); transitionTimer.current = null; }, 720); } else setPreviousIndex(null); activeIndexRef.current = next; setActiveIndex(next); }, [featured.length, reducedMotion]);
  useEffect(() => { if (featured.length <= 1 || paused || engaged || reducedMotion || document.hidden) return; const timer = window.setInterval(() => { if (!document.hidden) showIndex(activeIndexRef.current + 1); }, 7000); return () => window.clearInterval(timer); }, [engaged, featured.length, paused, reducedMotion, showIndex]);
  useEffect(() => { const next = Math.min(activeIndexRef.current, Math.max(0, featured.length - 1)); activeIndexRef.current = next; setActiveIndex(next); setPreviousIndex(null); }, [featured.length]);
  useEffect(() => () => { if (transitionTimer.current !== null) window.clearTimeout(transitionTimer.current); }, []);
  const active = featured[activeIndex]; const move = (offset: number) => showIndex(activeIndexRef.current + offset);
  return <section className="shop-hero shop-hero--drop" onPointerEnter={() => setEngaged(true)} onPointerLeave={() => setEngaged(false)} onFocusCapture={() => setEngaged(true)} onBlurCapture={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) setEngaged(false); }}><SignalField /><div className="shop-hero__type" aria-hidden="true"><span>WEAR THE LORE</span><span>WEAR THE LORE</span><span>WEAR THE LORE</span></div><div className="container shop-hero__grid"><div className="shop-hero__copy"><p className="eyebrow">The official store · Catalogue live</p><h1>Wear the<br /><span className="hero-feature-text">lore.</span></h1><p>Podcast merch with real catalogue variants and CAD pricing, with checkout held safely behind production gates.</p><div className="button-row"><a className="button button--primary" href="#catalogue">Browse the store <ArrowIcon /></a>{active ? <Link className="button button--secondary" to={`/shop/${active.slug}`}>Open featured product</Link> : <button className="button button--secondary" type="button" onClick={openCart}><BagIcon /> Cart · {cartCount}</button>}</div><div className="shop-facts"><span><strong>{products.length || "—"}</strong><small>Products</small></span><span><strong>{products.reduce((total, product) => total + (product.variants?.length || 0), 0) || "—"}</strong><small>Variants</small></span><span><strong>CAD</strong><small>D1 price authority</small></span></div></div><div className="featured-stage" aria-label="Featured products">{active ? <><div className="featured-stage__rails" aria-hidden="true" />{previousIndex !== null && featured[previousIndex] ? <FeaturedFrame products={featured} activeIndex={previousIndex} className="featured-stage__frame--exiting" /> : null}<FeaturedFrame products={featured} activeIndex={activeIndex} className={previousIndex !== null ? "featured-stage__frame--entering" : ""} />{featured.length > 1 && !reducedMotion ? <div className="featured-stage__controls"><button type="button" onClick={() => move(-1)} aria-label="Previous featured product">←</button><button type="button" onClick={() => setPaused((value) => !value)} aria-label={paused ? "Resume featured product rotation" : "Pause featured product rotation"}>{paused ? "Play" : "Pause"}</button><button type="button" onClick={() => move(1)} aria-label="Next featured product">→</button></div> : null}</> : <div className="featured-stage__empty">Commerce products are loading.</div>}</div></div></section>;
}

function FeaturedFrame({ products, activeIndex, className }: { products: CatalogueProduct[]; activeIndex: number; className: string }) {
  const active = products[activeIndex]; const support = products.filter((_, index) => index !== activeIndex).slice(0, 2); const exiting = className === "featured-stage__frame--exiting";
  return <div className={`featured-stage__frame${className ? ` ${className}` : ""}`} aria-hidden={exiting || undefined}><Link className="featured-stage__active" to={`/shop/${active.slug}`} tabIndex={exiting ? -1 : undefined}><img src={active.image} alt={active.name} width="720" height="900" /><span className="featured-stage__details"><small>Featured {String(activeIndex + 1).padStart(2, "0")} / {String(products.length).padStart(2, "0")}</small><strong>{active.name}</strong><ProductPrice price={active.price} formattedPrice={active.formattedPrice} /></span></Link>{support.map((product, index) => <Link className={`featured-stage__support featured-stage__support--${index + 1}`} key={product.id} to={`/shop/${product.slug}`} aria-label={`View ${product.name}`} tabIndex={exiting ? -1 : undefined}><img src={product.image} alt="" /></Link>)}</div>;
}

function featuredCompare(a: CatalogueProduct, b: CatalogueProduct) { if (a.featured !== b.featured) return a.featured ? -1 : 1; return (a.featuredOrder ?? Number.MAX_SAFE_INTEGER) - (b.featuredOrder ?? Number.MAX_SAFE_INTEGER) || (a.displayOrder ?? 1000) - (b.displayOrder ?? 1000) || a.slug.localeCompare(b.slug); }
function LoadingGrid() { return <div className="product-grid product-grid--store" aria-label="Loading products" aria-busy="true">{Array.from({ length: 8 }, (_, index) => <div className="product-skeleton" key={index}><span /><i /><i /></div>)}</div>; }
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="empty-state empty-state--error"><p className="eyebrow">Shop unavailable</p><h3>{message}</h3><p>The replacement shop does not fall back to legacy catalogue data.</p><button className="button button--secondary" type="button" onClick={retry}>Try again</button></div>; }
