import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useLocation, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowIcon, SearchIcon } from "../components/Icons";
import { ShopHero } from "../components/ShopHero";
import { ProductCard } from "../components/ProductCard";
import { catalogueProvider, categorySlug } from "../lib/catalogueProvider";
import { useCart } from "../store/cart";
import type { CatalogueProduct, CatalogueSnapshot } from "../types/catalogue";

type SortMode = "featured" | "price-asc" | "price-desc" | "name";

export function ShopPage() {
  const { category = "all-products" } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [searchParams, setSearchParams] = useSearchParams(); const cart = useCart();
  const galleryHeading = useRef<HTMLHeadingElement>(null); const [snapshot, setSnapshot] = useState<CatalogueSnapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const query = searchParams.get("q") || ""; const rawSort = searchParams.get("sort"); const sort: SortMode = rawSort === "price-asc" || rawSort === "price-desc" || rawSort === "name" ? rawSort : "featured";
  const load = useCallback(() => { const controller = new AbortController(); setLoading(true); setError(""); catalogueProvider.load(controller.signal).then(setSnapshot).catch((reason: unknown) => { if (reason instanceof DOMException && reason.name === "AbortError") return; setError("The commerce catalogue could not be loaded."); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  useEffect(load, [load]);
  const activeCategory = category === "all" ? "all-products" : categorySlug(category);
  const allProducts = useMemo(() => snapshot?.products ?? [], [snapshot]);
  const collections = useMemo(() => snapshot?.collections ?? [], [snapshot]);
  const catalogueCollections = useMemo(() => [{ title: "All Products", slug: "all-products" }, ...collections], [collections]);
  const products = useMemo(() => { const needle = query.trim().toLowerCase(); const next = allProducts.filter((product) => { const slugs = product.collectionSlugs || product.categories.map(categorySlug); const matchesCategory = activeCategory === "all-products" || slugs.includes(activeCategory); return matchesCategory && (!needle || `${product.name} ${product.categories.join(" ")} ${product.optionTypes.join(" ")}`.toLowerCase().includes(needle)); }); if (sort === "featured") next.sort(featuredCompare); if (sort === "price-asc") next.sort((a, b) => a.price - b.price || a.slug.localeCompare(b.slug)); if (sort === "price-desc") next.sort((a, b) => b.price - a.price || a.slug.localeCompare(b.slug)); if (sort === "name") next.sort((a, b) => a.name.localeCompare(b.name)); return next; }, [activeCategory, allProducts, query, sort]);
  const updateQuery = (key: string, value: string) => { const next = new URLSearchParams(searchParams); if (value) next.set(key, value); else next.delete(key); setSearchParams(next, { replace: true }); };
  const chooseCategory = (slug: string) => { navigate({ pathname: slug === "all-products" ? "/shop" : `/products/${slug}`, search: location.search, hash: location.hash }); window.requestAnimationFrame(() => { galleryHeading.current?.focus({ preventScroll: true }); document.getElementById("catalogue")?.scrollIntoView({ behavior: "smooth", block: "start" }); }); };
  const clearFilters = () => { setSearchParams(new URLSearchParams()); navigate({ pathname: "/shop", search: "", hash: location.hash }); };
  const filtersActive = activeCategory !== "all-products" || Boolean(query) || sort !== "featured";
  return <><ShopHero products={allProducts} cartCount={cart.count} openCart={cart.open} loading={loading} error={Boolean(error)} />
    <section className="collection-section collection-discovery" aria-labelledby="collections-title"><div className="container split-heading split-heading--compact"><div><p className="eyebrow">Find your line</p><h2 id="collections-title">Shop by collection.</h2></div><p>Explore collections managed by the authoritative commerce catalogue.</p></div><div className="container collection-grid">{collections.map((collection, index) => { const categoryProducts = allProducts.filter((product) => (product.collectionSlugs || product.categories.map(categorySlug)).includes(collection.slug)); return <button className="collection-card" key={collection.slug} type="button" onClick={() => chooseCategory(collection.slug)}><span className="collection-card__index">{String(index + 1).padStart(2, "0")}</span><span className="collection-card__images" aria-hidden="true">{categoryProducts.slice(0, 2).map((product) => product.image ? <img key={product.id} src={product.image} alt="" /> : null)}</span><span className="collection-card__copy"><strong>{collection.title}</strong>{collection.description ? <span>{collection.description}</span> : null}<small>{collection.productCount} {collection.productCount === 1 ? "product" : "products"}</small></span><ArrowIcon /></button>; })}</div></section>
    <section id="catalogue" className="section section--panel catalogue-section"><div className="container catalogue-heading"><div><p className="eyebrow">Commerce D1 catalogue</p><h2 ref={galleryHeading} tabIndex={-1}>The complete replacement drop.</h2></div><div><p>Browse real products and variants. All gallery prices use the authoritative CAD catalogue value.</p></div></div>
      <div className="shop-utility-wrap"><div className="container shop-toolbar shop-toolbar--commerce"><label className="search-field"><SearchIcon /><span className="sr-only">Search products</span><input value={query} onChange={(event) => updateQuery("q", event.target.value)} placeholder="Search products and collections…" /></label><label className="sort-field"><span>Sort</span><select value={sort} onChange={(event) => updateQuery("sort", event.target.value)}><option value="featured">Featured order</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="name">Name</option></select></label><div className="result-count" aria-live="polite"><strong>{loading ? "—" : products.length}</strong><span>results</span></div></div><div className="container filter-bar" aria-label="Catalogue filters">{catalogueCollections.map((collection) => <button key={collection.slug} className={collection.slug === activeCategory ? "is-active" : ""} type="button" onClick={() => chooseCategory(collection.slug)} aria-pressed={collection.slug === activeCategory}>{collection.title}</button>)}{filtersActive ? <button className="filter-clear" type="button" onClick={clearFilters}>Clear filters</button> : null}</div></div>
      <div className="container">{loading ? <LoadingGrid /> : null}{error ? <ErrorState message={error} retry={load} /> : null}{!loading && !error && products.length ? <div className="product-grid product-grid--store">{products.map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div> : null}{!loading && !error && !products.length ? <div className="empty-state empty-state--catalogue"><SearchIcon /><p className="eyebrow">No matches</p><h3>No products are on this section of rail.</h3><p>Try another category or clear the current search and sort controls.</p><button className="button button--secondary" type="button" onClick={clearFilters}>Clear filters</button></div> : null}</div>
    </section></>;
}

function featuredCompare(a: CatalogueProduct, b: CatalogueProduct) { if (a.featured !== b.featured) return a.featured ? -1 : 1; return (a.featuredOrder ?? Number.MAX_SAFE_INTEGER) - (b.featuredOrder ?? Number.MAX_SAFE_INTEGER) || (a.displayOrder ?? 1000) - (b.displayOrder ?? 1000) || a.slug.localeCompare(b.slug); }
function LoadingGrid() { return <div className="product-grid product-grid--store" aria-label="Loading products" aria-busy="true">{Array.from({ length: 8 }, (_, index) => <div className="product-skeleton" key={index}><span /><i /><i /></div>)}</div>; }
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="empty-state empty-state--error"><p className="eyebrow">Shop unavailable</p><h3>{message}</h3><p>The replacement shop does not fall back to legacy catalogue data.</p><button className="button button--secondary" type="button" onClick={retry}>Try again</button></div>; }
