import { Link } from "react-router-dom";
import { ArrowIcon, BoltIcon, CrownIcon } from "../components/Icons";
import { SignalField } from "../components/SignalField";

export function VipPage() {
  return <div className="vip-page">
    <section className="vip-hero" aria-labelledby="vip-title"><SignalField /><div className="vip-hero__constellation" aria-hidden="true">{Array.from({ length: 18 }, (_, index) => <i key={index} />)}</div><div className="container vip-hero__grid"><div className="vip-hero__copy"><p className="eyebrow">THIRD RAILIFY VIP</p><h1 id="vip-title">THE INNER RAIL<br /><span>IS BEING BUILT.</span></h1><p>VIP V2 is not available yet. Membership purchase is inactive, billing is disabled, and account entitlements are not connected. This preview exists so the next access path can be built with real authority instead of theatre.</p><div className="button-row"><Link className="button button--primary" to="/community">Back to Community <ArrowIcon /></Link><Link className="button button--secondary" to="/watch">Watch the Show <ArrowIcon /></Link></div></div><div className="vip-medallion" aria-hidden="true"><i /><i /><i /><div><CrownIcon /><strong>VIP</strong><small>INNER RAIL</small></div></div></div></section>
    <section className="section vip-status-section" aria-labelledby="vip-status-title"><div className="container split-heading"><div><p className="eyebrow">Current access state</p><h2 id="vip-status-title">Gated means gated.</h2></div><p>No legacy pricing, implied tier, or decorative purchase control is presented as a working membership.</p></div><div className="container vip-status-grid"><Status label="Membership activation" value="Not connected" /><Status label="Billing" value="Disabled" /><Status label="Entitlements" value="Not active" /></div></section>
    <section className="section vip-authority-section" aria-labelledby="vip-authority-title"><div className="container vip-authority"><div className="vip-authority__mark"><BoltIcon /></div><div><p className="eyebrow">Why the gate stays closed</p><h2 id="vip-authority-title">Access needs an honest handoff.</h2><p>The replacement experience needs authoritative accounts, a deliberate billing boundary, and a verified entitlement handoff. Until those pieces exist together, there is no fake access path and no purchase button.</p></div><ol><li><span>01</span>Account authority</li><li><span>02</span>Billing handoff</li><li><span>03</span>Entitlement proof</li></ol></div></section>
    <section className="vip-closing"><div className="container"><CrownIcon /><p className="eyebrow">THE SIGNAL CONTINUES</p><h2>Stay with the herd while the inner rail takes shape.</h2><div className="button-row"><Link className="button button--primary" to="/community">Explore Community</Link><Link className="button button--secondary" to="/watch">Watch Third Railify</Link></div></div></section>
  </div>;
}
function Status({ label, value }: { label: string; value: string }) { return <article><i aria-hidden="true" /><span>{label}</span><strong>{value}</strong></article>; }
