import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { BackIcon, EditIcon, FullscreenIcon, OfficialIcon, PaletteIcon, PracticeIcon, ShareIcon, SoundIcon } from "../components/Icons";
import { useAuth } from "../auth/AuthProvider";
import { getWheel, officialSpin, winnerAction } from "../wheels/client";
import { selectWeightedEntry, spinPlan } from "../wheels/engine.mjs";
import type { Wheel, WheelAccess, WheelEntry } from "../wheels/types";
import { AppearanceDialog } from "../wheels/AppearanceDialog";
import { WheelCanvas } from "../wheels/WheelCanvas";
import { WinnerCelebration } from "../wheels/WinnerCelebration";
import "../styles/wheels.css";

export function WheelPage({ presentation = false }: { presentation?: boolean }) {
  const { slug = "" } = useParams(); const { account, csrfToken, openAuth } = useAuth(); const audio = useWheelAudio();
  const [wheel, setWheel] = useState<Wheel | null>(null); const [access, setAccess] = useState<WheelAccess | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [mode, setMode] = useState<"practice" | "official">("practice"); const [rotation, setRotation] = useState(0); const [spinning, setSpinning] = useState(false); const [soundMuted, setSoundMuted] = useState(false); const [result, setResult] = useState<{ entry: WheelEntry; official: boolean } | null>(null); const [busyAction, setBusyAction] = useState(false); const [appearanceOpen, setAppearanceOpen] = useState(false); const pending = useRef<{ entry: WheelEntry; official: boolean } | null>(null);

  const load = useCallback(async () => { setLoading(true); try { const payload = await getWheel(slug); setWheel(payload.wheel); setAccess(payload.access); setError(""); if (!payload.access.canSpinOfficially) setMode("practice"); } catch (reason) { setError(message(reason)); setWheel(null); } finally { setLoading(false); } }, [slug]);
  useEffect(() => { void load(); }, [load]);
  const cleanupAudio = audio.cleanup;
  useEffect(() => () => { cleanupAudio(); }, [cleanupAudio]);
  useEffect(() => { if (!presentation) return; document.documentElement.classList.add("wheel-presentation-root"); return () => document.documentElement.classList.remove("wheel-presentation-root"); }, [presentation]);

  const finishSpin = useCallback(() => { setSpinning(false); audio.stopTicks(); const next = pending.current; pending.current = null; if (!next) return; setResult(next); if (wheel?.config.winnerSoundEnabled && !soundMuted) audio.playWinner(); }, [audio, soundMuted, wheel?.config.winnerSoundEnabled]);
  const spin = async () => {
    audio.unlock(); if (!wheel || spinning) return; const active = wheel.entries.filter((entry) => entry.state === "active"); if (!active.length) { setError("This wheel has no active participants."); return; }
    if (mode === "official" && active.length < 2) { setError("Official draws require at least two active participants."); return; }
    setError(""); setResult(null);
    try {
      let entry: WheelEntry; let official = false;
      if (mode === "official") { if (!access?.canSpinOfficially || !csrfToken || !wheel.revision) throw new Error("Official spinner access is unavailable."); const response = await officialSpin(slug, wheel.revision, crypto.randomUUID(), csrfToken); entry = active.find((candidate) => candidate.id === response.spin.winningEntryId) || { id: response.spin.winningEntryId, label: response.spin.winningLabel, order: 0, weight: 1, colour: null, state: "active" }; official = true; }
      else entry = selectWeightedEntry(active);
      const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; const plan = spinPlan(active, entry.id, reduced ? 2000 : wheel.config.spinDurationMs, rotation); pending.current = { entry, official }; setSpinning(true); setRotation(plan.finalRotation);
      if (!soundMuted && wheel.config.tickingSoundEnabled && !reduced) audio.startTicks(plan.durationMs); if (reduced) window.requestAnimationFrame(() => finishSpin());
    } catch (reason) { setError(message(reason)); setSpinning(false); pending.current = null; audio.stopTicks(); }
  };
  const mutateWinner = async (action: "keep" | "hide" | "remove" | "remove-matching") => { if (!result || !csrfToken || !access?.canEdit) return; if (action === "keep") { setResult(null); return; } setBusyAction(true); try { const payload = await winnerAction(slug, result.entry.id, action, csrfToken); setWheel(payload.wheel); setAccess(payload.access); setResult(null); } catch (reason) { setError(message(reason)); } finally { setBusyAction(false); } };
  const toggleFullscreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen(); } catch { setError("Fullscreen is unavailable in this browser. Presentation mode still fills the page."); } };
  const toggleSound = () => { if (soundMuted) audio.unlock(); setSoundMuted((value) => !value); };

  if (loading) return <WheelState presentation={presentation} title="Tuning the wheel signal…" />;
  if (!wheel) return <WheelState presentation={presentation} title="Wheel unavailable" message={error || "This wheel was not found."} />;
  const active = wheel.entries.filter((entry) => entry.state === "active"); const officialAvailable = Boolean(access?.canSpinOfficially && wheel.officialEnabled && wheel.lifecycle === "active"); const messageTemplate = wheel.config.winnerMessageTemplate || "Signal locked: {winner}"; const background = wheel.config.backgroundEnabled !== false ? wheel.media?.background?.url : null;
  const pageStyle = { "--wheel-bg-image": background ? `url("${background}")` : "none", "--wheel-bg-x": `${wheel.config.backgroundFocalX ?? 50}%`, "--wheel-bg-y": `${wheel.config.backgroundFocalY ?? 50}%`, "--wheel-bg-opacity": (wheel.config.backgroundImageOpacity ?? 72) / 100, "--wheel-overlay": (wheel.config.backgroundOverlayIntensity ?? 58) / 100 } as React.CSSProperties;
  return <div className={`wheel-control-page${presentation ? " wheel-control-page--presentation" : ""} intensity--${wheel.config.backgroundIntensity}${background ? " has-custom-background" : ""}`} style={pageStyle}>
    <div className="wheel-control-page__background" aria-hidden="true" />
    {presentation ? <header className="presentation-bar"><Link to={`/wheels/${wheel.slug}`} aria-label="Exit presentation mode"><BackIcon /> Exit</Link><span>{wheel.title}</span><button type="button" onClick={toggleFullscreen}><FullscreenIcon /> Fullscreen</button></header> : null}
    <div className={presentation ? "wheel-presentation-layout" : "container wheel-control-layout"}>
      <main className="wheel-control-stage">
        {!presentation ? <><nav className="wheel-breadcrumb" aria-label="Breadcrumb"><Link to="/wheels"><BackIcon /> Back to wheels</Link><span>WHEELS / {wheel.visibility === "public" ? "PUBLIC DRAW" : "PRIVATE DRAW"} / {wheel.title}</span></nav><header className="wheel-control-heading"><div><p className="eyebrow">THIRD RAILIFY WHEEL</p><h1>{wheel.title}</h1><p>{wheel.description}</p></div><div className="wheel-control-heading__actions"><button type="button" className="icon-control" onClick={() => navigator.clipboard?.writeText(window.location.href)} aria-label="Copy wheel link"><ShareIcon /> Share</button><Link className="icon-control" to={`/wheels/${wheel.slug}/present`}><FullscreenIcon /> Present</Link>{access?.canEdit ? <Link className="icon-control" to={`/wheels/${wheel.slug}/edit`}><EditIcon /> Edit</Link> : null}</div></header></> : <h1 className="sr-only">{wheel.title} presentation</h1>}
        <div className="wheel-visual-wrap"><WheelCanvas entries={wheel.entries} config={wheel.config} rotation={rotation} durationMs={wheel.config.spinDurationMs} spinning={spinning} winner={Boolean(result)} centreImageUrl={wheel.media?.centre?.url} onSpinEnd={finishSpin} /></div>
        <div className="wheel-spin-console">
          <div className="wheel-spin-console__secondary">{officialAvailable ? <fieldset className="draw-mode-switch"><legend>Draw mode</legend><button type="button" className={mode === "practice" ? "is-active" : ""} aria-label="Practice spin" aria-pressed={mode === "practice"} onClick={() => setMode("practice")} disabled={spinning}><PracticeIcon /> Practice</button><button type="button" className={mode === "official" ? "is-active is-official" : ""} aria-label="Official draw" aria-pressed={mode === "official"} onClick={() => setMode("official")} disabled={spinning}><OfficialIcon /> Official</button></fieldset> : <p className="draw-badge">DEMO / NOT RECORDED</p>}</div>
          <button className={`spin-trigger${mode === "official" ? " spin-trigger--official" : ""}`} type="button" onClick={() => void spin()} disabled={spinning || !active.length || (!wheel.demoEnabled && mode === "practice")} aria-label={mode === "official" ? "Start recorded official draw" : "Start demo spin"}><span>{spinning ? "SIGNAL IN MOTION" : "SPIN WHEEL"}</span><small>{mode === "official" ? "Server-selected · recorded" : "Local demo · not recorded"}</small></button>
          <div className="wheel-spin-console__tools"><button className="sound-toggle" type="button" aria-pressed={!soundMuted} onClick={toggleSound} aria-label={soundMuted ? "Turn wheel sound on" : "Turn wheel sound off"}><SoundIcon muted={soundMuted} /> {soundMuted ? "Sound off" : "Sound on"}</button>{access?.canEdit && csrfToken ? <button className="sound-toggle" type="button" onClick={() => setAppearanceOpen(true)}><PaletteIcon /> Appearance</button> : null}{presentation ? <button className="sound-toggle" type="button" onClick={toggleFullscreen}><FullscreenIcon /> Fullscreen</button> : null}</div>
        </div>
        <div className="wheel-live-region sr-only" role="status" aria-live="polite">{result ? `${result.official ? "Official" : "Demo"} result: ${result.entry.label}` : ""}</div>{error ? <div className="wheel-alert" role="alert">{error}</div> : null}
      </main>
      {!presentation ? <aside className="wheel-result-rail"><section><p className="eyebrow">DRAW STATUS</p><StatusRows wheel={wheel} access={access} /></section><section><div className="rail-section-title"><h2>Participants</h2><span>{active.length}</span></div><ol className="participant-list">{wheel.entries.map((entry) => <li key={entry.id} className={entry.state === "hidden" ? "is-hidden" : ""}><i style={{ background: entry.colour || wheel.config.palette[entry.order % wheel.config.palette.length] }} /><span>{entry.label}</span>{entry.weight !== 1 ? <b>{entry.weight}×</b> : null}{entry.state === "hidden" ? <em>Hidden</em> : null}</li>)}</ol></section><section><div className="rail-section-title"><h2>Official history</h2><span>{wheel.recentOfficialResults.length}</span></div>{wheel.recentOfficialResults.length ? <ol className="result-history">{wheel.recentOfficialResults.map((item) => <li key={item.id}><strong>{item.winningLabel}</strong><span>{formatDate(item.createdAt)}{item.voided ? " · voided" : ""}</span></li>)}</ol> : <p className="rail-empty">No recorded official results.</p>}</section>{!account ? <button type="button" className="secondary-button" onClick={() => openAuth("signin")}>Log in for approved controls</button> : null}</aside> : null}
    </div>
    {result ? <WinnerCelebration entry={result.entry} official={result.official} message={messageTemplate} celebrationEnabled={wheel.config.celebrationEnabled !== false} confettiEnabled={wheel.config.confettiEnabled !== false} lightingEnabled={wheel.config.winnerLightingEnabled !== false} intensity={new Set(["subtle", "normal", "strong"]).has(wheel.config.celebrationIntensity) ? wheel.config.celebrationIntensity : "normal"} palette={wheel.config.palette} canEdit={Boolean(access?.canEdit)} busy={busyAction} onClose={() => setResult(null)} onAction={(action) => void mutateWinner(action)} /> : null}
    {appearanceOpen && access?.canEdit && csrfToken ? <AppearanceDialog wheel={{ ...wheel, media: wheel.media || { background: null, centre: null } }} csrfToken={csrfToken} onClose={() => setAppearanceOpen(false)} onSaved={setWheel} /> : null}
  </div>;
}

function StatusRows({ wheel, access }: { wheel: Wheel; access: WheelAccess | null }) { return <dl className="wheel-status-list"><div><dt>Mode</dt><dd>{access?.canSpinOfficially ? "Official available" : "Public demo"}</dd></div><div><dt>Wheel</dt><dd>{wheel.lifecycle === "archived" ? "Archived" : wheel.visibility === "hidden" ? "Hidden" : "Public"}</dd></div><div><dt>Weighting</dt><dd>{wheel.weighted ? "Weighted segments" : "Equal segments"}</dd></div><div><dt>Official lock</dt><dd>{access?.officialSpinLocked ? "Locked by Admin" : "Open"}</dd></div>{wheel.latestOfficialResult ? <div><dt>Latest result</dt><dd>{wheel.latestOfficialResult.winningLabel}</dd></div> : null}</dl>; }
function WheelState({ presentation, title, message: detail }: { presentation: boolean; title: string; message?: string }) { return <div className={`wheel-route-state${presentation ? " wheel-route-state--presentation" : ""}`}><div><span aria-hidden="true">ϟ</span><h1>{title}</h1>{detail ? <p>{detail}</p> : null}<Link to="/wheels">Return to Wheels</Link></div></div>; }
function useWheelAudio() { const context = useRef<AudioContext | null>(null); const tickTimer = useRef<number | null>(null); const stingerNodes = useRef<OscillatorNode[]>([]); const closeTimer = useRef<number | null>(null); const unlock = useCallback(() => { try { context.current ||= new AudioContext(); if (context.current.state === "suspended") void context.current.resume(); } catch { /* optional */ } }, []); const stopTicks = useCallback(() => { if (tickTimer.current != null) window.clearInterval(tickTimer.current); tickTimer.current = null; }, []); const startTicks = useCallback((duration: number) => { stopTicks(); const audio = context.current; if (!audio) return; let elapsed = 0; tickTimer.current = window.setInterval(() => { elapsed += 150; const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.frequency.value = 880; gain.gain.setValueAtTime(.022, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audio.currentTime + .035); oscillator.connect(gain).connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + .04); if (elapsed >= duration) stopTicks(); }, 150); }, [stopTicks]); const stopWinner = useCallback(() => { for (const node of stingerNodes.current) try { node.stop(); } catch { /* stopped */ } stingerNodes.current = []; if (closeTimer.current != null) window.clearTimeout(closeTimer.current); closeTimer.current = null; }, []); const playWinner = useCallback(() => { stopWinner(); const audio = context.current; if (!audio || audio.state !== "running") return; const notes = [392, 523.25, 659.25, 783.99]; notes.forEach((frequency, index) => { const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.type = index < 2 ? "triangle" : "sine"; oscillator.frequency.value = frequency; const start = audio.currentTime + index * .095; gain.gain.setValueAtTime(.0001, start); gain.gain.exponentialRampToValueAtTime(.06, start + .018); gain.gain.exponentialRampToValueAtTime(.0001, start + .42); oscillator.connect(gain).connect(audio.destination); oscillator.start(start); oscillator.stop(start + .45); stingerNodes.current.push(oscillator); }); closeTimer.current = window.setTimeout(stopWinner, 1100); }, [stopWinner]); const cleanup = useCallback(() => { stopTicks(); stopWinner(); const audio = context.current; context.current = null; if (audio) void audio.close(); }, [stopTicks, stopWinner]); return { unlock, startTicks, stopTicks, playWinner, cleanup }; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Unavailable" : new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(date); }
function message(reason: unknown) { return reason instanceof Error ? reason.message : "The wheel service is unavailable."; }
