import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../auth/AuthProvider";
import { getCreatorAccess, listWheels } from "../wheels/client";
import type { WheelSummary } from "../wheels/types";
import { WheelsBrandMark } from "../wheels/WheelsBrandMark";
import "../styles/wheels.css";

export function WheelsPage() {
  const { account, openAuth } = useAuth(); const [items, setItems] = useState<WheelSummary[]>([]); const [search, setSearch] = useState(""); const [sort, setSort] = useState("recent"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [canCreate, setCanCreate] = useState(false);
  useEffect(() => { let active = true; setLoading(true); Promise.all([listWheels(search, sort), account ? getCreatorAccess().catch(() => null) : Promise.resolve(null)]).then(([payload, access]) => { if (!active) return; setItems(payload.items); setCanCreate(Boolean(access?.canCreate)); setError(""); }).catch((reason) => active && setError(message(reason))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [account, search, sort]);
  const featured = useMemo(() => items.slice(0, 3), [items]);
  return <div className="wheels-page">
    <section className="wheels-hero"><div className="container wheels-hero__grid"><div><p className="eyebrow">THIRD RAILIFY DRAW CONTROL</p><h1>SPIN THE <em>RAIL.</em></h1><p className="wheels-hero__lede">Public competition wheels built for raid calls, giveaways, games, and live show segments—with a clean line between practice and recorded official draws.</p><div className="wheels-hero__actions">{canCreate ? <Link className="primary-button" to="/wheels/new">Build a wheel</Link> : account ? <span className="wheels-access-note">Creator access is granted by Admin.</span> : <button className="primary-button" type="button" onClick={() => openAuth("signin")}>Log in for creator access</button>}<a className="text-link" href="#wheel-directory">Explore public wheels ↓</a></div></div><HeroWheel /></div><div className="wheels-trust-rail"><span><b>PUBLIC</b> View and demo-spin</span><span><b>APPROVED</b> Create and edit</span><span><b>OFFICIAL</b> Server-selected and recorded</span></div></section>
    <section id="wheel-directory" className="container wheels-directory"><header><div><p className="eyebrow">PUBLIC SIGNALS</p><h2>Competition wheels</h2><p>Every listed wheel is active and public. Hidden and archived wheels never appear here.</p></div><div className="wheels-directory__filters"><label><span>Search wheels</span><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title or description" /></label><label><span>Sort</span><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="recent">Recently updated</option><option value="title">Title A–Z</option><option value="participants">Most participants</option></select></label></div></header>
      {error ? <div className="wheel-alert" role="alert">{error}</div> : loading ? <div className="wheels-empty wheels-empty--loading"><WheelsBrandMark /><span>Tuning the draw signal…</span></div> : !items.length ? <div className="wheels-empty"><WheelsBrandMark /><h3>No public wheels are live yet.</h3><p>That is an authoritative empty state. Approved creators can publish the first one.</p></div> : <div className="wheel-card-grid">{featured.map((wheel, index) => <WheelCard key={wheel.slug} wheel={wheel} featured={index === 0} />)}{items.slice(3).map((wheel) => <WheelCard key={wheel.slug} wheel={wheel} />)}</div>}
    </section>
    <section className="container wheels-explainer"><article><span>01</span><h2>Practice in public.</h2><p>Anonymous visitors use local cryptographic selection. Demo outcomes are never written to result history.</p></article><article><span>02</span><h2>Draw with authority.</h2><p>Approved spinners choose Official mode. The server selects and persists the winner before motion begins.</p></article><article><span>03</span><h2>Keep the record.</h2><p>Revision, participant snapshot hash, immutable winner label, and audit context remain attached to every official result.</p></article></section>
  </div>;
}

function WheelCard({ wheel, featured = false }: { wheel: WheelSummary; featured?: boolean }) { return <Link className={`wheel-card${featured ? " wheel-card--featured" : ""}`} to={`/wheels/${wheel.slug}`} style={{ "--wheel-a": wheel.palette?.[0] || "#f3c928", "--wheel-b": wheel.palette?.[1] || "#b8182f" } as React.CSSProperties}><div className="wheel-card__orbit" aria-hidden="true"><i /><i /><i /><WheelsBrandMark /></div><div className="wheel-card__copy"><p className="eyebrow">{wheel.officialEnabled ? "OFFICIAL READY" : "PUBLIC DEMO"}</p><h3>{wheel.title}</h3><p>{wheel.description || "A public Third Railify competition wheel."}</p><div><span>{wheel.participantCount} participants</span>{wheel.weighted ? <span>Weighted</span> : null}<span>{wheel.demoEnabled ? "Demo enabled" : "View only"}</span></div></div><span className="wheel-card__arrow">↗</span></Link>; }
function HeroWheel() { return <div className="hero-wheel" aria-hidden="true"><div className="hero-wheel__rails" /><div className="hero-wheel__ring"><i /><i /><i /><i /><i /><i /><i /><i /></div><div className="hero-wheel__hub"><WheelsBrandMark /></div><div className="hero-wheel__pointer" /></div>; }
function message(reason: unknown) { return reason instanceof Error ? reason.message : "The wheel directory is unavailable."; }
