import type { Poll, PollAccess } from "./types";
export type PollError = Error & { code?: string; status?: number };
export function listPolls(view = "open", search = "") { return request<{ ok: true; items: Poll[]; count: number; refreshedAt: string }>(`/api/polls?view=${encodeURIComponent(view)}&search=${encodeURIComponent(search)}`); }
export function getPoll(slug: string) { return request<{ ok: true; poll: Poll; access: PollAccess; refreshedAt: string }>(`/api/polls/${encodeURIComponent(slug)}`); }
export function getCreatorAccess() { return request<{ ok: true; authenticated: boolean; canCreate: boolean; canManageAll: boolean }>("/api/polls/access"); }
export function createPoll(input: Record<string, unknown>, csrf: string) { return request<{ ok: true; poll: Poll; access: PollAccess }>("/api/polls", { method: "POST", headers: jsonHeaders(csrf), body: JSON.stringify(input) }); }
export function savePoll(slug: string, input: Record<string, unknown>, csrf: string) { return request<{ ok: true; poll: Poll; access: PollAccess }>(`/api/polls/${encodeURIComponent(slug)}`, { method: "PUT", headers: jsonHeaders(csrf), body: JSON.stringify(input) }); }
export function lifecyclePoll(slug: string, revision: number, action: "open" | "close" | "archive" | "restore", csrf: string) { return request<{ ok: true; poll: Poll; access: PollAccess }>(`/api/polls/${encodeURIComponent(slug)}/lifecycle`, { method: "POST", headers: jsonHeaders(csrf), body: JSON.stringify({ revision, action }) }); }
export function votePoll(slug: string, optionId: string, csrf = "") { return request<{ ok: true; poll: Poll; vote: { optionId: string; repeated: boolean; changed: boolean }; refreshedAt: string }>(`/api/polls/${encodeURIComponent(slug)}/vote`, { method: "POST", headers: csrf ? jsonHeaders(csrf) : { "Content-Type": "application/json" }, body: JSON.stringify({ optionId }) }); }
function jsonHeaders(csrf: string) { return { "Content-Type": "application/json", "X-CSRF-Token": csrf }; }
async function request<T>(input: string, init: RequestInit = {}) { const response = await fetch(input, { ...init, cache: "no-store", credentials: "include", headers: { Accept: "application/json", ...(init.headers || {}) } }); const payload = await response.json().catch(() => null) as (T & { error?: string; message?: string }) | null; if (!response.ok || !payload) { const error = new Error(payload?.message || "The Poll service is unavailable.") as PollError; error.code = payload?.error; error.status = response.status; throw error; } return payload; }
