import type { WheelEntry } from "./types";
export type RandomValues = (values: Uint32Array) => Uint32Array;
export function secureBoundedInteger(maxExclusive: number, randomValues?: RandomValues): number;
export function selectWeightedEntry(entries: WheelEntry[], randomValues?: RandomValues): WheelEntry;
export function secureShuffle<T>(items: readonly T[], randomValues?: RandomValues): T[];
export type SpinPlanOptions = { landingFraction?: number; turnRandom?: number; extraTurns?: number; randomValues?: RandomValues };
export type WheelSpinPlan = { winnerId: string; durationMs: number; turns: number; landingFraction: number; landingLocalAngle: number; targetModuloRotation: number; positiveTargetDelta: number; startRotation: number; totalTravel: number; finalRotation: number; startAt?: number; id?: string };
export function entryAngles(entries: WheelEntry[]): Array<{ entry: WheelEntry; start: number; end: number; span: number; centre: number }>;
export function normalizeTurn(value: number): number;
export function entryAtAngle(entries: WheelEntry[], angle: number): WheelEntry | null;
export function entryAtPointer(entries: WheelEntry[], rotationDegrees: number, pointerAngle?: number): WheelEntry | null;
export function hitTestWheel(entries: WheelEntry[], point: { x: number; y: number }, size: number, rotationDegrees: number, innerRadiusRatio?: number, outerRadiusRatio?: number): WheelEntry | null;
export function participantOdds(entries: WheelEntry[], entryId: string): { entry: WheelEntry | null; totalWeight: number; probability: number; combinedWeight: number; combinedProbability: number; eligibleCount: number };
export function formatProbability(probability: number): string;
export function secureUnitFraction(randomValues?: RandomValues): number;
export function constantDecelerationProgress(elapsedMs: number, durationMs: number): number;
export function constantDecelerationVelocity(elapsedMs: number, durationMs: number, totalTravel?: number): number;
export function suspenseDecayProgress(elapsedMs: number, durationMs: number): number;
export function suspenseDecayVelocity(elapsedMs: number, durationMs: number, totalTravel?: number): number;
export function fullTurnsForDuration(durationMs: number, turnRandom?: number): number;
export function spinPlan(entries: WheelEntry[], winnerId: string, durationMs: number, currentRotation?: number, options?: number | SpinPlanOptions): WheelSpinPlan;
