import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { CloseIcon } from "../components/Icons";
import { saveWheel, uploadWheelMedia } from "./client";
import { secureShuffle } from "./engine.mjs";
import type { Wheel, WheelEntry } from "./types";
import { useModalDialog } from "./dialog";
import { SegmentStyleDialog, SegmentStylePreview } from "./SegmentStyleDialog";
import { normalizePaletteStyles, resolvedEntryStyle, styleForEntry, type SegmentStyle } from "./segmentStyles.mjs";

export function ParticipantManagerDialog({ wheel, csrfToken, onClose, onSaved }: { wheel: Wheel; csrfToken: string; onClose: () => void; onSaved: (wheel: Wheel) => void }) {
  const [entries, setEntries] = useState(() => wheel.entries.map((entry) => ({ ...entry })));
  const baseline = useRef(JSON.stringify(wheel.entries)); const [quick, setQuick] = useState(""); const [bulk, setBulk] = useState(""); const [search, setSearch] = useState(""); const [sort, setSort] = useState<"order" | "label" | "weight">("order"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [confirmClose, setConfirmClose] = useState(false); const [confirmClear, setConfirmClear] = useState(false); const root = useRef<HTMLDivElement>(null); const close = useRef<HTMLButtonElement>(null); const restoringHistory = useRef(false);
  const [styleEntryId, setStyleEntryId] = useState<string | null>(null); const [stagedFiles, setStagedFiles] = useState<Map<string, File>>(() => new Map()); const previewUrls = useObjectUrlMap(stagedFiles);
  const segmentMedia = useMemo(() => [...(wheel.media.segmentFills || []), ...[...stagedFiles].map(([id, file]) => ({ id, purpose: "segment_fill" as const, url: previewUrls[id] || "", contentType: file.type, byteSize: file.size, width: null, height: null, sha256: "", createdAt: "", fileName: file.name }))], [previewUrls, stagedFiles, wheel.media.segmentFills]);
  const dirty = JSON.stringify(entries) !== baseline.current; const activeCount = entries.filter((entry) => entry.state === "active").length;
  const duplicates = useMemo(() => { const counts = new Map<string, number>(); entries.forEach((entry) => counts.set(entry.label.toLowerCase(), (counts.get(entry.label.toLowerCase()) || 0) + 1)); return new Set([...counts].filter(([, count]) => count > 1).map(([label]) => label)); }, [entries]);
  const visible = useMemo(() => { const filtered = entries.filter((entry) => entry.label.toLowerCase().includes(search.toLowerCase())); if (sort === "label") return [...filtered].sort((a, b) => a.label.localeCompare(b.label)); if (sort === "weight") return [...filtered].sort((a, b) => b.weight - a.weight || a.order - b.order); return filtered; }, [entries, search, sort]);
  const requestClose = useCallback(() => { if (dirty) setConfirmClose(true); else onClose(); }, [dirty, onClose]); useModalDialog(root, close, requestClose);
  useEffect(() => { const unload = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; const pop = () => { if (restoringHistory.current) { restoringHistory.current = false; return; } if (dirty) { restoringHistory.current = true; window.history.forward(); setConfirmClose(true); } }; window.addEventListener("beforeunload", unload); window.addEventListener("popstate", pop); return () => { window.removeEventListener("beforeunload", unload); window.removeEventListener("popstate", pop); }; }, [dirty]);
  const normalize = (list: WheelEntry[]) => list.map((entry, order) => ({ ...entry, order }));
  const add = (label: string, weight = 1, colour: string | null = null) => { const clean = label.trim().replace(/\s+/g, " ").slice(0, 120); if (!clean || entries.length >= 1000) return; setEntries((current) => [...current, { id: crypto.randomUUID(), label: clean, order: current.length, weight: Math.max(1, Math.min(100000, Math.trunc(weight) || 1)), colour: /^#[0-9a-f]{6}$/i.test(colour || "") ? colour!.toUpperCase() : null, style: null, state: "active" }]); };
  const patch = (id: string, value: Partial<WheelEntry>) => setEntries((current) => normalize(current.map((entry) => entry.id === id ? { ...entry, ...value } : entry)));
  const move = (id: string, delta: number) => setEntries((current) => { const index = current.findIndex((entry) => entry.id === id); const target = index + delta; if (index < 0 || target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return normalize(next); });
  const applyBulk = () => { for (const line of bulk.split(/\r?\n/).map((value) => value.trim()).filter(Boolean).slice(0, Math.max(0, 1000 - entries.length))) { const [label, weight, colour] = line.split(",").map((value) => value.trim()); add(label, Number(weight || 1), colour || null); } setBulk(""); };
  const save = async () => { if (!wheel.revision) return; setBusy(true); setError(""); try { const replacements = new Map<string, string>(); const referenced = new Set(entries.filter((entry) => entry.style?.mode === "image").map((entry) => (entry.style as Extract<SegmentStyle, { mode: "image" }>).imageAssetId)); for (const [id, file] of stagedFiles) if (referenced.has(id)) { const uploaded = await uploadWheelMedia(wheel.slug, "segment-fill", file, csrfToken, file.name); replacements.set(id, uploaded.asset.id); } const savedEntries = entries.map((entry) => entry.style?.mode === "image" && replacements.has(entry.style.imageAssetId) ? { ...entry, style: { ...entry.style, imageAssetId: replacements.get(entry.style.imageAssetId)! } } : entry); const payload = await saveWheel(wheel.slug, { title: wheel.title, description: wheel.description, visibility: wheel.visibility, lifecycle: wheel.lifecycle, config: wheel.config, entries: savedEntries, revision: wheel.revision }, csrfToken); baseline.current = JSON.stringify(payload.wheel.entries); setEntries(payload.wheel.entries); setStagedFiles(new Map()); onSaved(payload.wheel); setNotice("Authoritative participant revision saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Participants could not be saved."); } finally { setBusy(false); } };
  const paletteStyles = normalizePaletteStyles(wheel.config.paletteStyles, wheel.config.palette);

  return createPortal(<div className="wheel-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) requestClose(); }}><div ref={root} className="wheel-modal participant-manager" role="dialog" aria-modal="true" aria-labelledby="participant-manager-title">
    <header className="wheel-modal__header"><div><p className="eyebrow">WHEEL CONTROL / PARTICIPANTS</p><h2 id="participant-manager-title">Manage participants</h2><span>{activeCount} active · {entries.length} / 1000 entries{dirty ? " · Unsaved changes" : ""}</span></div><button ref={close} type="button" onClick={requestClose} disabled={busy} aria-label="Close participant manager"><CloseIcon /></button></header>
    <div className="participant-manager__body"><div className="privacy-warning"><strong>Public content warning</strong><p>Entries are publicly visible. Do not add email addresses, payment details, addresses, donation data, or other sensitive information.</p></div>
      <div className="quick-add"><label><span>Quick-add participant</span><input value={quick} maxLength={120} onChange={(event) => setQuick(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); add(quick); setQuick(""); } }} /></label><button type="button" onClick={() => { add(quick); setQuick(""); }} disabled={!quick.trim() || entries.length >= 1000}>Add</button></div>
      <details className="bulk-add"><summary>Bulk paste / CSV-like lines</summary><p>One participant per line. Optional: <code>Name, weight, #RRGGBB</code>.</p><textarea value={bulk} rows={5} onChange={(event) => setBulk(event.target.value)} /><button type="button" onClick={applyBulk} disabled={!bulk.trim() || entries.length >= 1000}>Add lines</button></details>
      <div className="participant-tools"><label><span className="sr-only">Search participants</span><input type="search" value={search} placeholder="Search participants" onChange={(event) => setSearch(event.target.value)} /></label><label><span className="sr-only">Sort participants</span><select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="order">Configured order</option><option value="label">Label A–Z</option><option value="weight">Highest weight</option></select></label><button type="button" onClick={() => setEntries((current) => normalize([...current].sort((a, b) => a.label.localeCompare(b.label))))}>Sort A–Z</button><button type="button" onClick={() => setEntries((current) => normalize([...current].reverse()))}>Reverse</button><button type="button" onClick={() => setEntries((current) => normalize(secureShuffle(current)))}>Secure shuffle</button><button type="button" className="danger" onClick={() => setConfirmClear(true)} disabled={!entries.length}>Clear all</button></div>
      {confirmClear ? <div className="participant-manager__confirm" role="alert"><span>Clear every participant entry?</span><button type="button" onClick={() => setConfirmClear(false)}>Keep entries</button><button type="button" className="danger" onClick={() => { setEntries([]); setConfirmClear(false); }}>Clear all</button></div> : null}
      <div className="participant-rows">{visible.map((entry) => <div className={`participant-row${duplicates.has(entry.label.toLowerCase()) ? " has-duplicate" : ""}`} key={entry.id}>
        <div className="participant-row__order"><button type="button" onClick={() => move(entry.id, -1)} aria-label={`Move ${entry.label} up`}>↑</button><button type="button" onClick={() => move(entry.id, 1)} aria-label={`Move ${entry.label} down`}>↓</button><span>{entry.order + 1}</span></div>
        <label><span>Label</span><input value={entry.label} maxLength={120} onChange={(event) => patch(entry.id, { label: event.target.value })} />{duplicates.has(entry.label.toLowerCase()) ? <em>Duplicate label; separate entry retained.</em> : null}</label>
        <label><span>Weight</span><input type="number" min={1} max={100000} value={entry.weight} onChange={(event) => patch(entry.id, { weight: Math.max(1, Math.min(100000, Number(event.target.value) || 1)) })} /></label>
        <button type="button" className="segment-style-action" onClick={() => setStyleEntryId(entry.id)}><SegmentStylePreview style={resolvedEntryStyle(entry, wheel.config)} media={segmentMedia} previewUrls={previewUrls} label={`${entry.label} fill`} /><span><b>Style</b><small>{resolvedEntryStyle(entry, wheel.config).mode}</small></span></button>
        <button type="button" onClick={() => { const style = styleForEntry(entries, entry.id, paletteStyles); patch(entry.id, { colour: style.color, style }); }}>Reset style</button><button type="button" onClick={() => patch(entry.id, { state: entry.state === "hidden" ? "active" : "hidden" })}>{entry.state === "hidden" ? "Unhide" : "Hide"}</button><button type="button" className="danger" onClick={() => setEntries((current) => normalize(current.filter((candidate) => candidate.id !== entry.id)))} aria-label={`Remove ${entry.label}`}>Remove</button>
      </div>)}</div>
    </div>
    {error ? <p className="wheel-alert" role="alert">{error}</p> : null}{notice ? <p className="wheel-notice" role="status">{notice}</p> : null}{confirmClose ? <div className="wheel-modal__close-confirm" role="alert"><span>Discard unsaved participant changes?</span><button type="button" onClick={() => setConfirmClose(false)}>Keep editing</button><button type="button" className="danger" onClick={onClose}>Discard and close</button></div> : null}
    <footer className="wheel-modal__footer"><button type="button" className="button button--secondary" onClick={() => { setEntries(JSON.parse(baseline.current)); setNotice("Unsaved participant changes discarded."); }} disabled={!dirty || busy}>Discard</button><button type="button" className="button button--primary" onClick={() => void save()} disabled={!dirty || busy || !entries.length}>{busy ? "Saving…" : "Save participants"}</button></footer>
    {styleEntryId ? <SegmentStyleDialog label={entries.find((entry) => entry.id === styleEntryId)?.label || "Entrant"} value={resolvedEntryStyle(entries.find((entry) => entry.id === styleEntryId)!, wheel.config)} media={segmentMedia} previewUrls={previewUrls} onFile={(file) => { const id = crypto.randomUUID(); setStagedFiles((current) => new Map(current).set(id, file)); return id; }} onApply={(style) => patch(styleEntryId, { colour: style.color, style })} onClose={() => setStyleEntryId(null)} /> : null}
  </div></div>, document.body);
}

function useObjectUrlMap(files: Map<string, File>) { const [urls, setUrls] = useState<Record<string, string>>({}); useEffect(() => { const next: Record<string, string> = {}; for (const [id, file] of files) next[id] = URL.createObjectURL(file); setUrls(next); return () => { for (const url of Object.values(next)) URL.revokeObjectURL(url); }; }, [files]); return urls; }
