import { useState } from 'react';
import { EntrantAppearanceControls } from '../components/EntrantAppearanceControls';
import type { Discovery, RosterAuthority, RosterPreview, RosterRule, WheelChoice } from '../lib/automation-client';
import '../styles/subscriber-roster.css';

type Request = <T>(path: string, token?: string, body?: unknown) => Promise<T>;
const initial = (wheel: WheelChoice, source: Discovery['source']): RosterRule => ({ name: 'Current Self-Paid Subscriber Roster', sourceScope: source?.scope || '', targetWheelId: wheel.id, enabled: false, syncMode: 'add_missing', entriesPerMember: 1, minimumQuality: 'qualified_live_current', appearance: null });
const when = (value?: string | null) => value ? new Date(value).toLocaleString() : 'Not yet';

export function SubscriberRosterAutomation({ rules, authorities, wheel, discovery, request, csrf, reload, schemaReady = true }: { rules: RosterRule[]; authorities: Record<string, RosterAuthority>; wheel: WheelChoice; discovery: Discovery; request: Request; csrf: string; reload: () => Promise<void>; schemaReady?: boolean }) {
  const [editor, setEditor] = useState<RosterRule | null>(null), [preview, setPreview] = useState<RosterPreview | null>(null), [busy, setBusy] = useState(''), [error, setError] = useState('');
  const save = async (rule: RosterRule) => { setBusy('save'); setError(''); try { await request('rosters', csrf, rule); setEditor(null); setPreview(null); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Roster automation could not be saved.'); } finally { setBusy(''); } };
  const inspect = async (rule: RosterRule) => { setBusy('preview'); setError(''); try { setPreview(await request<RosterPreview>('rosters/preview', csrf, { ruleId: rule.id, revision: rule.revision })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Roster preview failed.'); } finally { setBusy(''); } };
  const sync = async () => { if (!preview?.rule.id) return; setBusy('sync'); setError(''); try { setPreview(await request<RosterPreview>('rosters/sync', csrf, { ruleId: preview.rule.id, revision: preview.rule.revision })); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Roster sync failed. Refresh and preview again.'); } finally { setBusy(''); } };
  return <section className="subscriber-roster" aria-label="Subscriber roster automation"><header><div><p className="eyebrow">MEMBERSHIP AUTOMATION</p><h3>Current Self-Paid Subscriber Roster</h3><p>Uses the persisted qualified Rumble Intelligence snapshot. Exactly 500 cents qualifies; gifted recipients and review amounts are excluded.</p></div><button disabled={!schemaReady || Boolean(busy) || !discovery.source} onClick={() => setEditor(initial(wheel, discovery.source))}>Create roster automation</button></header>
    {!schemaReady ? <p role="status" className="subscriber-roster__warning">Roster automation storage is not ready. Existing event automations remain available.</p> : null}
    {error ? <p role="alert" className="subscriber-roster__error">{error}</p> : null}
    {editor ? <form className="subscriber-roster__editor" onSubmit={event => { event.preventDefault(); void save(editor); }}><header><h4>{editor.id ? 'Edit roster automation' : 'Create roster automation'}</h4><button type="button" onClick={() => setEditor(null)}>Close</button></header><label>Name<input maxLength={100} required value={editor.name} onChange={event => setEditor({ ...editor, name: event.target.value })} /></label><label>Entries per self-paid subscriber<input type="number" min={1} max={100000} step={1} value={editor.entriesPerMember} onChange={event => setEditor({ ...editor, entriesPerMember: Number(event.target.value) })} /></label><label>Sync mode<select value={editor.syncMode} onChange={event => setEditor({ ...editor, syncMode: event.target.value as RosterRule['syncMode'] })}><option value="add_missing">Add missing only</option><option value="exact_managed">Exact managed roster</option></select></label><p>{editor.syncMode === 'exact_managed' ? 'Removes only this rule’s owned weight, and only from a fresh qualified live roster.' : 'Never automatically removes previous managed members.'}</p><label><input type="checkbox" checked={Boolean(editor.appearance)} onChange={event => setEditor({ ...editor, appearance: event.target.checked ? {} : null })} /> Apply appearance to newly created roster entrants</label>{editor.appearance ? <EntrantAppearanceControls value={editor.appearance} onChange={appearance => setEditor({ ...editor, appearance })} /> : null}<label><input type="checkbox" checked={editor.enabled} onChange={event => setEditor({ ...editor, enabled: event.target.checked })} /> Enabled</label><p>Event awards and roster membership are additive; only roster-owned weight is removed.</p><button className="primary-button" disabled={Boolean(busy) || !editor.name.trim() || !editor.sourceScope}>Save roster automation</button></form> : null}
    <div className="subscriber-roster__cards">{rules.map(rule => { const authority = authorities[rule.sourceScope]; const status = !rule.enabled ? 'Paused' : rule.lastResult === 'failed' || !authority?.current ? 'Needs attention' : authority.health === 'stale' ? 'Roster stale' : rule.lastResult === 'removal_blocked' ? 'Sync blocked' : 'Current'; return <article key={rule.id}><header><div><strong>{rule.name}</strong><small>{authority?.label || rule.sourceLabel}</small></div><span>{status}</span></header><p>{rule.entriesPerMember} per member · {rule.syncMode === 'exact_managed' ? 'Exact managed roster' : 'Add missing only'}</p><p>{authority?.counts.eligible ?? '—'} eligible · {authority?.counts.giftedExcluded ?? '—'} gifted-only excluded · {authority?.counts.mixedCurrent ?? '—'} mixed</p><p>Managed weight: {rule.counts?.managedWeight || 0} · Last sync: {when(rule.lastSuccessfulSyncAt)}</p>{rule.members?.length ? <details><summary>{rule.members.length} managed roster contributions</summary>{rule.members.map(member => <p key={member.entryId}><strong>{member.actorLabel}</strong> · +{member.weight} roster weight · snapshot <code>{member.snapshotId.slice(0, 12)}</code></p>)}</details> : null}{rule.syncMode === 'exact_managed' && !authority?.removalAllowed ? <p className="subscriber-roster__warning">Removal blocked — subscriber roster is stale/degraded</p> : null}<footer><button disabled={Boolean(busy)} onClick={() => setEditor(rule)}>Edit</button><button disabled={Boolean(busy)} onClick={() => void save({ ...rule, enabled: !rule.enabled })}>{rule.enabled ? 'Disable' : 'Enable'}</button><button disabled={Boolean(busy) || !rule.enabled} onClick={() => void inspect(rule)}>Preview changes</button></footer></article>; })}</div>
    {!rules.length ? <p>No roster automation is configured for this Wheel.</p> : null}
    {preview ? <section className="subscriber-roster__preview"><h4>Pending delta</h4><p>+{preview.delta.added.length} additions · ~{preview.delta.updated.length} updates · −{preview.delta.removed.length} managed removals · ={preview.delta.unchanged} unchanged</p><p>{preview.authority.counts.giftedExcluded} gifted excluded · {preview.authority.counts.reviewExcluded} review excluded</p>{preview.removalBlocked ? <p className="subscriber-roster__warning">Removal blocked — subscriber roster is stale/degraded.</p> : null}<button disabled={Boolean(busy) || Boolean(preview.synced)} onClick={() => void sync()}>{preview.synced ? preview.noOp ? 'No changes written' : 'Sync complete' : 'Sync now'}</button></section> : null}
  </section>;
}
