import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { createPortal } from "react-dom";
import { CloseIcon, PaletteIcon, ShareIcon } from "../components/Icons";
import { getWheel, lifecycleAction, removeWheelMedia, saveWheel, uploadWheelMedia } from "./client";
import type { Wheel, WheelConfig } from "./types";
import { useModalDialog } from "./dialog";
import { WheelCanvas } from "./WheelCanvas";
import { ImportExportDialog, type ImportedWheelContent } from "./ImportExportDialog";
import { embeddedMediaBlob, type PortableMediaSet } from "./portable.mjs";

export type WheelEditorDraft = Pick<Wheel, "title" | "description" | "visibility" | "lifecycle" | "config" | "entries" | "revision">;

export function WheelEditorDialog({ wheel, csrfToken, suspended = false, onClose, onSaved, onOpenAppearance }: { wheel: Wheel; csrfToken: string; suspended?: boolean; onClose: () => void; onSaved: (wheel: Wheel) => void; onOpenAppearance: (draft: WheelEditorDraft) => void }) {
  const initial = () => draftFrom(wheel); const [form, setForm] = useState<WheelEditorDraft>(initial); const [baseline, setBaseline] = useState<WheelEditorDraft>(initial); const [tab, setTab] = useState<"identity" | "settings" | "appearance">("identity"); const [transferOpen, setTransferOpen] = useState(false); const [portableMedia, setPortableMedia] = useState<PortableMediaSet | undefined>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [confirmClose, setConfirmClose] = useState(false); const root = useRef<HTMLFormElement>(null); const close = useRef<HTMLButtonElement>(null); const restoringHistory = useRef(false); const dirty = JSON.stringify(form) !== JSON.stringify(baseline) || portableMedia !== undefined;
  const requestClose = useCallback(() => { if (dirty) setConfirmClose(true); else onClose(); }, [dirty, onClose]); useModalDialog(root, close, requestClose, !suspended && !transferOpen);
  useEffect(() => { const next = draftFrom(wheel); setForm(next); setBaseline(next); }, [wheel]);
  useEffect(() => { const unload = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; const pop = () => { if (restoringHistory.current) { restoringHistory.current = false; return; } if (dirty) { restoringHistory.current = true; window.history.forward(); setConfirmClose(true); } }; window.addEventListener("beforeunload", unload); window.addEventListener("popstate", pop); return () => { window.removeEventListener("beforeunload", unload); window.removeEventListener("popstate", pop); }; }, [dirty]);
  const patchConfig = (patch: Partial<WheelConfig>) => setForm((current) => ({ ...current, config: { ...current.config, ...patch } }));
  const save = async (event?: FormEvent) => {
    event?.preventDefault(); setBusy(true); setError(""); setNotice("");
    try {
      const payload = await saveWheel(wheel.slug, { ...form, description: form.description || "" }, csrfToken); let savedWheel = payload.wheel;
      let next = draftFrom(savedWheel); setForm(next); setBaseline(next); onSaved(savedWheel);
      if (portableMedia !== undefined) {
        try { await persistPortableMedia(wheel, portableMedia, csrfToken); savedWheel = (await getWheel(wheel.slug)).wheel; next = draftFrom(savedWheel); setForm(next); setBaseline(next); setPortableMedia(undefined); onSaved(savedWheel); }
        catch (reason) { throw new Error(`Wheel content was saved, but imported media is still pending: ${reason instanceof Error ? reason.message : "media could not be saved"}`); }
      }
      setNotice("Authoritative wheel revision saved.");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "The wheel could not be saved."); } finally { setBusy(false); }
  };
  const archive = async () => { setBusy(true); setError(""); try { await lifecycleAction(wheel.slug, "archive", csrfToken); const payload = await getWheel(wheel.slug); const next = draftFrom(payload.wheel); setForm(next); setBaseline(next); onSaved(payload.wheel); setNotice("Wheel archived. Official spins are disabled and history is retained."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The wheel could not be archived."); } finally { setBusy(false); } };
  const loadImport = (content: ImportedWheelContent) => { setForm((current) => ({ ...current, title: content.title, description: content.description, config: content.config, entries: content.entries })); setPortableMedia(content.media); setNotice(`${content.sourceFormat} loaded as unsaved editor state. Press Save changes to persist it.`); setError(""); setTransferOpen(false); };
  if (suspended) return null;
  if (transferOpen) return <ImportExportDialog source={{ ...form, media: wheel.media, slug: wheel.slug }} currentMedia={wheel.media} mode="existing" onClose={() => setTransferOpen(false)} onApply={loadImport} />;
  return createPortal(<div className="wheel-modal-backdrop wheel-editor-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) requestClose(); }}><form ref={root} className="wheel-modal wheel-editor-dialog" role="dialog" aria-modal="true" aria-labelledby="wheel-editor-title" onSubmit={(event) => void save(event)}>
    <header className="wheel-modal__header"><div><p className="eyebrow">APPROVED CREATOR CONTROL</p><h2 id="wheel-editor-title">Edit {form.title || "wheel"}</h2><span>Revision {form.revision || "pending"}{dirty ? " · Unsaved changes" : " · In sync"}</span></div><button ref={close} type="button" onClick={requestClose} disabled={busy} aria-label="Close wheel editor"><CloseIcon /></button></header>
    <div className="wheel-editor-dialog__tabs" role="tablist" aria-label="Wheel editor sections">{(["identity", "settings", "appearance"] as const).map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} className={tab === item ? "is-active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div><div className="wheel-editor-transfer-launch"><button className="button button--secondary button--compact" type="button" onClick={() => setTransferOpen(true)}><ShareIcon /> Import / Export</button><span>Portable wheel content · local until Save</span></div>
    <div className="wheel-editor-dialog__body"><section className="wheel-editor-dialog__controls">
      {tab === "identity" ? <><p className="editor-section-kicker">IDENTITY + PUBLICATION</p><label>Wheel title<input value={form.title} maxLength={100} required onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} /></label><label>Description<textarea value={form.description || ""} maxLength={280} rows={4} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} /></label><fieldset className="publication-choice"><legend>Visibility</legend><label><input type="radio" name="modal-visibility" checked={form.visibility === "public"} onChange={() => setForm((current) => ({ ...current, visibility: "public" }))} /><span><b>Public</b>Listed and shareable while active.</span></label><label><input type="radio" name="modal-visibility" checked={form.visibility === "hidden"} onChange={() => setForm((current) => ({ ...current, visibility: "hidden" }))} /><span><b>Hidden</b>Assigned accounts and Admin only.</span></label></fieldset><div className="editor-lifecycle"><div><b>Lifecycle</b><span>{form.lifecycle}</span></div>{form.lifecycle !== "archived" ? <button type="button" className="button button--danger-outline button--compact" onClick={() => void archive()} disabled={busy}>Archive wheel</button> : <span>History retained; official spins disabled.</span>}</div></> : null}
      {tab === "settings" ? <><p className="editor-section-kicker">SPIN + RESULT SETTINGS</p><label>Spin duration <span>{(form.config.spinDurationMs / 1000).toFixed(1)} seconds</span><input type="range" min={2000} max={20000} step={250} value={form.config.spinDurationMs} onChange={(event) => patchConfig({ spinDurationMs: Number(event.target.value) })} /></label><label>Winner message<input value={form.config.winnerMessageTemplate} maxLength={160} onChange={(event) => patchConfig({ winnerMessageTemplate: event.target.value })} /><small>Use <code>{"{winner}"}</code> where the selected label belongs.</small></label><Toggle label="Generated wheel ticks" checked={form.config.tickingSoundEnabled} onChange={(value) => patchConfig({ tickingSoundEnabled: value })} /><Toggle label="Generated winner stinger" checked={form.config.winnerSoundEnabled} onChange={(value) => patchConfig({ winnerSoundEnabled: value })} /><Toggle label="Winner celebration" checked={form.config.celebrationEnabled} onChange={(value) => patchConfig({ celebrationEnabled: value })} /><Toggle label="Public official history" checked={form.config.publicHistoryVisible} onChange={(value) => patchConfig({ publicHistoryVisible: value })} /></> : null}
      {tab === "appearance" ? <div className="wheel-editor-dialog__appearance"><PaletteIcon /><p className="editor-section-kicker">APPEARANCE + MEDIA</p><h3>Theme the broadcast stage.</h3><p>Palettes, pointer accent, entrant colours, custom background and centre artwork, celebration, confetti, lighting, focal point, and overlay controls open in the existing preview-first appearance workspace.</p><button type="button" className="button button--primary" onClick={() => onOpenAppearance(form)}><PaletteIcon /> Customize appearance</button><small>The wheel editor is suspended while Appearance is active, then returns here predictably.</small></div> : null}
    </section><aside className="wheel-editor-dialog__preview"><p className="eyebrow">LIVE PREVIEW</p><h3>{form.title || "Untitled wheel"}</h3><WheelCanvas entries={form.entries} config={form.config} rotation={0} durationMs={0} spinning={false} compact centreImageUrl={wheel.media?.centre?.url} /><dl><div><dt>Publication</dt><dd>{form.visibility === "public" ? "Public" : "Hidden"}</dd></div><div><dt>Participants</dt><dd>{form.entries.filter((entry) => entry.state === "active").length} active</dd></div><div><dt>Weighting</dt><dd>{form.entries.some((entry) => entry.weight !== 1) ? "Weighted" : "Equal"}</dd></div></dl></aside></div>
    {error ? <p className="wheel-alert" role="alert">{error}</p> : null}{notice ? <p className="wheel-notice" role="status">{notice}</p> : null}{confirmClose ? <div className="wheel-modal__close-confirm" role="alert"><span>Discard unsaved wheel changes?</span><button type="button" className="button button--secondary button--compact" onClick={() => setConfirmClose(false)}>Keep editing</button><button type="button" className="button button--danger button--compact" onClick={onClose}>Discard and close</button></div> : null}
    <footer className="wheel-modal__footer"><button type="button" className="button button--secondary" onClick={() => { setForm(baseline); setPortableMedia(undefined); setNotice("Unsaved changes discarded."); }} disabled={!dirty || busy}>Discard</button><button type="submit" className="button button--primary" disabled={!dirty || busy || !form.title.trim()}>{busy ? "Saving…" : "Save changes"}</button></footer>
  </form></div>, document.body);
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="editor-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label>; }
function draftFrom(wheel: Wheel): WheelEditorDraft { return { title: wheel.title, description: wheel.description || "", visibility: wheel.visibility, lifecycle: wheel.lifecycle, config: { ...wheel.config }, entries: wheel.entries.map((entry) => ({ ...entry })), revision: wheel.revision }; }
async function persistPortableMedia(wheel: Wheel, media: PortableMediaSet, csrfToken: string) { for (const [purpose, item] of [["background", media.background], ["centre", media.center]] as const) { if (item) { const file = embeddedMediaBlob(item); if (file) await uploadWheelMedia(wheel.slug, purpose, file, csrfToken); } else if (wheel.media?.[purpose]) await removeWheelMedia(wheel.slug, purpose, csrfToken); } }
