import type { WheelConfig, WheelEntry } from "./types";
import type { SegmentStyle } from "./segmentStyles.mjs";

export type WheelImageDimensions = Map<string, { width: number; height: number }>;
export type WheelPatternRenderPlan = Readonly<{ id: string; tile: number; tileWidth: number; tileHeight: number; lineWidth: number; dotRadius: number; extent: number; originX: number; originY: number; scale: 1; orientation: "segment-radial" | "wheel-space"; clipToSegment: true; highDprVector: true; usesBaseColour: true; usesPatternColour: true; boltSource: string | null }>;
export type WheelImageRenderPlan = Readonly<{ assetId: string; tangent: number; scale: number; width: number; height: number; centreX: number; centreY: number; imageRotation: number; cropWidth: number; cropHeight: number; cropX: number; cropY: number; localOrientation: number }>;
export type WheelSegmentRenderPlan = Readonly<{ entry: WheelEntry; index: number; start: number; end: number; midpoint: number; span: number; radialAngle: number; radialSpan: Readonly<{ inner: number; outer: number; length: number }>; tangentSpan: number; style: SegmentStyle; label: Readonly<{ text: string; visible: boolean; fontSize: number; measuredWidth: number; maxWidth: number; anchorX: number; anchorY: 0; baseline: "middle"; orientation: number }>; pattern: WheelPatternRenderPlan | null; image: WheelImageRenderPlan | null }>;
export type WheelGeometry = Readonly<{ requestedDiameter: number; requestedPhysicalSide: number; cssDiameter: number; physicalSide: number; diameter: number; outerDiameter: number; outerRadius: number; rotorDiameter: number; canvasCssSide: number; canvasBackingSide: number; centreCss: number; centrePhysical: number; faceRadius: number; faceDiameter: number; hubRadius: number; hubDiameter: number; faceToOuterRatio: number; hubToOuterRatio: number; blackBandWidth: number; ringRadii: Readonly<{ outer: number; inner: number; faceBoundary: number; light: number }>; pointerGeometry: Readonly<{ width: number; height: number; top: number }>; dpr: number }>;
export type WheelRenderPlan = Readonly<{ size: number; centre: number; radius: number; hubRadius: number; outerDiameter: number; faceToOuterRatio: number; hubToOuterRatio: number; density: number; segments: readonly WheelSegmentRenderPlan[] }>;
export const WHEEL_LABEL_FONT_FAMILY: string;
export const WHEEL_LABEL_FONT_WEIGHT: number;
export const WHEEL_GEOMETRY: Readonly<{ faceToOuterRatio: number; hubToOuterRatio: number; hubPaddingRatio: number; outerRimInsetRatio: number; innerRimInsetRatio: number; pointerWidthRatio: number; pointerHeightRatio: number; pointerTopRatio: number; dprCap: number }>;
export function resolveWheelGeometry(requestedDiameterCssPx: number, devicePixelRatio?: number): WheelGeometry;
export function createWheelRenderPlan(entries: WheelEntry[], config: WheelConfig, geometry: WheelGeometry, measureLabel: (label: string, fontSize: number) => number, imageDimensions?: WheelImageDimensions): WheelRenderPlan;
export function segmentRenderPlan(segment: { entry: WheelEntry; start: number; end: number; centre: number }, index: number, geometry: Readonly<{ size: number; centre: number; radius: number; hubRadius: number; count: number; density: number }>, config: WheelConfig, measureLabel?: (label: string, fontSize: number) => number, imageDimensions?: WheelImageDimensions): WheelSegmentRenderPlan;
