import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useNavigate } from "react-router-dom";
import { getAccountInbox, mutateAccountMessages, type AccountMessage } from "./inbox-client";

export function AccountInbox({ csrfToken }: { csrfToken:string }) {
  const navigate=useNavigate(); const [items,setItems]=useState<AccountMessage[]>([]); const [selected,setSelected]=useState<Set<string>>(new Set()); const [detail,setDetail]=useState<AccountMessage|null>(null); const [unreadOnly,setUnreadOnly]=useState(false); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setItems((await getAccountInbox(unreadOnly)).items);setSelected(new Set());}catch(reason){setError(reason instanceof Error?reason.message:"Your messages are unavailable.");}finally{setLoading(false);}},[unreadOnly]);
  useEffect(()=>{const controller=new AbortController();void getAccountInbox(unreadOnly,controller.signal).then((payload)=>{setItems(payload.items);setError("");}).catch((reason)=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:"Your messages are unavailable.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[unreadOnly]);
  const mutate=async(ids:string[],action:"read"|"unread"|"delete")=>{if(!ids.length)return;if(action==="delete"&&!window.confirm(`Delete ${ids.length} selected ${ids.length===1?"message":"messages"}?`))return;setBusy(true);setError("");try{await mutateAccountMessages(ids,action,csrfToken);setDetail((current)=>current&&ids.includes(current.id)?null:current);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Your messages could not be updated.");}finally{setBusy(false);}};
  const open=async(message:AccountMessage)=>{setDetail(message);if(message.unread)try{const readAt=new Date().toISOString();await mutateAccountMessages([message.id],"read",csrfToken);setItems((current)=>current.map((item)=>item.id===message.id?{...item,unread:false,readAt}:item));setDetail((current)=>current?.id===message.id?{...current,unread:false,readAt}:current);}catch{/* Detail remains available. */}};
  const all=items.length>0&&items.every((item)=>selected.has(item.id));
  return <section className="account-panel account-inbox"><header className="account-inbox__header"><div><p className="eyebrow">Private messages</p><h2>Your inbox.</h2><p>Open a message for the full detail record, or manage several at once.</p></div><div className="account-inbox__filters"><button className={!unreadOnly?"is-active":""} type="button" onClick={()=>setUnreadOnly(false)}>All</button><button className={unreadOnly?"is-active":""} type="button" onClick={()=>setUnreadOnly(true)}>Unread</button></div></header>
    {error?<div className="account-service-alert" role="alert"><strong>Inbox unavailable</strong><span>{error}</span><button type="button" onClick={()=>void load()}>Try again</button></div>:null}
    <div className="account-inbox__bulk"><label><input type="checkbox" checked={all} onChange={(event)=>setSelected(event.target.checked?new Set(items.map((item)=>item.id)):new Set())}/><span>Select all</span></label><button type="button" disabled={busy||!selected.size} onClick={()=>void mutate([...selected],"read")}>Read</button><button type="button" disabled={busy||!selected.size} onClick={()=>void mutate([...selected],"unread")}>Unread</button><button className="is-danger" type="button" disabled={busy||!selected.size} onClick={()=>void mutate([...selected],"delete")}>Delete</button></div>
    <div className="account-inbox__list" aria-live="polite">{loading?<div className="account-inbox__empty" role="status">Loading your private messages…</div>:items.length?items.map((message)=><article key={message.id} className={`account-message${message.unread?" is-unread":""}`} role="button" tabIndex={0} onClick={()=>void open(message)} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();void open(message);}}}><label onClick={(event)=>event.stopPropagation()}><input type="checkbox" checked={selected.has(message.id)} aria-label={`Select ${message.title}`} onChange={(event)=>setSelected((current)=>{const next=new Set(current);if(event.target.checked)next.add(message.id);else next.delete(message.id);return next;})}/></label><span className="account-message__dot" aria-label={message.unread?"Unread":"Read"}/><div><small>{message.category}</small><h3>{message.title}</h3><strong>{message.preview}</strong><p>{message.body}</p><time dateTime={message.createdAt}>{formatDate(message.createdAt)}</time></div><div className="account-message__actions" onClick={(event)=>event.stopPropagation()}><button type="button" disabled={busy} onClick={()=>void mutate([message.id],message.unread?"read":"unread")}>{message.unread?"Mark read":"Mark unread"}</button>{message.actionUrl?<button className="button button--secondary" type="button" onClick={()=>navigate(message.actionUrl!)}>{message.actionLabel||"Open"}</button>:null}<button className="is-danger" type="button" onClick={()=>void mutate([message.id],"delete")}>Delete</button></div></article>):<div className="account-inbox__empty"><strong>{unreadOnly?"No unread messages":"Your inbox is clear"}</strong><span>Account and order messages will appear here when an authoritative workflow sends one.</span></div>}</div>
    {detail?<AccountMessageDialog message={detail} busy={busy} onClose={()=>setDetail(null)} onMutate={(action)=>void mutate([detail.id],action)} onAction={()=>detail.actionUrl&&navigate(detail.actionUrl)}/>:null}
  </section>;
}

function AccountMessageDialog({message,busy,onClose,onMutate,onAction}:{message:AccountMessage;busy:boolean;onClose:()=>void;onMutate:(action:"read"|"unread"|"delete")=>void;onAction:()=>void}){const close=useRef<HTMLButtonElement>(null);useEffect(()=>{close.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key);},[onClose]);const details=Object.entries(message.details||{}).filter(([,value])=>["string","number","boolean"].includes(typeof value));return createPortal(<div className="account-message-lightbox" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className="account-message-dialog" role="dialog" aria-modal="true" aria-labelledby="account-message-title"><header><div><p className="eyebrow">{message.category} · {message.unread?"Unread":"Read"}</p><h2 id="account-message-title">{message.title}</h2><time>{formatDate(message.createdAt)}</time></div><button ref={close} type="button" aria-label="Close message" onClick={onClose}>×</button></header><div className="account-message-dialog__body"><strong>{message.preview}</strong><p>{message.body}</p><dl><div><dt>Message ID</dt><dd>{message.id}</dd></div><div><dt>Source</dt><dd>{message.sourceType}</dd></div>{details.map(([key,value])=><div key={key}><dt>{humanize(key)}</dt><dd>{String(value)}</dd></div>)}</dl></div><footer><button type="button" disabled={busy} onClick={()=>onMutate(message.unread?"read":"unread")}>{message.unread?"Mark read":"Mark unread"}</button><button className="is-danger" type="button" disabled={busy} onClick={()=>onMutate("delete")}>Delete</button>{message.actionUrl?<button className="button button--primary" type="button" disabled={busy} onClick={onAction}>{message.actionLabel||"Open action"}</button>:null}</footer></section></div>,document.body);}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.valueOf())?"Unknown date":new Intl.DateTimeFormat("en-AU",{dateStyle:"medium",timeStyle:"short"}).format(date);}
function humanize(value:string){return value.replace(/([a-z])([A-Z])/g,"$1 $2").replace(/[_-]+/g," ").replace(/^./,(char)=>char.toUpperCase());}
